---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: game-server-accounts
  namespace: udl
spec:
  encryptedData:
    UDL_NA_ADVANCED_ONE: AgCo/XImT0THWgdEN7IgOVm+sM0EC8xdWk4gft9c/1YGymDzVj1L7bjqu3J/rB3j3QiHWipstHjWCxmqzyi+Nm7h+eF3XNCBBLSsDsifOeahQ2RXzQNPVv/wbLp/1Fc9cC4yyJ2bZb2VbXb6936QkSlprajEHCw/jLEuOnb83fLz6M3RM3HEZACMpavKzoWNT8X0SSrykaTDpkjgzULGQbBiRM2+RhNt4gwvZGOE74Ll/63MbdM3z4RxrCRNhWxrgB0Ulxa+GbCIylQ8Q9aXjOHqz35K0Cq3ttRVMIggLWol7B2KbwZfIu/MowcNJxxK58IL8DhyWL912Fstqxnui/VAe0OLZ9J/UY6bxkgs8nP6D0pXkxnkbGdNv2xgHmAhRncgb9CHxfc1vZ/AqqFUAqqyBeGcne0lSlcqVFjLrJ8goZlIvqaIrLnINVszna8KNrxbhhPZbqv8n2hOcK41xX2slzxzL6pOKQ62tRhX3aoEKT1LOV5bxeZHl56FuZy7mUsmbedM4NN9K1+6XNoHUeUSgO1GLTPfRtMwy3CZ5sFc0w1buF6gXDDw0CUMSDuWnYkY7G0yMbKh5AB9kBnzSzh5P+nmiWqi7F+APg4cRR5TaJUUSBxQ6hm9Lairu2chO7cuh2soFDf2C8BwtyT4DtYRsci94UzPt89W2z4cvhx/k9AjIXU3F7/SUJDvKz5BR5z1u8i9awh95K8yJF1aGzYlZ//LmYOO6DHgoQomeG2o6w==
  template:
    metadata:
      creationTimestamp: null
      name: game-server-accounts
      namespace: udl
    type: Opaque
