---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: game-server-accounts
  namespace: udl
spec:
  encryptedData:
    UDL_NA_ADVANCED_ONE: AgCJMumC1gs2lSR5JxXs9SNxBPV67lLLzkUD3nnoIwkpUHeiZwmZGtMmq+GAggNt/qdW9I0AvJxyoRI+c6mQA3Pie/ETn3qo6ZO7wmYwMDVrpFAjVkVYPaVDmUbdvs0YtkpUiOUTowSVa4jrfeGGzsSseTItmVu/zaeIcrPstGONpfAKbGkdrMMIJKmifvVfWfgz9TAkq5d5X1soQ6n95W7fczc0ruSjtgPXNfBDh2SGHWpSDgQ+ek2lGJQnKJ0HJCeq9k6IHRQ2SWinEuMy1jR2eS4/NQ3Xvxjw0C3uMVJCg8qU/TmmH5q92YERa2DE5iAheeComHoXGHNL1Ebz1JlDi0hy0FMGQm6Sb7GHOz2410b5rgE7JSCUOhTN/6qTZkk0/L0beAMAksfgnMNZHf6k9zPoKyvnIbgT2rxZaIPICwrAW+A/CmUU1bJxDGx9BR26PpRJhVokr0NxqDrfLWoDADgMeDdvqS1zcgghQcb4yRBnp4HfJ0UrcqtBtVd5a0UxvTDhjuS/GmrMex6LN5tT64FI12AfRczyhDCXFh1FlRE5l8SXmoR1f+SyIf9DGHHmeD+sJGgpDnCrlebm5VBsoJPQGqnrk38Fw6+BNfHENTUhC84ZtomIPvwL6wVjFRltEOfz9A3sf+IJbijz1HbvCO1hRrzz3VTmAnQX3SlJgQQM0JjdsTQqGO53k3z6J3tlwKs+dTt5fEEWP9fD8e/cDULFc/XboqNzBdJjGkS2yQ==
  template:
    metadata:
      creationTimestamp: null
      name: game-server-accounts
      namespace: udl
    type: Opaque
