---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: game-server-accounts
  namespace: udl
spec:
  encryptedData:
    UDL_NA_ADVANCED_ONE: AgAIN9vMGpMPGREX0QzpXSmTpx8kJK3z6nP/oDXNlnSoQvGOYKJMw+Eu1aReWCROxWsqoaqt9mPgjXn4MQ+E1qksAekpF6GjBpSCG/oIG5wL5YKgXTu9LqgjLGblWi8aJXZ9yH5S9McCazRR1bF67xp/GKxIM3RZJmIHqGxJF/aPrQO5qs79xg33UcphOoIj+oJnUr1Xu/XuOkQvLw9VyYWZ9z0G5zjvZA0p7K6AzapofGgOduQJUPm3J2lYFJeEXWC1qpMR4xHdIHrN6Lsi5e1NLn/3UTcfumqUV8vm/6qtJEcNqWZySlX9wKU6ADLhb6GE2x8/q1ijAhhRmVyYk7kHGvs9dFfTYR04ntUvXYhHQKTIeyNDS/Y9NMAvP0sj958MIS4fjub+zJcY0eTV4IkPYSsNyJcOZlNYmqIypS+zwgzFELCupqcSBl7U/Rdil0WeQfrU8PR+LczWuIfYUClvEPrzk6xBR9h85ZnottpKv/JZhMFwX1SMvDycYLy/WR8mKLk/Q4FgtfqMaELXRPq6XpQuSL8kjTUcZrw9dspaKtJ22i3WZqbBaAxMIA3IMITGwhfVzhviqtq/nyodmzVpDVZcPVohOLuF1LVRQCo+p+g7o5Jh3joEWnWRFhKyW1bDDnjXrU4WbfZMWTQIGqK42GTqs2KkHCED+4aPbTsBKm5mMjDuYEz2EvDJnpzBRhV+H6GU2exCalLqoTzz8VrvrN4EcIMWoqBcuS8Rgr8wRg==
  template:
    metadata:
      creationTimestamp: null
      name: game-server-accounts
      namespace: udl
    type: Opaque
