apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: game-server-accounts
    namespace: udl
stringData:
    UDL_NA_ADVANCED_ONE: ENC[AES256_GCM,data:O41b9DOJxV3hLQbzZqDH+bOEnVHzVZAZbZLh+iX16S8=,iv:kH5D92H90RHHC8VJkYuTDTEqbGpqgSmbfh1KwvC/3bY=,tag:VVNv6w9qo6kd3ZRXj9oXiw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN2xQWVByTjZKSnBWY1Za
            RVBYTDFhU1ZYczNWc0JnRU5OT2JBRG9QbTJzCmp0VHJiK25SUGlEVXV3NlFBcHNt
            bXZOUlNOWWlFUlhPZjJpWElaY3dEQkkKLS0tIDF6a2lUSGlBL0d1SjlmUVlPek4w
            QXZwb0dtaWkrdzMzb0V1RkpMQlhhc1UKNMCwcqeWQd/ckoFasaRsDLl4g1UJgw6T
            FyKqoBYMMX6l+6DHykmIndgsNEs6Iq+2+Rwcadv7ii6q2f8/3Dq3SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T03:21:38Z"
    mac: ENC[AES256_GCM,data:4FYsIWNOPoEX12qniFCG1Uab08SSayrvZDSCyXDI5fN4fcg0OEj3j8PQeHT8csRHh1wt5FK8EaeYTzhB6OqHb2fZgnmpsh1LeL710RvhmNQexZ5NGj41AV6JuvA+QvDrxvfND+ZfyOdl5NMClMA+Efxd0sqCpFfNtuyV/1KmEJ8=,iv:2pkQ8HlnO9JB5ahguG1WH+mBOWy4Tv9ktSg2/aQ8ljs=,tag:98pDfwgS5UN+2/i2OnbL9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
