apiVersion: apps/v1
kind: Deployment
metadata:
  name: nadeoki-friends
  namespace: minecraft
  labels:
    app: nadeoki-friends
spec:
  selector:
    matchLabels:
      app: nadeoki-friends
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nadeoki-friends
    spec:
      containers:
      - env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: FORGE
        - name: FORGE_VERSION
          value: "47.4.16"
        - name: VERSION
          value: 1.20.1
        - name: MEMORY
          value: 8G
        - name: MOTD
          value: \u00A7fNadeoki's \u00A79F\u00A74r\u00A73i\u00A72e\u00A76n\u00A7ad\u00A7bs \u00A7f<3 <3 <3
        - name: SPAWN_PROTECTION
          value: "0"
        image: itzg/minecraft-server:latest
        imagePullPolicy: Always
        name: nadeoki-friends
        ports:
        - containerPort: 25575
          hostPort: 25575
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 8Gi
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: minecraft-data
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /mnt/nadeoki-friends
          type: DirectoryOrCreate
        name: minecraft-data