apiVersion: v1
kind: Secret
metadata:
    name: ftp-credentials
    namespace: udl
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:EsoHoDFYU1se1ML6Ok1PceIzljN8PxlcrVBLzH3E/MUZL4OZTR3kFPNq+JQJlPaXteDeB6cn7nORVYVPDgpH+FRsPDk/bsUz3A5CenZhxBzqTuaUG7A3kUz3Voe9O9GGYDXxgiOOKWJdX97kTOt5DQ+LfY/W7GU67YfpkeFed/T272wHnQ7R0oEEk7iSNVtnOJV/A2YWWBql0Fbsn1ZT/cQnddaaEM3UgHkKz0Pvd6wpiS40NfA3pj1rOPiKf4lOfyraKHdpdwqm5siPH98PNdJ9jbO6pItS1awfVMT6oS6KML6kQ8M7eMY=,iv:LNzzl7cu3elV1xvgA2yJ43J4qqv+x4XFmISGxLGD8rs=,tag:LdG47ft3ZlpFao95iY70Zw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVklnd0tYZVV0VWE3RFhV
            VCtSOENWcmV0WStISmF2dW9SZGF3NElrSTI0CkxzZnV5QUZMNkpFd1RzSVRJYkkw
            QmRhdk9QMkk2a00xN0VjU1dkWTBxQVEKLS0tIHI3dmlISS9XenZjR2x5Mk9HRlRN
            M3BNUk8rVld1dENadEJhaTB5TXd4dE0KqKc4n2TYfnrUBa2q6/yCuLk9qVM86TdI
            ks17jnYLrX9nYPsyym+nzxtHGsBiXg6AtdgfUD0Rcn0nczOWUeEcnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T07:49:40Z"
    mac: ENC[AES256_GCM,data:7qcYJdqnKSvRCtHluFySNqLgKrdKmk3q0F820wY6eO1SdxGv2m0y6HDL6+/Ou2ESmhVuPGoMXWBPLLuXQI60VRJUmH55PDtXe85DRNaj5HVVBwYGjTFV7dx5/AK8BxhmF7x7TRkKF9NmykEVevVsC96sWkp44zCcyvICCMab2pI=,iv:ThBVYjqxFWjdVWaPxCPWCjIIeIMcWtQ+Kk7nXXHADUk=,tag:tITmpMlVLK84HsGVJfKmxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
