apiVersion: v1
kind: Secret
metadata:
    name: ftp-credentials
    namespace: udl
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:tHq4Ge8MW+OnLl1xWgX00geuxFQNTLP3GeVK781eMU9HlwgZt+hyGgrzAixrL6CXsMw9ClokxabT6GEqW/G5ka0UlL9t2Zllo8XUvnV8ZxomXnRph0QIMprjn8muExgYwcI9Xfw+KoOdqjC3S9fN0fouhcBiJxvD37X5cmXCHZ7jCc076B5WXXE9kvJ8M4uhHPyvIyfMrfscQIa0CP7Xclc8I8lqMbvzbhFC4XDSI2ACy0uwFMj2mssjTIphMS0LDCGsDr/pkeMj0Zu2jwQpe2gxNKaXdW/K8d509on+8YfKfwmcErT11BE=,iv:ijgyKZJ9U7WFtDChdVOa6uOwr2f190SuUIE3dYOAbyY=,tag:6VSIs58fugRzDjFE/CEAWw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMndFYzR4cDM1SU0xVVZ2
            aDA0R21mQUpNV0NMOWkvOTN2Z0lMc0d6d3k4Ci9QQjFoY1VWTlRScXRnVmtPVEM2
            OFo1d0g5eFFsTnRtaTJoYVE3bG00WEUKLS0tIEZjTHRLeWZ6aEdIY204S1JoV0xj
            elZxUUtIdElhYlhNTi9OdVIvZnBDaDAKXDJ5AEoQMMheAkaTM/+dolUZWHdoOp+b
            pyoJtfG3ikYNM63SLBWCrfJR6ukaszT34kb1E4rZG6vCi0u5L/w+tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:42:15Z"
    mac: ENC[AES256_GCM,data:wExPAilcbY8+3+zjGptjTWXUwCt2V1DDwUY3O3DgWTGXNjKjJbDFaNFb+hVxVI2eSJRNklx1C0r/SEfC4E/i/5OVmrClTYXKqJojC2DC+l+D3gjewogsyTMumcHqCalqiJ0hVm7kSsS7vapWPFwhCAPrgN8H9FNBBKpw21TCvBs=,iv:kS6yFCFb1Eh7mLuN/Db0UzRXzHoqRrkjmy59Uha06bQ=,tag:xo00RxPBHV4lBMVrG37eJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
