---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ftp-credentials
  namespace: udl
spec:
  encryptedData:
    users: AgBKN46P7UV//D6Tu3euhYT1biyIEarOHyDT5RtyjWU5bi2J5xHVk4JXasKHOaA5FOp7jdvSbIAvL88RbIcaJQnv6TbdS9AqQnnu3Z5YvcDRH4GB832d4URjKjc0Ld89vIJSDWEbbQFy/1f35d8oUdNclsnx7+y+tFLqsf/lB5IQ3xjL+lMQzsgNLkyiY+GnQYyF9Scz1+/CdXV2W7NOgrBad88D9a1Hcn581ilnvxT5/Bt55bjvfyCVqSp4MX8VElxVbz4rB8fjMJshkZitftsTQxD3UOL8e6tMOVLWqgNC+F/qOU5Du9TIala5OcI7AzZYaAbaQVFFTFX0dTNjOzIRGIVU72VL5X1lN2PvcUvZoCcW7xF9MLMbj2ta/+XKP6HcqFxZVNsFKhKzqccFt1nNjIAP+4ERhlncKSGsoH27UnaYcTXLjrxVPkahugaeY1+Lr9zw7946aFWH6Un7fcftCjdgsuK6Ye/MXfskQZKHWXdvKWwjjm/Y+6w+BxjcrvnsYC6TAxvfrVE010tqHnkIJN7zaKQPWtG3qQbn0gecMhEJGl+QBBiQQNLj8lUpII0BpxnpwCOcNTyUYJdU8l7nfZe/Cexk9NEIN/yvTEtOPh9JS/9bQ7/iBFbMsVCpH6HNb4lYmcvp8K+H81x+2t0+CU+0A2YUKM01BGMKfpsnRrRPkvodWLdVB6qqXcdy+9OfLGY3k48FIN12/WmRMVAxXYtP+LCEx/nEzLIyUTgf7wzijxJk0QTmoEy2iZ1IXVNMoqFeCGOMLbuuprj1vFRJBc3sfMC+9+Mv/H3ZHEw+nlpmlEO1k/lrc7dCdsud9ucyfoLU6K0603zcKH3GfF90X7z/saV47D/9lcjFQ0LUHBw7B2PBdosPwwrwB77DEd1D65BJs90wj6YrEP6XVbqyRAbuoN9wmb3Gl/nnfNlBu8lbl+r3DCDGOtRNxFAuzD3jECHlKHlPS4OJWoaLdWKcEe8Q4LVSw7eYO297+WE+kGe2FmWr1EoYaQ==
  template:
    metadata:
      creationTimestamp: null
      name: ftp-credentials
      namespace: udl
    type: Opaque
