---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ftp-credentials
  namespace: udl
spec:
  encryptedData:
    users: AgCGhB/HWQtZvuqEnl8xxZzXXOD9aUYlV/0s3gRn4fLa087sOp099fSTJ8bMXVBBE7xJ4nYTgxH9YjLKwCN2aFwZauSBnCOcKI6IBu434mB7lAnimr0BxPlZK24+UmReguVypNGYOYePULT30XkvNmHf0jKibQP91jvi46kIZY2E7mLpoyu/ZiLsrjNl1NRZbi5lrLbXfuhxgsslMg6bk1i220xzGYDmQ6xOP9mE3ffqMRb2Z/dApTckNj3oElSALIkS+KP9YA4LA+ag/LCikXO5PmE0kjhkCX0DWov0KuMr/dCnk6AUCc1CEztLfaX7WpKb9sOU0pKbWd527+XROuc9euBUfRM91HQRdasa53lSKCD1wjFw/ThaaCy5NZ5tJu3HbHqw7fWE9+KESXA/EHLJPDplDnVMAeos6LmzEo3smoxHEpNj7FmpDCA7mvLRIBlPBjtAbiHzQhFE0y1KW3JQaxjaPpWF/QE+JzII+p0ROXG9x/rIz0F/Frv+Y94T+2Ayts7/ws3Nc7cloQ+FMF0peOhZuephyF4u7JgrnZ0Tm4dRcEUtaZiijOYFtIvd0FArqfPTdcPwd4FHdBkrEfUqETn+dC0sCSfFNzH4/FWAdh21MKlbTH0p4SU1Nwtz3P5O2XuKnA3SHU3Be6iJYCXu9cR+Umg8F+Cb9jtiWt0jbotTQ0FA64X3iSV4kKgQq9KFHDqX9VH4Lk/JuJ+c4o7kqMPLCECZVFf5/Xa7/PPA3dwNf91+oNvRaW6ouvF8dsOJbRJwfDYvKJVMdjVAT+2kYIy4/TFd/u6vmHSMrUCWjGXilXP5P8rGoYL7+y3tFtu9KzNLOMZw5cEPpkY66axt5R2pDvhdigyAAeZsDdif/+BEFvePIh6ZpbB1V1kj83rGasZhdBkEvLRhRM/PZyV59mWDzlN4/gKuIjYDabOFF2ffjfERFUYWy0QOmGChbrHdplLDmB+x7dTcEjOHwnZwBKD5AacM/8QIbmYrg9frEmKORzBtj2Bi4A==
  template:
    metadata:
      creationTimestamp: null
      name: ftp-credentials
      namespace: udl
    type: Opaque
