apiVersion: v1
kind: Secret
metadata:
    name: ftp-credentials
    namespace: udl
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:/d7mNjoUW1Csk8tKYhB82Y3nuEVvcZ9pso8a8UDt3YRprxIxYLat+8ZQ4LVGGVxnS9dJekzbABYbwsKAMq3LNbD5Kl55Swi7RvLXz3a1EuomFlHE9BmfVTLryjJEEJrQj9Ki333cg2pVW2Aaund0SGuMxXvzm9Ekb8dQ1q7MF6GlRsuh0Pap1IYAKuS0BcFFAc0xWy/fMnsr4LfvJFV1+s8vHsPaCgZN3dy9dmpgaiLlMbnKLemVIOvNLbOulL1BRQ9M2awDAKk0lZ58BCgor0dmqJIHEcTLMwNnWKkKwXI3dF0EFfRRA9U=,iv:s2GkmUmtKGTof5shEqcM3Ah5KNhaAOMimUPowwh+EtQ=,tag:8A+gZDqzjVWWuvRZ+QdaWg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bmxpd08zODNCLzNXaTMz
            RVlPOGVHTFVPWTNxVjVIcmhxNGdwZTM0LzBjCjU4bCttVzRoaGd5Z3ovYUowWFZi
            WTNTN0V2RXR5OUZyZnlmbjNRclYyem8KLS0tIGlNdC9SQmhsVHlqa3VsOHRoeDBY
            S1oycnkzYWF5eWFoNU16b0tSZE5BbUkKJJ+6HEguo0nd5qeuKVgUvarAHO5eJ6QZ
            h3Ml4fraA3HE/igFaa5V6J9XmEdjos0WJoCRwjEbwiKNDwuUh7eNLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:53:18Z"
    mac: ENC[AES256_GCM,data:t70fOupJMdDcchdVbCv2IkM9RJQrM0AUE1HXYY5Sf30M4WqC8+PGBqc8qrwvTfGIUWDMmkUSXXuOWBxY4w1ieomOYq1LDkU54tDHBAu0tXcFbuLIRpBdBrWQSeUG5RcvVzO4cyRZbaT/FfrZ4ST2mcYb6FFBmsWutftIbISMKWE=,iv:FbUVnqVj19XwuRxCmGpdfCyyZpN7io4hMS5u2vEDe/8=,tag:UuAjucAZuOZ+PJO1W/Ie6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
