---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ftp-credentials
  namespace: udl
spec:
  encryptedData:
    users: AgCfmQn10NLSCxtV94/GZuif9qfFUTmoR/29HjEGM/covohSZpyyKP9pGIJEOtZ2CYVXzNH/2HdfwuZEeLxXEHZJgr4RsNby7T7HvyUIioI+cknk4P/PnlYuFIfeJ4XBOhrupf4JH1zjo95neeIfawSJRU1PW79FkE8lF31xmpf6851CO4c2L/GctuhN/2Hy85c5FdVneqbIws1YF7Tf7pfQLjOttg6hypGkfP2l8JSoXKdkV/7sRuOAJjpaQgWiX26RXuyEkyjPspSuoFDrkUg+qVE6a3VCNVd0oskHKlzxzF2rA3dcNK7TMc469bemd/O9ZFXSo3p5GeFSWdzIUdBJkZbfbLuyeXfTFvozdTEyhdFuaDA/50BW1eLXOeIBDSYgsn9F5M8seNLv08pu4Yj1BueQfnDObqUBVfrVFTx3pN9t1aD6LfhbZRs9ML8H9FT+nOh6f0aC+pze9w7hEgNEFQkJK1N9Und6E3AoxdMeCNg4jwCiDpd0febepc7UcRB9cnp3I1SlVcv4xNeoLASkeUqMXHlgJDOSd4jKcyLxsrBgRI9o0YLIX2h+bQPOBxg5J1f6RyBf8fhvkesG01WzrfDbzMTY1OrFr9vChG3g6RfZXPVkBTWkmbRFYfeeH1BQcyCOF1g7faicPSU0EnatXO5wVf1C3Zbwu1+0BDKVscWj1cTkxO61P5IVbmnV66Mkkv7pK/lAtH3+/++jApLNQ3lvx8tAaUSOe7RT3kdgAmOHXzCX4DRtH1wC95HR1WVgysdub+UIZgbfrxo7J7lpsZ5FaVxONGgd1dMgBKwuBhUZCEqMc5CHnQLWefV75Oqiudh40QmKs9huc+7esFU5azFaqocVD4i2NG6CQTfr4o1+s0PS9EgqNTFeSKryNhPoOaSxTsI+eJnyg8ZfvvDwkpQm5Tc29sAAYArQZT5C24d9dJW9wul8kG9YLdFuWCN+xFdmQaSICQKxyBP4/ssJeW0phw9voqOs4ezdF2WFACjsrsCm481lgQ==
  template:
    metadata:
      creationTimestamp: null
      name: ftp-credentials
      namespace: udl
    type: Opaque
