apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: github-token-global
spec:
  externalSecretName: github-token
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - udl
            - flux-system
  refreshTime: 5m
  externalSecretSpec:
    refreshInterval: 30m
    target:
      name: github-token
      creationPolicy: Owner
      template:
        engineVersion: v2
        type: kubernetes.io/basic-auth
        data:
          username: token
          password: "{{ .token }}"
    dataFrom:
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: github-token-global
