apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-one
  namespace: udl
spec:
  chartRef:
    kind: OCIRepository
    name: tf2chart
    namespace: default
  interval: 1m
  targetNamespace: udl
  values:
    workload:
      kind: Deployment
      nameOverride: "test-one"
      deploymentStrategy:
        type: Recreate

    app:
      name: test-one
      image:
        repository: ghcr.io/udl-tf/tf2-image
        tag: latest
        pullPolicy: IfNotPresent
      ports:
        - name: game-udp
          containerPort: 27040
          protocol: UDP
        - name: sourcetv-udp
          containerPort: 27145
          protocol: UDP
        - name: client-udp
          containerPort: 37030
          protocol: UDP
        - name: steam-udp
          containerPort: 26925
          protocol: UDP
      env:
        - name: SRCDS_PORT
          value: "27040"
        - name: SRCDS_TV_PORT
          value: "27145"
        - name: SRCDS_CLIENT_PORT
          value: "37030"
        - name: SRCDS_STEAM_PORT
          value: "26925"
        - name: SRCDS_MAXPLAYERS
          value: "32"
        - name: SRCDS_RCONPW
          valueFrom:
            secretKeyRef:
              name: rcon-password
              key: RCON_PASSWORD
        - name: SRCDS_STARTMAP
          value: tfdb_octagon_udl_v4
        - name: SRCDS_STATIC_HOSTNAME
          value: "UDL.TF | EU | Test Server #1"
        - name: SRCDS_TOKEN
          valueFrom:
            secretKeyRef:
              name: game-server-accounts
              key: UDL_TEST_ONE
        - name: SRCDS_TICKRATE
          value: "128"
      command: []
      args: []
      stdin: true
      tty: true

    paths:
      hostSource: /mnt/test-one
      hostPathType: Directory
      containerTarget: /tf

    decompressor:
      scanBase: false

    merger:
      watcher:
        enabled: true
        watchParentDepth: 1
        pollIntervalSeconds: 10

    writablePaths:
      - tf/logs
      - tf/demos
      - tf/addons/sourcemod/data
      - tf/addons/sourcemod/logs

    copyTemplates:
      - targetPath: tf/addons/sourcemod/configs/sourcebans
        overlay: serverfiles-base
        sourcePath: serverfiles/base/addons/sourcemod/configs/sourcebans
        cleanTarget: false
        targetMode: writable
        onlyOnInit: true

    permissionsInit:
      applyDuringMerge: true
      applyPaths:
        - /tf
      user: 1000
      group: 1000
      chmod: "775"

    hostNetwork: true
    dnsPolicy: ""
    serviceAccountName: ""

    service:
      enabled: false

    podLabels:
      update: test-one
      restart: udl-servers
