apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: minio-creds
    namespace: minio
stringData:
    ROOT_USER: ENC[AES256_GCM,data:zaptbBEI,iv:TyQo2wDCTIc+tKSMTKcUCw44+4GHjgXmNmgLlBJdKt0=,tag:mFSkclwguhpgW281DmHGtA==,type:str]
    ROOT_PASSWORD: ENC[AES256_GCM,data:0WAAqDllGr5oQlDd5F4O3/PRJNqqT+D8CpLgry97RkwkEijGrUeP,iv:WU8DFJXG6KQkfkdZcINPR2xKXC7FIThGsnGif8Zuexo=,tag:DFvO/bBGPCeZmzVBcivp6w==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTEUveTBUdHZnbDJQenpa
            VzNnZGM1WU1MTDdzc3ZwbVU0M1hkMVVGbVFFCklLSURVM3p4bzZWaDJTM0N3d3I2
            Tkw5L1R6TFVtRXpRRzhSdXlDWHZjYzgKLS0tIHg2UTJ3MnM3ZUZzdjB4S0d0aW9T
            Q2c3bHBIL0t3REJvNWFwZEtycTF6WWsKxWh3jcQKrYrDIkaNjcK6THPiqeqa649L
            27CpvveqSS4nKsVRvgt0cOC4l5Nk06O0FB7EfprA32Tg9veDjZIggw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:04:53Z"
    mac: ENC[AES256_GCM,data:Xf/Lz6j0Brwt8zTRdIcXE/vbxMhHiFnjeDhiBy4z8q/aa3obuWG9ISiVAb2cduChtJiXfFCl4yyiD2ZPU8awQRTMtxrOQlFW8O1bsjDuP7cSmMj4/u5y2AC4Ou4k3ljteITs37xz92zf1i/5oZ1EoADkv9qx/VfsBfO/klBBqLs=,iv:C3ex7nRvq5t0pnhTDG1M8ZtdBkGXZl+YJ7D7msEEIDY=,tag:uo+3A9ZYucuuGnKroAza5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
