# minio-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: kadalu.s3-pool
  resources:
    requests:
      storage: 150G