---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: minio
spec:
  encryptedData:
    ROOT_PASSWORD: AgCZ3kw/o3pcf07567hScTC5Ai4Cu1EDDENsRZHWE8BQWBldynC4ftZ3BRD+p/0ZUrhGko05Q8l1nua3IAHMGXd9NLnu4X8OKYmxsE0FdbQHHoZinieU7tEjh/tyOZ7YZZeRcfDqdo8W3eojivR7VY4Lr+gp7FIQaon3Q2FTDV2lyDZdU0F0n7Hx86uQYz5joNMjFRtrDI/Y1rEKtkD+RbZ3qqhJ4yvbagcKbGC0TzU8PZwXFZ4DVMg2BhMlEGSHzgpxfJkHegcN0IG1cEFVV8xpOXOIhMPlXySdEVwJF5riTTrn6CM6cO10aCiq5DIz2a9pfrCCnSWBXU+m4EvzklxijErx+4EWXfvOrnznErfb5VFWpUIPYBHtech8wFXB75diAMisc6O8ndQt9bhDaIVOxXvCYgzK688pZVQ/RTSem6Ui+QLFTm3dJfYatf7wB7HyfyJLZtMJBVKfG8k6vSTujS/L7oShOtDzlR4DC8b8stBnAbdC/OwGjkZmG7WfQOLgwKBgqZvOMXFhFNbxbj1JA+50BDT+mrJmq26Cas6Tejvf36Le6EF1RhFKRh88f++hnQyYX9UTw5TH+WkItjGqw9yjli5jLmZb2r7QsJ3M/xk6j7f1w9XfaGJR7ghVtaFzV0bYVGq71WfjpbeY7zBEdPmnoY+71ykVTEAiztjQsZZq0B0omEg4mHNIRWiyI2UzxFlogG/nw3uzDvefQXdmJF/6BR8emMTFx7otllVcyZ5v9wxCxZs=
    ROOT_USER: AgBce41aUgLa3sfI89ZGTE1Fm2HOHP7lO4NiU8qTJ9BnDDmn7i9uq+N7jxK6M/yd+ohpF2iD18tUHJ49aR5pdagcfKHMSSsFimuuwxElhhwiMEQs/qdpp6sAly+w3Ye3nKAiHx8/xi26EV2zA9ZNMHp+YuwAc4a8T8kfUW09OG1NiT8cbo0tvoECayaIMv1ELFEQyYjq6pbV6v8NHu6+lTF1l2WCiK3RKNa1HPRlTzJpTSm5ITcnZhiLEE1yiNBtiycHw42G66A4f5+4wwkcYiCN0lZOFy2jAastavVyOVTwSYAKHrft3/4REzTIHaHExgdwVvGZ9n2Qqq9ZyLBDgBp4Uzwrkq6nQJvT++kpOmET+/kcm0yWuZhrTnEElwrbU2OnPS235zDkRmTZ3mNYFEEq1anlqHbXBVY/MMExvnJVFeBDVOnpeJXj1uqJ2WeRLIVl7i2Vl5Uqv/I0ciLUgIclgUFXgj9zzD3gc+BZKgDAr9Tyq+vswkgdOo13tPXG9yiuy/xWW4g9VividmvPLfeYZIlWulcL3njvvgO8ysJVJ9MqrghfzO3jgb+NImOXNuMhUkjbKo9pW9pVQnJZ9y/Y1ot6uUaGY5em0OoAOxokdm2jM8+tj2neoC7l9E6HY7vTEjvEAImCWrVBbXoH/iVffThTWCclexuSJ1XRbOoSXxYilp//jakYGGJl405f6fj5jtabTzs=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: minio
    type: Opaque
