apiVersion: v1
kind: Secret
metadata:
    name: postgres-creds
    namespace: yagpdb
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:coNZmRZL,iv:64fhkLe/lRXk0cVPaTGF2wwKFQhZuZDGoP+NqpNBsi8=,tag:WXuIMnDXvNc4FrUGEw7hfQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:6fYznags,iv:0/JH54njlsPAYhH+Vc/DwT2ePIxoUFmqRsmXNWFUz2o=,tag:XtTRxEyCEFvRoag/eTlb8g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YguA/82XtepYyeIIepe1jQBP6aUnPsomJ4w=,iv:1R0zV3xyus7jQ1csGnT6Cl9Xl/6N2u1Zy/fPxAQuoho=,tag:/v8X1NiKuw8t0x3lcW2ReQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeVRxVnRnMjdBYllrZ0Qv
            K01QQUtVR3c1RXhWcG9SaTVGK1REMnNiV1ZFCm5wWnNFazhLbm9iL1RoTkFpbG5r
            ZW1UUVVuVmphRHNzRUQzdkZjSTU0YnMKLS0tIGhQL0Q5ZUExZDBEVWtxT1BPWHA4
            bGhiNytjTVZXVjBYZGdjTE9tdU9tV2sKVypK1WoEf37QJz3HBY2EXTcSO7bPA7K8
            1vStqlIz8lN2Wfzqc+wuxJqJw/VbpHzKY9J0ZVWYBK9gWRLXsrlA/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:04:53Z"
    mac: ENC[AES256_GCM,data:J4oUGav7FZNxIkLYj+2uDzSxs5+BBCM38Gd+wWxlTiF5iMJj6RZlt6E0SWhZktTWiliS34hYN7AV5KMJ1aOkDcS4FeWc37iBwHQwW++U578at5bS16Iehv0ovLGaW8qmLYJgbF7d61On2F6d7VlBjjsSX3NjeMo6BBq+PAmEiG8=,iv:RbmQjBH4x2MJHRmpGFUKN3KnnWsXquubvdtoXoIGvvQ=,tag:IfNzhx6+OyhaWeHZufGMXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
