apiVersion: v1
kind: Secret
metadata:
    name: yagpdb-secrets
    namespace: yagpdb
type: Opaque
stringData:
    YAGPDB_OWNER: ENC[AES256_GCM,data:QqTZnkmrKR/FEjSdMQzQqLU6,iv:/wMf4SS9fq6HHOQIWYhy3SVLM+vlYzV0VdYQZXyWmcg=,tag:2lnR8mKaxbOWxFYg9noIVA==,type:str]
    YAGPDB_CLIENTID: ENC[AES256_GCM,data:hlx4t7olSRTFwYOVflMrGYUXEQ==,iv:1+yLhgJ3Bg0xITHpRjXpfhCa3WDXBzTYzkFHudkX8lk=,tag:WRASFUjd6eLrRXAYU2IFJQ==,type:str]
    YAGPDB_CLIENTSECRET: ENC[AES256_GCM,data:dcUihc2aAAsvzrMJk/bbTUIEgRYCpPnau+24+2fSdcI=,iv:9qbM6DVri2+LCq9jhzlWbmOTjj5eekEwATscfAXBsb0=,tag:xcBIKWcP5opEkeXcGTkiMQ==,type:str]
    YAGPDB_BOTTOKEN: ENC[AES256_GCM,data:h/dZ98vW4kMLxRoV1qz0KybZdlnayU6Ccn9VTxlyL1GxBinZWA3U+QZp0SK0lg9EHcXwZ4Ak5JXUcFKp4oXWyaR8Fc4ymhpax2glFg==,iv:6g6SRie+WTRNAlNfOHtvO2x7KnRggFGdGkFQNIYHKcA=,tag:CGnjs0L7jtw6LBN7iPtJMQ==,type:str]
    YAGPDB_HOST: ENC[AES256_GCM,data:Y2ORrIsMSVx9Y8rGQA==,iv:Y7sr5LJGPU3srK6U1dAPxdosRTcym7aO2dAYsmQ8cTM=,tag:kvOFuqqy5h6tAg3YgXM7cg==,type:str]
    YAGPDB_EMAIL: ENC[AES256_GCM,data:0jd1FvEI5JbvaXTwfw==,iv:3LnOm26Tovm9+fs4XHzB7yPOlbnWyixi3n6MiE3MZ7Y=,tag:NYtqb6z7HNBCsgDq1lPSUQ==,type:str]
    YAGPDB_PQHOST: ENC[AES256_GCM,data:GV0AH+ni+MM=,iv:LIPPkydRhXe1KT0n1ywNFbeuP/9KHzOCTaM5wu8gO2M=,tag:dKX87v1mbNfQGHt9gS3TTw==,type:str]
    YAGPDB_PQUSERNAME: ENC[AES256_GCM,data:9qqF+qBI,iv:1QTclGpSIELHgU2auGndn8qyYDBIw+4fM8VbZuKt+Jg=,tag:dfzoKqifvfJ/afGjiQ2/EA==,type:str]
    YAGPDB_REDIS: ENC[AES256_GCM,data:H8lU54U/QUmd2g==,iv:w5GPuVk06VAVge+OFXomywiQDnb6TF+Lh8SO+0hfmZs=,tag:WIhDs3CZL/4TFT3B+DjqLw==,type:str]
    YAGPDB_PREMIUM_ALL_GUILDS_PREMIUM: ENC[AES256_GCM,data:N08K6g==,iv:Q+VxWoEynbkr5D5FGdjFQKk7vfJHJWbIyPOcUZ8pVWw=,tag:mOegKu4h9F7PxScwLxUHXA==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMDI4KzByYk9qOXlEQ2x5
            aUpLdytkYnVYaDdnWnFmbHlySmRkZG83R0cwClFRdndXRHc5Z0dpN1o4YkJPUHlz
            Zmc3UUpYM1FxRzMvYy9XUnJEOGpaRzQKLS0tIG5qS0FVS1NkdGNiVnN0a3dUL3g0
            WUUxbjhqREthamJ1S0l2TGZIb3d6cGsKuPNYG6XV5n0N2GQ0eA7fjYQngmLTlgSg
            uaBS2W+6bITXAlNltZWKn79vlAktkPqAw4bp+5ZjlfF6Ij4RRYTnhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:42:15Z"
    mac: ENC[AES256_GCM,data:JYRGv5IPMU2yMl5NJoESsWVvquwIV5GZ9ZYaTocMRwZ9K6rhmoe2VVgfZShrCXEOYGSbL6lJfIoLsLxC9yLt85o+AuAxXY4+16TubdcVeATLDQKnH3gMscHhFXSE6m0NcKM/wUTO/SecSlMtPNKrB4seMflQHsUGLKZ85y/7BX4=,iv:VgYOtkS6SE04ucu1dg6DqfaNEn3PV55nmQhnsUZa52w=,tag:siTExJd5yM44T7Z9BUVLRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
