apiVersion: v1
kind: Secret
metadata:
    name: yagpdb-secrets
    namespace: yagpdb
type: Opaque
stringData:
    YAGPDB_OWNER: ENC[AES256_GCM,data:nZlPTnR5zyQ+GW56adHAjPLU,iv:VA0veSLPpFRyZFkh5kBCntCBTtyscNwqN2XN0ZAAGqc=,tag:Otw53j1JgM9V96yrNO3XHw==,type:str]
    YAGPDB_CLIENTID: ENC[AES256_GCM,data:Pm40pVTsz1xQ4dDgy+DHM+4t4w==,iv:4K4S7gSfax2OeZQJ9st3C6hoSWwrtHhjQAGMfmqFaNk=,tag:9HtZQjcA7L9o600nFM5Shw==,type:str]
    YAGPDB_CLIENTSECRET: ENC[AES256_GCM,data:nkRcU9dkOkwb7I7qK3reyL7Tiwsekf3s7zX63WWBCjc=,iv:7TzXSuF4QXLU9+eW0nB3yy2eg7N9s1sWxvI3AnJOKmw=,tag:n9TPiiVOp56uESRtUiq4RA==,type:str]
    YAGPDB_BOTTOKEN: ENC[AES256_GCM,data:m34KaKKKDCeYTkW3OrXrUBVLdICMs5ybA5qYQ786n3dM0X9Ph4atoOUpPZXuW27C0FVZbVx//c/Hb7AF2PWAMfmHxpZRv1xbe1C0UA==,iv:nupJcoYebET3oV7NHjfDssDuYtP/tuoSvql5xbq8HTo=,tag:ezITD8jFZUrXHxilWhggjw==,type:str]
    YAGPDB_HOST: ENC[AES256_GCM,data:tYxTyY75CVfdoBd3pQ==,iv:uhOT66IgDiW/WnMbL4RuGFvuEnas2ltwWuFvdnuLZA0=,tag:uOb9IH3lTeEyk6XIkU9K1A==,type:str]
    YAGPDB_EMAIL: ENC[AES256_GCM,data:EeU/I/wkgtbMOqHapA==,iv:WnoQXgGbpd7udvtsAaxXxwsUvl5EHz2xsiBMZu8qYuU=,tag:9X/H3zHRVWTgi2xL6u7GhQ==,type:str]
    YAGPDB_PQHOST: ENC[AES256_GCM,data:k7Jp+NIPRCk=,iv:zwcrjriZZrNCSdymJnPiMuVThGVYb/PRLNLG9l5juHs=,tag:RwTKS7wibKaDoynArvZAFA==,type:str]
    YAGPDB_PQUSERNAME: ENC[AES256_GCM,data:9j8rzYpz,iv:R5G5FSJK6VJaUGaR/NuKYHnpMX2a1S1k1cEJS83PTwk=,tag:UTB958UeEMb5/+jFCjmxmQ==,type:str]
    YAGPDB_REDIS: ENC[AES256_GCM,data:2dOiOeuHE2tnHQ==,iv:ZDmmYI9BuOfmO/COyy02X/51+DF6QkhXCttM+4RfzCA=,tag:CU2Uk9VK1puBvDty2FbgUA==,type:str]
    YAGPDB_PREMIUM_ALL_GUILDS_PREMIUM: ENC[AES256_GCM,data:R+EwFw==,iv:/yd47Nln4X3khVfcy2si1D0rYKU2zAXaQjn6OU6aWjc=,tag:uofaP8MJXCIZDtp6F6F7cg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z01sQ3BRbnJKdk4vR2tR
            VXk1WWM2N0JMbEgzRDNMUXhNc01Uek9FY1cwCm9aOEdUVjhEWnBZcFhUeVFaS2ZI
            VUZ5TDF6ekNtRHJjd2k1QWZwZXR5SEUKLS0tIEpGbkZuYUdmVkpib0diUHJ4Ylpq
            Z3pYb2ZjL3h6N1o0SHVlSnZqaGJnVlkKTdraILT3RQAjaBBUXfjxO5qOuBwCHL6y
            Etjdu5jSiRrk/HhndXZQryjxNE5sZOCQkGTpG1pPhiyd5bdC3ObZ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:04:53Z"
    mac: ENC[AES256_GCM,data:EGq+n77OFQKKq9WKiRLDc5Ghff1Q8bSivltCTd0DcujhqhUJSriNvasgymyCdHcvaeyLgkfD3OKPp5Wf8ENQswyums0dAobsNWi1uoUEW/pFFgxKEqUA/69s/Vmq802wFaKTysqT2nt75M55jA7fvtQNLbsvUj2Xt9c5qTSBkeM=,iv:7aX2lSQp0VDxmJAYijDWkIeaRsp4TC4ykrLt0ROzplo=,tag:vym2+BIjpsJpkCw13uBgpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
