apiVersion: v1
kind: Secret
metadata:
    name: yagpdb-secrets
    namespace: yagpdb
type: Opaque
stringData:
    YAGPDB_OWNER: ENC[AES256_GCM,data:JMxPwl6Q0ezeeIJ99h3UvU2K,iv:Nt9rbUKYJCiD/5xWrIXhHOqCsszcjgSFVLRRrEuXDGk=,tag:xmA/hbdyoCovr0/2Z9x34w==,type:str]
    YAGPDB_CLIENTID: ENC[AES256_GCM,data:JGCbShuaZhQconTKxatMnPFAcQ==,iv:dpa16VRPP772tr8PRx5sUS3YJ/MF2BjBuwIyYsAzZgo=,tag:nU7hEL/U+z991JIPOCaGhA==,type:str]
    YAGPDB_CLIENTSECRET: ENC[AES256_GCM,data:OCgpcZyKD3V+Hzopkm+dfdUEe/Xp3c1MNn8xYXrTnNw=,iv:I1rgMQw89GYtZCEyPCDPPSA3uD+wqWaXxlm4lxmN6Rk=,tag:5CwVlL58OdEMR9yZffax9g==,type:str]
    YAGPDB_BOTTOKEN: ENC[AES256_GCM,data:kvLeewIi8SZNJjU3u8xYE4xuaGB3TqxN0mmzKWtCIqda/Eg0Rkp19FTflxitU78GswZU8nxY/g9NC5K/ODnuRbiy3gpk3G/pHjnTpA==,iv:Dtb0vC4kQ/+ASzsnRQjEhOxDWQS3Xtj+SP1UsHXw7W4=,tag:fOUah6d63vmOvdQIhthwdQ==,type:str]
    YAGPDB_HOST: ENC[AES256_GCM,data:+PBSMZHN7RI1m49DMQ==,iv:YqGoC5WI1ZbRzHd9PKeEus+mfOORSAe5pEQ6MaaOraA=,tag:ebA35pF3f9A4F6iBBtzEcA==,type:str]
    YAGPDB_EMAIL: ENC[AES256_GCM,data:8bQb/DDWtazOyJRSbA==,iv:zhH/A6cjPeuNTgz6gVXZ++HJtDGVRZcaKIUnzxFkRNw=,tag:PFytThju+9zY04mgt4Rzrw==,type:str]
    YAGPDB_PQHOST: ENC[AES256_GCM,data:Y7sWZm3sH/o=,iv:PZ4M8ipJI1RtG1zOFCwXIXFMODo/M/r+ndtc7knOsdg=,tag:XT6lvutcfClyoHbg20+3pA==,type:str]
    YAGPDB_PQUSERNAME: ENC[AES256_GCM,data:KzM4paHo,iv:Yh6lb4HTKEKDEAbQXMWNXLdWB8JyhuX9QU8B57hPzy8=,tag:vGwX/DXb8Q3hKTjsaCWMOw==,type:str]
    YAGPDB_REDIS: ENC[AES256_GCM,data:otXW9GhaIc9NZg==,iv:O/p8a1a38kvExC6rVcHgtRIKO0Wj48llsYP266oMJ1Q=,tag:4t+KbCWEOg2gpFEbDs6CZg==,type:str]
    YAGPDB_PREMIUM_ALL_GUILDS_PREMIUM: ENC[AES256_GCM,data:9+84mg==,iv:kdkgJHb4wqfnvT3ge/UsQKUd+0Wi+Cw/Ok4FMXYSI78=,tag:ojMk29f2cGnqEhYryEXVaQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dW1mTGpPanZ4aHJ0dVFx
            UkRJYW1NQlFPY054NDN3c0tHT2JYWk9WT3dRCnVCL0JRbndqdWhjSTN1eUVmMURB
            TmZPM3hNL2NhazArc1JpNHJVcHRRUmMKLS0tIFhrOWVlZHQ3eXRpeVhEYWc1YlJ5
            Mlo4MUpoZmNTWVlSQkcvWUlxZGJ0Q3cKfDeUiUqz+lfkw0FyF2qvaPwrWwXOGxOi
            lDOfY13+mzdWffrL4mwq2ARviQGulFeNqEoygZQVrjb7+529b5P9hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:39:03Z"
    mac: ENC[AES256_GCM,data:4qZGvNisaeq/rX0Kq4EANMFKain7PazX/OJtisvSTtF+qlTTeLFfXixMq/Vecp+7JvETpcXI0mdYdimkYWbzdpzvW9rmpiHVPBzUAbc8ztgEMf4RC7ZPy970JPmaDhV5WD8T3RtYWZY/fG7+WCMnN4PLXRMC5ULETEHLIIKWm2U=,iv:7wXneHhtX+gSBNkV7kqmvPz/d6CL149wsk8x7ujpnhg=,tag:jLPUi32yORcSA/UQmkCxXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
