apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-two
  namespace: udl
spec:
  chartRef:
    kind: OCIRepository
    name: tf2chart
    namespace: default
  interval: 1m
  targetNamespace: udl
  values:
    workload:
      kind: Deployment
      nameOverride: "test-two"
      deploymentStrategy:
        type: Recreate

    app:
      name: test-two
      image:
        repository: ghcr.io/udl-tf/tf2-image
        tag: latest
        pullPolicy: IfNotPresent
      ports:
        - name: game-udp
          containerPort: 27041
          protocol: UDP
        - name: sourcetv-udp
          containerPort: 27146
          protocol: UDP
        - name: client-udp
          containerPort: 37031
          protocol: UDP
        - name: steam-udp
          containerPort: 26926
          protocol: UDP
      env:
        - name: SRCDS_PORT
          value: "27041"
        - name: SRCDS_TV_PORT
          value: "27146"
        - name: SRCDS_CLIENT_PORT
          value: "37031"
        - name: SRCDS_STEAM_PORT
          value: "26926"
        - name: SRCDS_MAXPLAYERS
          value: "32"
        - name: SRCDS_RCONPW
          valueFrom:
            secretKeyRef:
              name: rcon-password
              key: RCON_PASSWORD
        - name: SRCDS_STARTMAP
          value: tfdb_octagon_udl_v4
        - name: SRCDS_STATIC_HOSTNAME
          value: "UDL.TF | EU | Test Server #2"
        - name: SRCDS_TOKEN
          valueFrom:
            secretKeyRef:
              name: game-server-accounts
              key: UDL_TEST_TWO
        - name: SRCDS_TICKRATE
          value: "128"
      command: []
      args: []
      stdin: true
      tty: true

    paths:
      hostSource: /mnt/test-two
      hostPathType: Directory
      containerTarget: /tf

    decompressor:
      enabled: false

    merger:
      watcher:
        enabled: true
        watchParentDepth: 1
        pollIntervalSeconds: 10

    writablePaths:
      - tf/logs
      - tf/demos
      - tf/addons/sourcemod/data
      - tf/addons/sourcemod/logs

    copyTemplates:
      - targetPath: /addons/sourcemod/configs/sourcebans
        sourceMount: /mnt/base
        sourcePath: tf/addons/sourcemod/configs/sourcebans
        cleanTarget: true
        targetMode: writable
        onlyOnInit: true

    permissionsInit:
      applyDuringMerge: true
      applyPaths:
        - /tf
      user: 1000
      group: 1000
      chmod: "775"

    hostNetwork: true
    dnsPolicy: ""
    serviceAccountName: ""

    service:
      enabled: false

    podLabels:
      update: test-two
      restart: udl-servers
