apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: game-server-accounts
    namespace: udl
stringData:
    UDL_NORMAL_ONE: ENC[AES256_GCM,data:l3kjMo6LW2kCVFFEsxgAjBdL5XXPPK633Ghc/ur5/ak=,iv:yqVHfdbEov1IR9MPyi+ViILE/C0JJjX5Yv/FcO+5jac=,tag:nu0ncy65EUSVwhfUe1aAAQ==,type:str]
    UDL_ADVANCED_ONE: ENC[AES256_GCM,data:3M5IA+0qY8kz8u7ce8E/IRqonUQFd+z4MfAwXFuMMHg=,iv:gvyLWv7jXlXX8K3z/D+4ajqhShZt4y8EkuCTxthgSQc=,tag:p28vFwcZ1uJ51KT4bGX6+A==,type:str]
    UDL_ADVANCED_TWO: ENC[AES256_GCM,data:9pi/SWTmsuusn/BEOQ9KJeqF1yJSVwDgCSj4snbp0ps=,iv:gmB90OhBYSkNWQ8SGeoUburdbfwimhhWiW7BCQpgP8E=,tag:Oae5/+Zgj6mFHHleJf1WEg==,type:str]
    UDL_TEST_ONE: ENC[AES256_GCM,data:3ay8E3CEGByatLA2GvCqtZnxc8DnjK8mJfTTO19tjJI=,iv:sq84VkGMwkWp8yjYBqdg0IzdbQoBH1jlc6BTMXZwd78=,tag:6zgN8GF/anwk74zASPwupQ==,type:str]
    UDL_TEST_TWO: ENC[AES256_GCM,data:x4m1tU9BJCQgTMX6PfoLccCQyDq+g3+XHU07qtwcm0E=,iv:B2EavA4kxZ9WShIEqnY9goMp/ZnWdttsXmct5dFyWpg=,tag:JEzYhh+rN96szoGWnb1RwA==,type:str]
    UDL_TEST_THREE: ENC[AES256_GCM,data:K6bn9K+C0mqQoXcUkdt2BALUD+hWKt95J/wYVqmRs8c=,iv:ly9IBrmLt9XC+mhx6W+Kv5J+rAjkU5+2XoBkhNsRaFI=,tag:hvKol9G/48tZYFsVjw/fjQ==,type:str]
    TONY_76561198123577596: ENC[AES256_GCM,data:vnexGzp8nr5ljfrW4EZRRfIze9/4nHPEHu3OpOiYGmQ=,iv:r365o0ejAJb8eL3bJ/vZJjMHnX3ySljp/AuqY+iYugI=,tag:RVx5otb31/s5lR2u7GVH1w==,type:str]
    POPPAS_76561198777082182: ENC[AES256_GCM,data:Di2hzyOXwRydOHwfRRCkc5fkQD1lsY5lF+6tir6j7rw=,iv:A1ohYA9ZEnHD51F7cULzpe+/BO8k+1kUDKc6Oz5aW/g=,tag:H+xkFlE0eTF2RnnI8qThjg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcUFwOVQ5SWxjRTFYanRt
            cmMzT2ZNMWhxMHVFeCtWaWlZTWlPRWV4T1NRCkdlZWFCSkVVVG5sbE5hMUlEVEVv
            djNuUDYvejROYXd0SE9zUGwvTVBLK28KLS0tIDJFUEphMmQxQkVlRExhcDFXS1dU
            Vjl6K3AwWTczaVZCMHVpY25uZVY0L00K6gaoN1z/Hajuuf3fXnl5pYyPraMTmTLm
            37SYUXLUnq50GY4WeXDSKLLDFKWT5UrpQDCtOb9kHPHJQqrTkf8l8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T03:21:37Z"
    mac: ENC[AES256_GCM,data:MMIIoZODyJxwb5l+r+vWy+d5SfgC/WhSk1AsH4G1FsI1BErSshtknA6sUpgz4SuT+rhXrs/Wu4lVdZ06nvl2aPQOSHEXTPXrnPzuFaW0D6e5S8LUBNhgzoMWWZSohVaUyogvnCj0fPvDX7uKyjrB308yAhRvYJi9RnfDWCi6A7s=,iv:xsBTnWjgFUING37/VWRaIsXsRucI91xh48GjKmbLCsc=,tag:8PRzlZWB4FJWqFr9YZaT+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
