apiVersion: v1
kind: Secret
metadata:
    name: citadel-secrets
    namespace: citadel
type: Opaque
stringData:
    master.key: ENC[AES256_GCM,data:eg90SSKcDviRJpRbai4fbdIfwg28AoKZ6TR7lPYBwow=,iv:sZo938VqbS42ny+0lDyY80b2sO32SOJhoz5RCjJKXQU=,tag:zP5PJ5y576MOzzCT5jhrxA==,type:str]
    credentials.yml.enc: ENC[AES256_GCM,data:USjWpSHvEI6ZUAcC6FFVBBZQ+zgoMGWD+IxZD6YI5IQJKhEwbWYUucdyUHCT31EAsPzYLq2c9GNE5lPrUpktLQGTkgYOSyk4xwHHVHDL5d619YexINP9FZVN7obVMESvRaHG3s4bR1TVxu8S5aduQYHHvf2IpvsbrgPOzZOHqet4FWIakip3X9ThvYyGB+IPzm/VyhoGkEVAOCzSaFO9wvMs/peeH7qVysRL/UbZUf4zSjKxoGhBFCV3fg80FHcL1LAlWFdgqxgp2tuPsAJcHOa0vvMyEOxLXr4rnKTFCNiJ/kabwPxZSjRGfv+5qRltBsjRnxINjIJ1QHemV9XrA4rNy1VEjL1Eq213pmn4M9WqoghyIEPNFCLaQq669pY5ex04XYZWOLRBN0R/nmBbrsMnikrKHA0KE/ii+HucMCh1rx23soF50NTf4sSP/vBdveMBY9yJjfJ781mZTK6ksoNYhXHmS0+Dsfe9BDKG9+HWqIbig+hwDyE4e0jqGhIOnuGtX19nMB44PyxBLEUW+lVo+hhcG6w6SvdYKdn4RsTKWYf1rtxG0kmybOmqu/AX1yGCMaYuenxfMpyD0HqXESmLx5UZbFYHec/sKn3jD9yODVO6lf3HXsAWy89OwgJjawKkg4Q9fqrn4bNbVUt1wWCAk1YnyAU9GG1Vte1qLt1r1lLZAhoSzH3a1J6kye8t1Hjk/HdPKOOlzSQaQ+JhFl7WbfibNUo9Ru9XVjpvevgr5qZxokMsN3hcJqOAR7VCdaRBSiN+Z0Y9V6zRUveVl0V3JlZR+hIUKJ+GDnJUSrNZl1Y+MkMvcjaD0ofcxPn4aMniYHuq2W3oKVpevh4MPGduRyjGwJ7c,iv:agUO52DuIZWI0O7ltyzH9FtZRGBg+7toVeCr9r3S+e4=,tag:M1pmH5SvjcsMPB51/2d5Rg==,type:str]
    SERVER_RESTART_SECRET: ENC[AES256_GCM,data:xOHTEMnMjfuU75DHRP6H8P1aDPU=,iv:uuM1VGtjfEIU1e1f91h8znmnF06mASXo+QcqBZwDKiA=,tag:5/KCYXYf5EUgmO2mxS9NBw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdEdTUFIrSHh1ZnZpNFY0
            TVZZUFNMUFdLWThITmhhNHc0YUM1UTk5c2g4CkRFQiswTWRUQUpaYW1oWDdWbVcw
            QjdzWEhWeXVOUTg0MGZnV1F2WXZ4UUkKLS0tIHNpTFZjMGs4WmlQc3hvQWdYS1pK
            Wmx4dkYrY1RFQnFZdzlEZTd2QlQ0Zm8KYv/tKJ8dwmHo5kpPrrFeylCqYm0A83+N
            g6fLN68Wi87wuNvUehmTqP3zCh/WPaGNwo5CA76WhdaR0Ivo03OJLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:35:24Z"
    mac: ENC[AES256_GCM,data:MtyRmX0hInt9kHpSU6xMx10lqV4MEL4DQK4e9JzVf4uw8Gig90i+7vNmg1k/nIJwUCZSPXXMOfccqw7+LcZczvh4QNQDP2N/GWWo2OVo9PnrkpdLPNfhZI9GPoWhwz3rdS+J9JwFkDgqfMp/tkgnTpQY+Wj5WfBnK9NdD44s1i0=,iv:Eenz5iFqWbDfLOQQFEQEJqxhc81cmgGZhIjjT5erAwg=,tag:F+/WHzTbIn+cmFtBRuv5xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
