apiVersion: v1
kind: Secret
metadata:
    name: citadel-secrets
    namespace: citadel
type: Opaque
stringData:
    master.key: ENC[AES256_GCM,data:cbeny2ipwMaWY3oQ1wxKFiZ83QfqM2SAt/N3HI3epDA=,iv:QCDOsi/r3pe5TN4fQwjgyPuF7ue4xzwp8eJ9GCYw2GQ=,tag:voyMqhuxry4AwwKIGYYUVQ==,type:str]
    credentials.yml.enc: ENC[AES256_GCM,data:kQvngbTpxmV39rzt1820HHrTsTTFUDLDnt54qVG/zewiEf/CkygaW/3cOkhkaQip9+6SIFsG26olOqOFJeAX12VjS13RUK87nrPz6iI/DNsWSEXdUCb+xF/eoqQzJIaUbtFVv47kgumegqcfRyOXvJjdrpLQbRaLMIJ9KubyWyWI8W7an40TBxq7dg0aE8RzrXmd4UiLAHEb6dKcfodlO3TElAIk3FeGiZg1uorYFNUyjYaJRVvtZFb2YR0WLCb8wiVpyJ2BEzX2R/uKaPrOHdd88JbCG+ULhGIcUVtsZNDHN1n6uxndA0jr+tb8SynM3llpW/gxVKfmqwStQX/n/alfzmNdEGq2+ruGaANkwTa78HIZi8gm0BZjyyq44IFH25RY3bsbyhTfKKtoE6lm+B/ZXjpo6cev5VrxcUZjeTxsXBSeg86QiGIgPxkBUgs62DJ08XKSrfnLBA5SgHZoruMZlAna4QY/ieDvNAcYYTlJP0fBhXjmOmLk9LMO+o/qqBhKN5DUaSecjO5vR4aA6sTiRiXwLkpTbXE/+n0BuDM7SF+QkY+3rtNMaGfbp+wC7uleAhlcMkOypOeGueCl3vvu5ioPOOTHBs8R1r7YmeAVH+OXSB7E9c2PmV3OG4qlj1zD4V3+iFG+ImvDkfBUnlOE48utaFb5VLkj8s9tDcOOE+j7XLHFKBe7+cURj6i3GduGxXGgXgT3CHzDD6Vxq3lZUZ9vmIJtkfxA+MBlzc5KapG51bhT9O9SfE/WDTgBqj+ZBs697Rllq/Z6Eb8JcXSqwAkHzlI58yRD2EuLCHDNPQ3ppieosUqpzeBl63lpTcSPqt4gpcgLui8W2nqvfviuswHL8OuU,iv:od3JQXaNlKHHo5iiIlqpip6KE1X0rGHtGddTHSXNuTU=,tag:zAsPafwaQga2R3cfQQ87kg==,type:str]
    SERVER_RESTART_SECRET: ENC[AES256_GCM,data:HMj/Thxch0oIdMyLgMSeVwIcKs0=,iv:s3tYwCt5waw3RzmkA7wu22QkGr9FImXPwPhrrp4JWbU=,tag:f1737xtIF+9uXjEMHGgTKA==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWk9IM0kvUEYxUCtXZ2g2
            Tk82aHBZR0ZJSWNJRERDSE9xZlZpakE2elQ0Ck8va08rUFRZZXdBalhQZGxVb1Zq
            Y0FTa0JEd0Fkd2EwRWI4czRjeHN5RmMKLS0tIE8rdldXdTRBME54TlFPeEJFR3ht
            THlEY25OaHpPdXRmQ0cxM3NhZ1JlVDAKBGPmg8Kb/y6t9mmJAuhB3a3Lf61G1eDd
            3XmLNagwqH/F5fGUw+ymCqNP+MP1g8/UaOUr+59hmKdJHL1ewQQMVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T21:09:17Z"
    mac: ENC[AES256_GCM,data:sbzOjbLi49CzqPIfWZ49g27FXIAc3JPVEvgSbdq9pnj1PRCP6Dk50BjCZRs9QpFjnWWtw92O5CWTC4zsPkEA3NHsdG4z9kVTc4hZRNIRL2tyUvayOF63AZ7kbZizQ22/XBCFetH/2s4KhMBgeEeu960U3SjrwWjH8KGwGkVSIV8=,iv:4Xozb/UPpNx2CCEghSEJK/G29YRE+/O5pOZPXqbrOR8=,tag:paUOd3Vcai9Pm0Ox9B8+wA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
