apiVersion: v1
kind: Secret
metadata:
    name: citadel-secrets
    namespace: citadel
type: Opaque
stringData:
    master.key: ENC[AES256_GCM,data:4iv8KBKYFt57e60lBJLnd7jtNOPgu/3haLvCRpMCesw=,iv:QORSpYkT1xplc51+xwiBvwThwmXQXKaBuVWSR2GNsUI=,tag:z4AWoUqjYCwHgdQqZbY+fQ==,type:str]
    credentials.yml.enc: ENC[AES256_GCM,data:bIBI/x6UCI8kqiqOeGzc/i06Knsu8WNvoIm5o7kaDQWfXVvs6y/TDhbzuNI13BiC3E47JxRPhzSul1JD/u3/4tKheMW5X1fTm/xeSfjt2dn5aGVbEpjEHwniUPdsB1GisbjrTiTtIAbmwiTTZaM4OW3EC4by47im15IY/IUrh3z2pyMCegg8ZR1C/kcvGUNq4EBfFOMNOBC16nGCQkLfxR6jyz7295L71Bvh6po69gBkeCwi4LhVR1ouMkpGG5XTtLeXONxdazQk3mwT3MPEmnSKCqxKKV1uih4CYKyL2tKTAFydd63i4pzm9tIBQDZiGu3fskEmZdRPFRrUL3cJIZZFHXnXUxOwrvFnKIkq9bOKYq75oq0d7/cNsY9EPqcnfmpqDeDRwC9U03nnj6KnjpVIDuVvWwQ+MFDWo3D4y2OMhwhfFLEwI11ixMtvo+gAFLERudAMjfjs4LsprfQe7KKswDeJZHpVMd4tj2YnDO3Gn+tBKjKo/D9sS5L883hbSMkURklIdSqLB0r0CxuzOrdwmxibSNrsyCusNWUW1Q1Dy8goVWszCFnTdcA/huuteTl4762pKwdwuCkJrWnN7yXW6xfajvtk+DvN/l0vOHJpe8uF1iA/LpHhy5hjzNA9AWoNBbPJOCqPGdLuCNJvZmBvWkL1bAC0hmz+83K5nnXg/qa3kSvoGO/xPNs7qgj0zpW2CQVbFDKLZjRLF/wD7x/59QDM6AT42PiyPJE/ADspBfYB/6469N7plpN6yCXMPJuljdkL+U/Xq2TK8AOiMgWb5EOuDNypgNijlPITYzhd+/rDlur4LJ8p1aRoyIdq2RXMTgQsiuSn4xFEMS7XvGw+B5qlsJtf,iv:Noj65Xw3JVp66qDcp5BUFezHYRKbpVHTVI5qnN4+ytE=,tag:IxfN2WjUQ+LNFVAiV/xPPQ==,type:str]
    SERVER_RESTART_SECRET: ENC[AES256_GCM,data:iaBHaBETNTLE+BGou3OA/Oud2qM=,iv:tBsLyeA8PCxanizZa6L1JOB3SW74cA8S+aucQmAL3AY=,tag:9c8KAdjRfTfbqIxxlEOmtw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VXEvOGI3YWpzb00vUXNM
            TUpKYW9ZMjZjZjhNR1VUeGFVM1BmTkdSYXhBCjdrVmNCNWZ5MEhQWkFWbVN0MnJ4
            UlpwTW1TVGRBbVczdCtLaEwrb1dkSEkKLS0tIDYwQW4vd0ZmbitUakcwdC92dGlm
            TUZNZFV5UHlmc21jc1B4bmQzblp2R2MKS8gv2mvmhUzKxFihrPzrdJ7KY6tg0zJN
            AGtcbGyS8ScpZ2+Vdfax8Ts6l9gg1OB0u8z7TTN2XGW1d8+2YLvOXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:06:37Z"
    mac: ENC[AES256_GCM,data:A148jDoVMIalJA7bNPFL+DfPlaPHcOdL49vmY0KHeMf1bNblT/mytbt3ghIu2JhcsmtaCkOT0mNpFGQ7L39r5VPqeBkUUletUnvH3+zB81MRQUjzDL3rc5JYVuswxB1EZd7H309yFsDGRDHkbsv4qNLKNmkWepN2VyCcYmBWWiM=,iv:7vs0YH7ApJencORYx9KmHgEdnXU8a6LKuydtN0IM8cs=,tag:vABG/HJcRRYMwNb0qcxqKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
