---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: citadel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC+++JoUsaoaWDVOA30OpLW8baM0muA42XnpjJGcDb/8I2Y51L5gnDa9Xf2+rh+29Y0pr6yBWSxEMoBQOzZJv4njsneTrxa8BJCbJvyVlMe+wBZAMCF9aGVKRZZtirCCPYeNWJKAJWaTaLQmAX0DZRD8XQqlvsl1zU4a55UJ3lczW99qdSOge2ULwaATaQUrAd3e6l9mvZVp84PTGnPsCMnJfKsiQ8ArY2ECFBR0YTkmpSnZ0KCbTmwWEgX9U3KegOZWTnCiwx/8oQtrpOuWlkJgMwlRRgGM49lia4T49PCBk2UjjtQJPNf2QdZLGul7fzv6TWEI0jlEaHIs8pq5npcXChmhyHedzNSBxkOFeNxHEVf8RjDTvmGCd7WuX6+MJkZ4txNFRYcVthyoZIqcqVVe6R1wg8qRtnigS4RfC3hN6xruOebvcCXIHaRnSZgvadtUuPvntJ88kjI+m8b8o4ZLdmxJgm+y2mMoMueTcxTVL+UcxcllJrBa1958JDV6uUFxAc+zDzVJDDmx5ogYaqHJk6ByBHWxgcs0TrAJgz/FfMTMVuMI5SzJEu6P6LRy3ASfjDoP/Wz1LzknhDXSQ+bBdeirmX81WUCPsOu+q6RPuswGtsEJG2QhWJxQQUVyEws8kCqcAcEIYGrmw/icUOjXmIcv3bSz5MOqMhTsDMye0chrlqAmmp1PLutr8ueJIHEasoHD1A=
    POSTGRES_USER: AgCtPF2cOp2P+HzIhtNc907t/Us6wSGdmHbtUmuCzmSG2wRx9oQZE5oQ6FzGe8yKmtyUrDQv+wy3aTgt1j0kgo4fBypjl7DUG4GGfBGS3cxFhMe32mF/Px8vTz8ny2VW8ZfRXYMBedByoY0ni+j1uvcBpWYYwVFkcalZoSYSAzTBbMaVP0vGAJpPTzPKTJzWdk8YlI49xacLCBrxzVmJTH/DIRNRUAkPzG2o5zTHU4xwniSsBQmMThnU/IU8YrRhUfMKki7kuVckLqddscjfkRMgRaol0wZYMrbkmVvENXIvJLUWUmwbydVey8AVfi4ma6Un194HgBi7SCodFF/xjRayGR3wBaDU/Vl4rBaAWcrZmYyKUpQAOYZAi2jRebttaN/r1r45BxMuzWqONhDh52qC3guMT8WlOU79I2PDIo5mKCqHOdq10JKXp1U+B9lVjjCy9hYl5MN82MNuKULNIFzVOksSBT7fbSSm7j33HEPmC5Bbuem8S3NmzQPIioandu0W/ZTk+yfeeMLBm8Z7py40ZXPGhV5wgXcscNarV30m/0FkYN4m/9VgzqCgRfPkodUy+hvT9IWRMaKEVfgaMzb4quw81SUe3l78eyeKQiTK26BWYjt6IHH1gIAMzBXM68EoFJVAeF+PwoZX0rxILOCYFupKQ25ozdCA2kCto96wJ26zV4HS/WRVO7qGjwWfbQ0pgPbifKrrBQ==
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replicate-to: udl
      creationTimestamp: null
      name: postgres-creds
      namespace: citadel
    type: Opaque
