---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: citadel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBEh60+ChUwd/GBthu0F2MTB5L3wLtb+7O85cLYdnZX5Gn1wbNRMGkD/3Z5lfDFXqPoMzOYf8nc0BFRi8NYeBLCDcFo8k3G/pnKNz7zeVF9rDHfwu0CmHaWusFjyGEfDoFisAXXZ0GURS3VNUQCtjDa9I6WayS7Ic0K27wZlzaJhocN9vsQS7V05pBwJf1oY5GVrCIhmBDT5TQy+QqUpwF2nW90lwVlpQEyL1eRZbEvNkwww5DeXRmXuI1f2XrRGk3EED9B+pt5w/edo3H/8zTyKz5raj4rf4BO+6rq5M0aNJeBwzrIkWuiqTMWEHZbEvzaQ4Oy21b+nI5CKilJCrjdypfJV/mp8ZIeNcI+EnkdVnQPq1lSx/8A879gArZmdRKQ7D8zAnvb50SySZ8wdqnlRut5w7Rwx5YSRSrr1MM+ZIFlAA8jVmVL8lc4mMFaH/q6Yat62EDXtj0fsm7EGoMUJDg/yzWt6IZuyx3LubECF/iCwhcbk35yrrNfVUbecgWawKIzzSlDDRa1buJWgGXNsbSsTwLhH0dt6iZ093Oc4Wxp8b3Jpa7HY5IeYFU7/m4Wo+o+f9s+XYKSkBApURUI02hE6twJQ09Wp+oLRhXb/PI5C0NrSCvIEoa9ZYFzShB8A5unGfHA6nyKfvgeNWOtltAdY9fEW00PfVW81oGaKvOkA8/2YLqKrwQZcvikN1y4oqKhByU=
    POSTGRES_USER: AgBPAwkt0+9P9S8uq/hT8kvPRR7OKtOpaQAhxI1B12XdAS3qmGOh07NQfFdL5b0DHOjPJ+wdbRpKOZN+Z61UxBJGEGJQEMhxjXLSoTSgYe96mOsEkqv+eY6cfLrkksVoHh5cE17bYFYKiKlp8bjlGI5d1laxJjllNKgVECFll2QUy3zR+a4dUaXCFT+WA+/8q1FsHsAqQmsbH8zY0BOZbaw+u0JklYe2il+U1jf8Ve6zzUuB0xTojDxGuCiUbPztpnzdY5ghwzfyFcHquXiDzp6g3fOjSHAQGBHweRdQafGsyhjrHmBLy1TEY+TmYD9jltDG0hJ6gzMaqaYtrK4w31lU8gYd6eQvAwPN3jGBNxKWl3OauYvtadKohwxKoxg2pyiwTvqRxq6SiQarY6abjX7Sa2lDRA2D+ZPQVGi0ZPpIGVG0MjQ13nC0NzKtnbEUA+DLet5Ugbnts4RbqdCSjk7kF7PnNifyCtS/hP8kbEb8rtngL3pbpAWdopydSJR9XbcCnmn2IMM5egL4BiEHgSQEr3j2IOT1KOEaslrsMV7CsClzJujieYk65Ns2NNbf4yA1QGo1sCIpk6E4hUALbAw0zwzzqRtapuGSV7vb2Wq7fDnZkkvxK3WJUO6osUZPgD6Kvqcvqpbbti7CvQF0cymXD5wpJB3rZ4FTuxZyyECcm+MKuzc4YSf2r8E/1k2o0qsIoMdp9Pt/8g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: postgres-creds
      namespace: citadel
    type: Opaque
