apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        replicator.v1.mittwald.de/replicate-to: udl
    name: postgres-creds
    namespace: citadel
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:L0vNO1zE,iv:TdpjBOzTu4coJ+/bqP6AJ8VlW9B8xdsgbSNQy3407zc=,tag:P8h8pHuVrNkWNOoSrpGb3A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:vAELA+ZyXl8=,iv:wZjA3S+Id6pE61OriAahEvcmUtROuvoxUozqNODkyyk=,tag:CIzhNvchPym92hnjIROFjg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcUFXNENuQU93dXRQREFU
            QmptVzkrU2I5dGtVSjl4cDdTSUd6UHZlMmdRCmlEaUM5UTJuT3VJcUg3OWpaZEhU
            VEliTGhLREJTaVhwOGxQUzlGVVlybGsKLS0tIHRsckxnZXhML1JmMjNCU0cvZG1Y
            SHB4NnRVY2lYVjBGZ09nMGNCZ3Y1eGMKR2ge+CLtBlHxSs5v12Ai4yHf3Vm9KH/2
            sIQXlHtp56o6ITG8/tLPcq6WhPPwIBcapgM2vTjpBj57J7oUkXmgeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:42:15Z"
    mac: ENC[AES256_GCM,data:wt9as6l29MS5P7e3U3q7eNyi+kWptETFcgwlWWfAo4i4NCaEj/3jHPKqDKzCTtDwlY3Zvdx2RdtPb6S66XQLVQAHogpj6XGsDoukuEnG69EtTEugz85DacpmMDBKtKkawzi/B6C5pWR2bwAgvFHmkU5WDp1p+pMxA/NzTFL4C9w=,iv:qCOKDGG3VjvP0q0UhlH8av1TNDaP7WmU7Pr2KmAob9c=,tag:pqvEeWcEbIZy4/qTjICt2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
