apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        replicator.v1.mittwald.de/replicate-to: udl
    name: postgres-creds
    namespace: citadel
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Hb5/3Wmm,iv:3PG5SnC2QULO6lL9BMCt6zQZYIqsK2+9uToP190Spn4=,tag:4P9Erjav3esKRaSZw6xOXQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hfWG1yxwDCQ=,iv:U179xaTt/x8ybXLZv46Z2Gsk8Ywnme6PS5Q+OkNc9Lc=,tag:ksO3qbzvMMMPxpNKKaNhOg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NHgyT1VaRGRXaVRWOVRr
            dDRiQ0tqWkJrY3JLUXJtVEVaZW5DS3JSclNJCkwyL1lnQXVXZEtmT2FGYythN2Ju
            a0doVjhhRW5YYVlYVE5jSFNaYkgvTFkKLS0tIDFtSCtxUEZYRENscWlmR2U3a3hU
            STdMdG5NVm1icFdTUUZrcCtuOXhvbVkKneD7457PWWxccmGBdbgr3VvSZApnZZWu
            BmgfjR0hta9btv5gDkrJRkvlhZlj5N0WkkgePkD6rd4kOl8F4jPNlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:04:53Z"
    mac: ENC[AES256_GCM,data:EaRrBaNJCmBgYvrY5bA0V/JRX+9X/EJstMLN6SrMnluRFyM3VTucus+jgU+92Gx2If3kjuHDzM9WIW200DYynDKh5My4k7IKhnS7MHhAv9F2lyI3Dkz3mZ297zZHEWLw2I0+6ZdZEuaSOAKQUBjXrFfsGmYqzsaCzNalywZrk3k=,iv:hEoni3N7t6cIL8U+ulMYiw71gKl+AMYpraFnDzAOuso=,tag:uzIA0Z/I6NfUpfDWFFkGyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
