---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: citadel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBdNSaVDUwrHSxj/ICCI1oya0YSQJrQUsBynPSm5st0HUgOoT0NA/1KqclfUhzM0YJ+n1IuBeJYDxKmRD+AAGhS5hF4Vh5o2lujuDA+rhDF4hC/KGvZe5HH+JBDplnncDHHrmu+nok7666wwhoOaQPd/gfzJw1AnUH4XEpVkxw8DLxMWAcMu3DVQ2Fm6beUEVfGWqYKop8Qtgc5VqjSUJ+xJCn5qryaGkwynlLPt91fmyKMit68+rqz218lZLEJiCWa/s2+q4d9JnV5xcRkAdd00D/lJ05uOYJRGw2H1/54Yl8vY8ZpxMXfGJ1dtxg9QhrOeaVsk93AnqgPLeRKS8F0aV+aDqzguhyBDft1C9v0ZR7F0XHx2oXVAX2tqNjQ66rJYFQ1WQUckPOasg3kJc3/1MjDXdhNr9cDR8FkslXXh/8JGqV0EQ9fhgKV+K6S1WMBZ9DsbXVn/WkUwUWJt8OoBdfIhKE5EN2QxGv3QNVAcn1BxBNDxlvZl/D0/74GrD6BzHphiDzn4CtoG+jdL7YWN38qMdCVgl3bXtFyUus6Y1F0cV4cJjSEnO00HtfIIsW7RaAc7Imr6m4gTQWHvl9pqm13eMG6VXav5zqFyeNUJpEShElnmG9rq2tljK5NHUUqVNyy08qq5gn8hKPRKdTU9lLpuCND+yRaRxMV61f7EYzK7W2sME+wPNRPfevCfGLoxFrU9lk=
    POSTGRES_USER: AgBXDPX0+m4j9RgEwyigYDNxlGjd4HAS6ulrDRyXoKB7O2NoQ+utOfp+/TCGltwocyAPin5PfKIwSOdywJPDyMjCV1rEKib6LO4SqxtNDGbGATv4FrLgvfhYCw7ScNv2LR9PgkASrK2N91CCY9sjT9XWsm5XvrGHOjHaJziOrwKIxroVGvYsjDhQ/TDQ5A6H6T16beuxgilUSxtSlQ+PnfZWII1NUnyx/c5+ee3+p9yMcbIz8ZaHdjGoewF8cQxReDlFws5N44fYxu5eVscDOgAwIuiIebEHfhQj9N399t5cALeTB8DmAUR+Wn/4iIccq2bH1e0kQGLixvF9JYWWrQRk2Wn0Rge7WGurU3Q5Mz+8oLD5VyS+PSwvLIk3aTnANepunD/43LpxH01swwE7p5ufEmVjf4+12U26oIOM/HEjTYcVmt6t61yAe9w8nulZp6gw9FH1caJmJdBUWwbn3kYEYotvjTZE+dAsil1n5bKY2Z39ECIbrvc9qRaJHl4oDS2pFaXWo1u+AeY7oiKDFxUKU9lwmrr5fhp2QY8IRJwhoP+jX3pqUG1srIoGCPO5su6/ZKkh2B7BrFi6UIIGITg5DawWcN+xxEqtnFIXgorwo6afL9mK7SXSrBYGKHF1e/7a/wGTWt3OFBO1XxZ6XPkA40ENPTTs/4uEO7htLKEv5JeM3W3m+IYuF6R4KGPSLdj5zFfJdxrqNQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: postgres-creds
      namespace: citadel
    type: Opaque
