---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: citadel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAi2IL+StTD6tNuhmjyW0fvgD9KTBrgS/AEPCbeFstzoMOEasWZBPNDfF1e5dFmWL3XTka3CHldUAfG5+3laB8vC/4Ov1ISieQdaswgM7yyaWY4Tr9B1UogzQKB4AhEjJVDL9lNECpMrzPTWiRDkWhI142DZpqYy2c+zgt4lu/xfEvfcnflINFvPD7vNYrO4PV/57Mcpwb5FP1wLrkZ1YYQTisfyxbmca3vjjtJuzYtRRoG9O8w0CN3kZE+iM3lmR95iXdR73/+h+7AQptuHY0Ys9PE5tkfGOdcJZ+BPXaqeA9H7JH+9RIKvZgdfULtTpEa/WANvv05gaGA+fGGZgsX7efLGuvv+iq3qIqWmaNm244wJ7/SAXU14ADdO3qPe/sDur/UT+4t/N4cXV2apn12hLipAtiweH4jlGC30fkTZPuC2c7XxFmLLSXw+vCeVazdSmPRiLeyYLlqEEqzrZlCOfYsDaKYY545Svd4RGET4/rn0xdMVAw7LgQo05oib01vk6FBICmZ/TKnGpDlPPm884ITwQ0x3NpJ4gobfYFagnLcayBNUpj2nVDtndxlcrEkLVnfBySTMDrvDCa0NZQGfzuhJECT2oKihe4kPgk9F4sOhyv+M37ORp6YTE4EAQ3arqxnq+zrLs+GRox2b0p62H5Rp991npDEbJNYaMDq0fzPIIbQny4JwYlRZKvwVSokmx57olo=
    POSTGRES_USER: AgBA+3+YLgHumHsdXg0DaIoLYo8GiFq5+82VrdUSBGVTKm+HZugv1qn6HgotNHMaDs0ZSkVe7LTLSHVQnKZCjwtTqSpoiyh+2o/JG1ClIZUpVDiZ0g01Cg6FPGaPRcEu2N8h1cRyIphwJugGo3kjj/qQtMGtnUryvZ3bY8mG1paZsmDrFL7l3svFfIU+WE5NkB/kbu7vgRIEexjDNvYkA4+NB7E2vx51LX1O2jqRAJ+mC9zPGQT/9nC8DZ7QEWcqKOP/3lxuNElLjJIY7OK3dO5rbmRCY7N5575ZI9Qv9LsPzPGmnoo2lHH5kNs9dNnq6suh/HDYfnbeyCmmxQPazGwR/tUJsy2N3fDC7lDsuhCtF63ksyZqLx8+puhmPDrxl49VBTAauBzknl4kOgmi+UbJVu8HnK6FTCXJtEiu8OjUw3a1hcRMbKRMX4hgmeauk13cVBQgcC1VZtUysFoKivIhgS1WpGiV8X6QIKnx7jx8qxvdWNQEz9WDGe6seZ2wgkV5EU4l+qPzxsBCtbQps91rrYvyMVeNOHhHFzuOnXGfrjADmgUjzDXbgyCHJw62ztxvl3z5pVYpM3gcN9zREbSpX9aF/i8neQbXrAiCeOX3y3vWSB7WVi6gAy8XWCzfWyf8ZWeqxlWcHjTYa82HLGh/lx8vAt1az+wLJKF3omEApTW355U1onr9qwVGr19rHKooxpp5HOAgOw==
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replicate-to: udl
      creationTimestamp: null
      name: postgres-creds
      namespace: citadel
    type: Opaque
