---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: citadel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBRZ6+KRw9Tzt97SyHPQAwsiP4g+/42LSmdkzU5uXK2/FI85nCL3+vgx5M+aJk671AuyeOZ61VGkegZPYDQENpCqn2qgO+ezM8H5WMUCpuq79I5OJFypVVS2gd2f/OQKxCiW7Z86DXJVBvCbJQ8FKCvobSfqihY4M9I5wcJAzQCDCiq02UdC9zVObnmEwVcdY2dV+s0QXple7HsgDaR/XLmsESPt1GeJHkRMAwQ0PSgrfjwoC3k9tV6aX7JwMN5LdhZErpSZ7Sv3NM9PDVCKw1eiUUmwkBVaMw70n8OkT0UiwlYbYoAehhXltJpzO5DFrnaD59Vk1u1QoSPObvRMpornwfAEBIDt8p9wAxW3Me++7GrQuBw1hthI4Ff6gayAb+/NmbCaWAm95C0clL1w3sDLQDFTJKna2pY5RQB1gFs7MVBu+CixAlQmFrYkwbMaV5NsMkzy6/n0/75T0rxB5onnNObc2c3ziTbi+UDOLEoHiVlFz7Ob2Z52ErQdlqR0eieZ1Ntst9XARtf4YjvEleiPbdqLv0a6XAY0RCdN64Ju4pIpkwrxYWTopUvzcqtgBG7H+Z33/ebBtubjnejHp82U+P2NmPGwbviQVqUv8USiUBzMFGVl0vOPQEYDvXdKQ6lUvAB4VXMkCH5MkDj+mJgTblyxiiddeLynofBdPzx3UEmW2nRxak1sSMsar3WKza84MxnPzI=
    POSTGRES_USER: AgAZDxS+GjNGsncBHmD7LsN+kd2daxw8FUUZMHhcdqPKBxKKB36huEZuEYq4pnSAOO4MXAUmawUMBsjUuI1ILpiy3Ityx39nwcmVMXVdHMSKIapQLei/0PHDAZQBxxUBkCz2zKBmnJC+pGfu4Zj6suouaN9tf30Lic8HIVfWGkSa0y0KiVg8boZdy3XySOf4W5Bv90l0A2RwWpoRIGiIFNSgO7ToMvStXGm7nVlq7fLJMWA3hFcTuZOvr7ttu9ku/fbrlxfYs/bkf7I2PcZITUgQxKM4BhWFpPNcqxRs4xrMrizc+r8Po3nMUl99alYwcRcr3YwrjlUfqGbNJ0i2wopj+DiRgo0Q16lR556COP8lP78qOtXGmnMUm8vG1C8Qdu8lkQMc6z9FSN50xaHDOnEeJUttqfdu8lMq8OWQfNBoPKlS1vm76mmYlts6MJrRfz8AhwK5WEcWuWbEROaPoFNctwE8cemeLEfnOWen75wYXEL8XPOJqlhuStFEWbjbA7TH/3z3nkTedC+y4GiMpN/k5oluTnmiix9CHJtDukXYulNihw7Asetckii5nObXv4JALEvHpBeyrYtBvIfXbcWYuHeDNboDYJe46sX6Y2WXxgV99ynLbQtngtpD/mnacgVbhitzFTQDig/PKMWTZkPFCBXF+MLrB1Ksv1S2lviF06X6DXaU3M+vqRf4tw8+qplOOBxifijPDw==
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replicate-to: udl
      creationTimestamp: null
      name: postgres-creds
      namespace: citadel
    type: Opaque
