apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kadalu
  namespace: kadalu
spec:
  interval: 1h
  chart:
    spec:
      chart: kadalu-operator # The name of the chart in their repo
      version: "1.3.0"       # The latest stable version
      sourceRef:
        kind: HelmRepository
        name: kadalu-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    kubernetesDistro: "kubernetes"