apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:W37V8kteVr4tI6X0Q7t2ACUuRfqB518=,iv:DxCRLqDDeY8RGG9d1QC3/FO6GzYoU3UMIe+FQmdm3WI=,tag:KmJQum04Ag2PRA624NG4WQ==,type:str]
    RCON_PASSWORD_SCRIM_TONY_76561198123577596: ENC[AES256_GCM,data:/00Z6L8o49dUIVbBH97fi23BHZvzbZvVbQ==,iv:QwkQqpr6stgOeMd/PsiwYkuUMX4UPF8KYSEMzNCHtEA=,tag:+yqUaXJsIYS70P8OuHCv5w==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNlREWC93RVIyQmVhbXhZ
            UlBCYXdySm9XZ3NYWjBPZ0RJNUlJTitDYm1VCjZTTUpDck0wNUQ4UUUzZEVFaEtP
            SXhIQVJKcnNxMDRJdjRwdkhkVnZOM0kKLS0tIGVqOG5PQlk3QVFKZTF2Z04weWhl
            WXZZd1M2cFgzeExHdXRnVzhNbXp5dzgKEAJt2s48mHGjgakmUkpU922rZC6rGlF4
            0iiNM/NnCb1nVjJ6IIeMXvrSlkS1SyLy1fbnWa4vDk9Xq6/UYAM+cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T21:30:40Z"
    mac: ENC[AES256_GCM,data:K6AyHXNg1NTnfyfY7sFzDkNqr15NqQL1awaLYHpPQTuRAMJs5GahoIjPvTaIAh/pKmz6Cv14WGiuSUjeS+oQ1C+9gtU2QYJEbtllyNu+rTUINQyKQo4HfGazMfDXjSwD0AxJ9GBI4BlX/RJ8Jo4gfgu4PMKTaEnY3ZE19Y8Np5o=,iv:DBruNglerTxMQAxu+cl8j1iBn6r0PLdeEgb+UhrafQo=,tag:Y7fRyHw9aswWTY1QVZt5VQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
