apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:cmsZkrJ9ydVleaB55wuc86qle2lrID8=,iv:oanRLBR7aGDQyRDLRtLbD5FGKCfuPEObBd+z/sK3JBE=,tag:kB5u8JA2afeP/8ih5lA2bA==,type:str]
    RCON_PASSWORD_SCRIM_TONY_76561198123577596: ENC[AES256_GCM,data:wUxXE4lY7ugTWbhQaljYpkVLfNSQzJo8ug==,iv:IN0axJwMGh0dY0S96klEHUpS3epWt8rSZJiw69gNQuY=,tag:W8IAOcgLT+jLOIXf326tqQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WUZVcTV1bGQ0SFFFWlcw
            RmxvMUxXUGtTdlEwMU05LytDdXBGTDFUcEhzCmRVazNYeExEMjFQandRRGx2Zmpx
            SWljUThJOWlwckI3WGIySjFDOWFpYmcKLS0tIC8xdUlmdFNWckxjMWIwbTU1V1lC
            S2RUcFh2M2ZoU0FRODlJVWxLcHMrQncKmX4Wh6kJ5AXCPyW6oowVhkXYuQzJVGNw
            9oY4fXAPT9IHlEsqdN2UPAnkazuHIezf+si87f1qGiTHAnDDX5a2ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:56:35Z"
    mac: ENC[AES256_GCM,data:VuZe4/lMHHjlzfY4vi4ZX6Yrc1Ws0+T5klLVKBwJ2I+ehlZSZoZtd+kkJz4dFyUr8i1hlvHrTkiW/TMf3GbAIooeNowqhhq2Ylfr9OlbVzKjr1bhis/Unv0LM4oR0jsBXKMQtigbhjm+PX9IK1h5X1l7Q5EWhj4DHlIeN9C/Nfw=,iv:Og5sPO++B4Ly/rzlY+K0IL14UWtNOQbY/oOh3tLsNTg=,tag:mUP4n/xNIYNhVN2TSEfpnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
