apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:mq9E2p3WPtscJCbWxCuX0+n/hmM7AQk=,iv:zC9xsb6MG0VmVDk0fEzHlK4jcdqqqAo+gKKY7LD4Tbc=,tag:Oa4Emv3eNy+0zQuHYFOhaQ==,type:str]
    RCON_PASSWORD_SCRIM_TONY_76561198123577596: ENC[AES256_GCM,data:I0VOMLAxKaw3N5/ddxzYfJvOAnqUpXMsuw==,iv:oHjAd1UfqYA3fmgRd4USjlJ+kkEOBT2wiqusz5WocmE=,tag:S7WwP7V27GAisEonxpoH2A==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNd2ROcktPUzA4Um4vY2Ux
            akx2NEtSUU5uOGJSOUtsVTBxKzVvUkp4NnpzCjIzOHJLTEd0cWZWbEQ5Zi9Wd3Jt
            cW83S2V0U0NOMVFxTWVqK0NSaTVjOG8KLS0tIEE3dUFwUGxXRXBGK0VaYTYzTnR5
            cUZFbHEweGZueHJJL20vR1FqU3JmNkUK/LKW+PYypYVv2NjnKZowbAd1Llwdj/aj
            p/BAZr4e0+TvNO8wieUt81tEolHzcMTPP2SqtULbuQ5W1cBE5AbSTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T21:54:19Z"
    mac: ENC[AES256_GCM,data:xBWW8UjsxVzJkWc0Z5kGvIqNyFI4oH7Wd9CaDFOiW50wjiOewOT/S9/vplAtiOz+3sT3uajXTw94zjY7+8vCjcmCtMCxMn4g83xhmONjDGwM29Q0Zc1afGLjiI7S53XVDdd3I7xieL7wHlik5+fUdBzwyXHzeyT/vd4KuQAs8jI=,iv:vL2Ux3wjxj55Ca8Zmyb+yOKw0AUDUtA2OXlVdGG2g3w=,tag:92diZnB1XvfYhl89mAQNhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
