---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: steam-api
  namespace: udl
spec:
  encryptedData:
    ANALYSER_API_SECRET: AgC9wRNd9ogMB9l42evp7ef7CQumG1PEvIlxSkyKq/tF9pTYAOj5ksjaAUuatLW1yi5ER6SxpwCCZ0+ePYOGO4YZWV/j91b4xCCM6Ijxl86lBRpb4dxvX4tRfHzKRgdhURo2i7YAUsO/HsuI+jo+BjZNSP74odqQEO9mtJoFk06yO+6DGrVVEDpzfdHn40jxBrdcRcxfQCwubpGV0MtgYhrLvhYodt0O+N+L58E68NCxV7MQHEMliFoJhszU4M+lueQ8jDLJ202rZIsadfT2Kx2tL8MPfy01xmxl9et4SG8SFyW+Qw6eYqTKXuUX/SqnmhHxx4cf6mgxTbp0kPF0sGzzyHFUIvBYldk5PYog98SPpV4+H2EWLf+tNXov7ZA0B2qGvBzS61eacE5D3vfVBTNNSnnSJnfMm7WPrIfKZoKmD4veg03mRPxucwuLtdfhvBSumzanGZUrv3Egirw3mJacgvgqQhsc+NjEWZlhfN0YFWnO+FfZXPKsPt+cUfDnxE0nGFx6thMBkhhS1ZFMAJySu3DrVATLuXajjSl+VPu3inb6NcWJA7fzOfw2qsezKHEo11I00JZ5AvARoscYyjNhMZHEkpVwH8wIUNHE+GrcYo9SGkMmza1p+deKDplO0GLEBHP48aZjJaMx/jww/KleYR3JpNdgdmeJijojG/vRGN+2CDbx08CVTzhHQZ1GP9mw5I4Vy329LU1PtyP+LVnIfbu01IDCZow2
    STEAM_WEB_API_KEY: AgB3F0IEJR6LARrGxTFqm+TK75QvlY+VthAit8mSsUVMZ21RvWVZRmL5amNJTNvHY10L1GvoipQV8Ks+kNgukEWPkbcfjlpy3aqk4thnKCBNxobw44UaYDomKykrswCI1Xd9C5fNant//yKRyvev5ieptKyO6uRC+VDDTlRX6/T2CSxw2jlU/wxEQLZuaqUEovSYXGnJ11kU7XTqJnuYsh4S2p0Xu4CpKpAp/0uFzVtKS3IsjHQ9fOmR2uwRfAGF4q2Zj2p//DoeFVunDP6J2KtfboCsqCIGQu2Ea9+5NW19+8IY/rQI0u2Uj+dZ3XQnjObbXur5Leg/4ccm+rxtLYDbGCph918dSbIcxM0goD2A2CFKZ5pl9Gl+Kd8HONtqoMw1Eb5Q2FE066EU2qn7SJh4ts9rygxwMqQ3yOzpoANVVdzB/698vU/6AUr14n3Ldm1Q1xsXmdHh+wn3f5bJB6NRkrIh/d20SKx4ASl+Uxswmm2zY2oC9M06j3UDoqcS1KAN7DCjKiUdeFGPKdK9z0oYA2jwevoRkKOXdrQPG+nAwMfvmj+ZS2LWr38P+V3gHzqxM+gyj7+uJigPGOMxwLZ3SLhjHX28XquyIsbGiwr9KI55k3OTFNdPM5KxzJNi1sHOckv7qypIlFQ18U2jjWHdMnpR1IbuyOhylS4CW/UgR/y3uKnXr9/1UqvGn565lIfB2ipFLbcdxqPaX7AxRMfcBPpAFj4IXJx0FiNW3kc5gw==
  template:
    metadata:
      creationTimestamp: null
      name: steam-api
      namespace: udl
    type: Opaque
