apiVersion: v1
kind: Secret
metadata:
    name: steam-api
    namespace: udl
type: Opaque
stringData:
    #ENC[AES256_GCM,data:M8jvDARofya4BnYK4o51qg==,iv:fSZO9sI5+dg3vUDBcdyCB5d0cQUe0zMYJ0Kw4iD+Vcs=,tag:6ZQlZnrPhMAC3Yrtx8NUyQ==,type:comment]
    ANALYSER_API_SECRET: ENC[AES256_GCM,data:C+tq60L9laxHfLiC+y8sSAB+evhywJBbrw==,iv:gq11O7LQiYQ4h9hzpjIDEHhrouisDr+QoOnZdQOFdtA=,tag:U/nkfRpIreAg3qKJq67sSQ==,type:str]
    #ENC[AES256_GCM,data:Ft82vY6fS66+2pEsZTK1CgXWdppfJrs=,iv:0jyEqdNuo69R3+qlEn0pKHn8EaBnz2yOrs0iPoeXIos=,tag:b27nnJJswFM+WNTgW2i6Ew==,type:comment]
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:Zziv6ZjuyF1mXdUPYnmyNJdSKGCK8ZF9ZiMCD/UTXkw=,iv:Jnk0uxYvcasy0xVB4tNkQ/KAnVERiM7zMFpS/VxWh6w=,tag:wlaSjLvItyLywuMPlikVFg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZHdyRVlaZVhCb1AxTzkv
            aHFwSnJsc05Sck9qMDBXdy8rVnRKOVZoWHpJCnN4dkxFRzYxcnNtZS9teFF2cFBW
            UkhTNCtLTlZoVGNnelNKZU1sQ3hkUEUKLS0tIC9Tb3FTKzJ1REFXeTlUMjJRaXMw
            cUh4YWlaZ2RUQmdncHUyeDVTT2U2MmMKYbjgh232G9CyiUiqZg0SXwebfRmmWTWA
            WmYeXE3zDNFE5SwuvdwCdp1b/6sope4S240dw7ttoreNpdaE4go1TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T21:09:18Z"
    mac: ENC[AES256_GCM,data:VX/NgjWPCPqT2oi3+g5fEoN6OUgjUXFTlLwrm+97wLnOBHkIT3SHJsJA/hIEpoRhSRBkOzdB1RazTy03DcR8jwoeOY9INMoO6DfBqOhXjHE1WLBGB+AuJX3qC9kmrA7fQbHgfEbjUCvlJAoh0B0Fzvc1BrGhXujNDuu7eU2CKCU=,iv:cw68ewlEZ05tMV+k2PuiS82mCLkW/ZVFou4WFs9dxwc=,tag:xQfJUQj6hMK2db6LBV8hFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
