apiVersion: v1
kind: Secret
metadata:
    name: steam-api
    namespace: udl
type: Opaque
stringData:
    #ENC[AES256_GCM,data:bRj2C7NuPM0GIoqbELH6PQ==,iv:/O39jlquKh4yhwejNpCRMxsMiPvbk9QI9l7asuF+Lbs=,tag:dckCsDLGpblK7EqkXL+dYg==,type:comment]
    ANALYSER_API_SECRET: ENC[AES256_GCM,data:kUwQ5T3gvgBRGFKOupT4NuUHZ3p8Jb++OA==,iv:7s5J2ovChWcHiWFwXJ9D36WNKxCRXluJe/AyF5pl8H4=,tag:LbTDREXBY8YkyfynMHuT4w==,type:str]
    #ENC[AES256_GCM,data:52VNLTO+JIWHaQP74PT5v/dOcR6p9gU=,iv:VtF2X5FAc4SEXWqBEQJQBic1kVnGykM+WzzUPp4nBpY=,tag:Fa17lEF+3M/2xbjSHjpE5Q==,type:comment]
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:9IBlVEAMuAlSsYhSPrfLsKjlr5fPECEzulUpCOfj72U=,iv:CYIVKnhPw0FYNiQjRI3f7tL3C+JG5lqA+C2WgWU7+PY=,tag:YdyCTc2clJ7E3E3vCTRcXQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WjBEY3FFblZFRVBUbWR2
            Wm5jVXdGNXNKeDQzS2ZKNWhmK0NnOHQybjFBClpHTW5HWTlwWXdLN2VvTks1T0VS
            cFhKSENTWHA2S1poMGExRmlsOFpUbTAKLS0tIFRzemd4TTNUZnVpVmdUNkhiQnVo
            WHZmMm1GdWRybHFLMGlkVnZVaGt4RTgK75NEOFe1G2G8fq/FAub2I/Ief3VSMWot
            p6RcD+sYrztuM/M/kx7INFo3GpwmRRCmH0IZYkmB0mwbnfIqRPg5ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T21:54:19Z"
    mac: ENC[AES256_GCM,data:lwKXOv4YYZSK57pmnp1lH4HWGsMJ6UjuZFth+yELw1+H2mt9Xm6Q5d6q1NgE2JEkksYBSzG2FLnCpVbI1orD9xmgfssxLT359UjI7OeE01DTovBYZWvwpPE1+KcKEaz9RR0CSjw3EHs00I93I/VgDwFyq3puwayIrjQVToFm1hE=,iv:gCF3IADFqokNGXbddBWQnpownMF8vkkly/h42QFc8ag=,tag:/CWFsL9vjyqbaR/oA8B26Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
