---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: steam-api
  namespace: udl
spec:
  encryptedData:
    ANALYSER_API_SECRET: AgBUtV8DTw6VhdKP/y5+mC40FldEQPybtT90OgB6uvn+URIBJdnan+fUYWmkzIPUSM3ORCimaAxLd2V3kJGshLUQVfKFzEHj0+8+ckyBj4eDV2eLaZ16r9//UGicjEjRdkSFLPIFkQyXtaYPIDvXbtJq0UzHZX5PseGG0vT7PYxi5TW75FXf/X8xWDJ6vOGglDfNjSJ/ZuOQKHIQ7X4rlLc84CaOjEjt4l+HTMWur1VkUuBRvJZH+/di+B6/4qpnIotVUEc4XA3cDUd/Y4FifplwN31qlCE1FuxJzJeUN60xkK+UdqP61Nh0SFi9IL3/W/aKGhGhetZTW3r6ug0k26uov36BxN3LOa2aXlO4s8BZYKZMuVTomPmfnQfevkGwD9QXEm5NRqkEC4OZZCnK8FyqCmn7ziSsgq36nW0/Yo49liGYGTUC3/vqwN6VKb8J6sCmH3okB03O+1UgzahVWByZ16HOyIyMQuhhgvL3ZnpDslRuZkKesoQO1KD2WFsYzZfIj/9pUVjTOdNJfU5KQlpfmzbpdsc7s2PkDhKfxJCZNSkCXmQgoocWnq+Hgnn+3azaeHtVL3485Ag9Tif3jfaz6+FiwgkZAtdbXZw9IWVaSz6NJqm5z6I4hOVfIKiz2KxCSTh8eVlrTTnvndhAGdy0W5QIu/4d7JIPxSH2ZYKwMH//TBkuWldp9O7aaxSZrTbA/PYSa87xOjcU7JDT69h/7wGWssFnDoyd
    STEAM_WEB_API_KEY: AgBWxCgbbnA0z27XhjE5lvXyHVuZn0385E43Ca2VPifGrpf3zC+l7qBed9V2zYuzz2FdW4oiv76GQIzQnRUodtc03YrzFV4nvJTxUZn+lkNbArke+cdfwESPQZAkKrB1hIhuVuoT23EOjwLf1hD/CbUbecqTs55TvXGvr5F1g1XitTO6Lrv1KHauqSaieD3YlvqkTqqhBGpWIoX9EQ/w9q9CrSbDgdNTfr1xSvaJgZLSMgcVsdyW4d8mZoouyjvJf54fAJ9OKa/2kPycCsAsNBU7CDirJxa+HJ56InVtsz5BranmKanhPmvk+zu95POzz7UPKlrUj8VzVoexAlJwmvzdLmb/bcYBYwWU61RRxF+QvwYwuFMzkb6hkBXOv5ZQWf3gKU5Wlc3GjeUyEfFs42vxwlXA1eJ7l9PXD2mDNWtJ9HsNxU4eztb8gJ6P5JC2P1QnNKTw5IZPjPvJdaJ7VUuREkkYJXSvVFdfa959srBdAKzsrZdE4NWPsltkf//z8hFLUCPbhAAb6nmB/D9Esjrbm2EOWcBvuCb5Wc+tyfCKQAyIn/hkfmcToWS+2iwlG1kozJDkCb0iv7Sejq+Il+zGAoBkkm4II9rPuhecQvY/20xCOSYfz274XR18Pmz0FrOviIb85WPBZl82Ygy+Z89rjySD9k8V6jD1f8prLrATnolzvB+J5xGAqAvxy88TWTEbqfOAHlc33lbMPM+R/wrxfMyIakBEH6N+Iz1Q65Rjjw==
  template:
    metadata:
      creationTimestamp: null
      name: steam-api
      namespace: udl
    type: Opaque
