---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: steam-api
  namespace: udl
spec:
  encryptedData:
    ANALYSER_API_SECRET: AgBkw/39+4mUdh5oFKa9UP5V6BCL+d6r+/sDok2fJwruleXBvXxxU0mk08mH1yTPU6vKqB1pS8AEIqAyXoe/uHGzRZegxieWFFDSnYxeSh3+n2nwKtaw4XVKBbubeWtbhwvt/GsJbwQ6Lk5/Drt3S4GSmzq2OOeAHOW9AjvUdhUmf0eN0q3jI4ssQKyDD4JQptvvzN46k2VPC6YVl8SQXCAOIIsshYO6r/tUqh/qoOO06xEbj1i7DcWTmw2J08axye6hK/iy8ra3wuYIupMGO/J1NRZRh6peooWN2dz+7r4lCnOEC14iJRTPqVqWYSSbTKr6efSs6fLLgGHzUWyRpeQsub3YJB2BCPdipIx9LZ83iUdVvjNXGKDo+13VyN0ySLJIeEolxFH+Gz2/IG7nMBu27KVs7Ov0nsAJCmWSPSGJK8G5yz5ysnBUSb26wKdIBZouq7TABAiJ2uG6PD6/1e8aU3kOW+jzdDzMM0k/Jtwy6en83jd+9SXZBa2hSHnPAlj2nU6xXQSiJIp0z0cbChWKNohDrnU82yfQoquC0PY3b2NgC3abEx8+esIgqpysipIqTAsZmn3/05AZXm0316kwmh66N4mlaIOzYqEMno6BPuQmcMfnBbdrFoxIglCXr7AGvFWm3pwTr14ehAkhTj22Y7pedlCUUYYGWwpTA/wirw8lb1QLTXiAanx9An3qTnViLZ62/db6Z1AMP5SSWlgQdgnmixdUQM11
    STEAM_WEB_API_KEY: AgBCVbnyKYom4WXsHKQyYwQe/3qbm3ZEzLEn6FbEgRQqoqT4hDkSj0z26WtTcabmsE7cN2TpqflnKbwDq53vd/0qNfnBJXyZIqgINMAR6qrl/hG7ZYAbDYO6EkCae1fQi/hYor6iaASROM71Jt8mvJQ3KVe1MeHiRLIosKD6LY/e8Ag5LVdC2Q29zfpf30VdXovzRAGD4tnInUKeuip8aCQbZMguVHRXJh8X+6/jJx+BlLs80YK/WCNo4qqjbmMwat4M/QTAO0boYppatRNRgXeJ87lhM1w1rDSRvBmcdZFnLuf5anoXPInsSkO2iHNkXyZrM/Y0gn5i3gQ/GN8bnIpnSAFjq7RYJA1hPDnyMCpKMWQavjJmSU+vfbCyOBDH4kQJ6QlVqfldEFYPduZsOPSHFBWbAmuYfN7WM9Je/6+527SOdjUBh9c7OK49s95TIRlO9oeU9rBoWLDjQniEANRKjgxHiQHkaGA68tar/j3KiGH0Z2VofK3XhZMxf16GzambA53qRMhVTSLr0bp/JJ2I0LbEPNQmQOhGyU5TPPRVk/IhnSkTGHPEtbKa3fQjDRqQGOO6/RrLIxx4TBsQ2H3YuBfJWFJaNWAJ2SbguYx1IKZsCMxrE7FRnFPr3ddYGauJTl1FYjAbLuOVgeAKnMUdi4FvIchV8XP4rAlaPzdrccGRvYhyZstOoZu6kVSYOI7lxLZMiT9ub9plubdZBPZ3sfi1cSPufMHbtcFERJIogQ==
  template:
    metadata:
      creationTimestamp: null
      name: steam-api
      namespace: udl
    type: Opaque
