apiVersion: v1
kind: Secret
metadata:
    name: steam-api
    namespace: udl
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uooGAgkxrgYCJqKPML7ybg==,iv:3gcvhXy6kUMaJvPfLGHBJWfAaHqHv1Bstx6Ub0Gmndo=,tag:G4V7ltQDLEcAlEyBXxc9Qg==,type:comment]
    ANALYSER_API_SECRET: ENC[AES256_GCM,data:iDuAFGtcZKgSSHglZFf7mQPF4FQYmwBUKg==,iv:UGx/0kimNjolzd8lw+W/Kfc9w05VnMnpsrdmTiloJSs=,tag:bvzijAnN24sZsI1i+ifkZw==,type:str]
    #ENC[AES256_GCM,data:yhYYpe1tVyJbnerx57TXEkGVwRqppWc=,iv:2XfWAEx82DWq76XLkikchpzzoX3QoUjDTyLqhRW6lQQ=,tag:KO/wGyVTYaIUBfWpeW2spg==,type:comment]
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:+cjz3/pTVqe7CU+cRqbDVDs5xezExPTmnLVug6dleh8=,iv:DqB4U8ZNRkBdpZBVh6H6+ZRm++/bSSbWChG5/Rb+XZo=,tag:fu1LmTt5Zr3brYsadq5cKw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWklZOHVQT0wxWTk2S01k
            Y3lmNTRwcEMzbjZrcWRMaG9GKzVtdUVEMDJjCjBCbEFFQjZuYzZFc3RITzVzL3hz
            T0FxS3lPUGNXM2c2ZnN3SjR1cVFxZG8KLS0tIEFNSHhRTWlYRTZpWG9qK0lEVnFN
            aisxOXVrOXpWc2RiNmJCc3hPQVVnY3MK61gvS5nStoJDKSh2HTOpSoJq0tNCxONJ
            I+5DBQGuvYqjYgZ8oqgYNUrRv1QwEU8w1yNNdEtbeGmWqHe+kgCUEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T18:36:38Z"
    mac: ENC[AES256_GCM,data:gVWQkaIIf4DWuK8CM2vC7lTsiVSs1yCtjvzrJRolqknSsKwCPXx4SN21IS2utcaIk4+LsM6GN8AVKgkXhJl7VJzwFBwrOdNk5Wlg4l9K+AP3BFBylBC+pjjr0hSlfjW5Pv2dgnhgNwZmr+vsV038e1r1aLuNoHH19Ni6s9DAvmY=,iv:xr0mg7GdxNiEKJu5E0WbaBmHzV0eRFA1rc+IIxTC6zs=,tag:Uclo+PqKSVTGdjBtBIj/sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
