apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Pbj8SHvUEg/AJ29dZCDmG3f7VMpXGK0SsaR0UeefCDAUOLOVQJ2abB67zIfyuDh1dLw=,iv:cDEnPPwS7EqZOEJqJk1ZfwbgM3hFhLcELJVLkbJ7Rvg=,tag:8en1Pzw6Ea9qdff9fnZLJw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Mi91jZudUx8=,iv:cjAalqNgafzp8BrzWyIFy2Z5gqs/O6mQG/Qh2s6g3DQ=,tag:BAclKcY0hq9zzGIlmIUJYw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb1FDUmFHL2xwZmxkb3Fn
            M0hIbUFSR1puVWhYeGp6SkNlM2E1R1hDKzIwCkc2Y2JPR2RTb3dpZWJzSVBKTTdE
            RHZQNVJjSEFITFBKc0NGYXN3bmxqN2sKLS0tIExJclZVcWJVM0VGalpKendoMFVD
            UDV1U0E1ckFuYjlkbUxONEdsVklZTlkKCWD8hZFJorQZoAfq/2ryeRLBBXRFCMeX
            8raCQn0xrbZMeh19n8coNalC3FuE3EOBk1ON3kr7DcSi248o5AoaBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:59:57Z"
    mac: ENC[AES256_GCM,data:nCDiqqRf6PNWdA52v1pYdEdoUfcnQ2uzJjVr/gLtc6UpLNCKEaCQ3WwVzSrBAAS4vuXhVXYBgrdIxweXqBDf2i2pF9AppFAPgKSr9nb32hpQztMlbvVZ/QEpVyaBfNgYzHjCgg1WF60RQyUkxJp1Q6jBoewnCFsz2K6UbFB8L1k=,iv:xQmCvjEsWdEgsi7MkZrec3nm0rHF/YKLz4zNMh1OWuo=,tag:ZhdzxjS4+W3f4jlr2+JkHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
