---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: udl-stats
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAUpJfBUhDoB8r5TsoBQxuWva+IUznSocvQ/Bsyw7XjUo1XKHzWDI4TW+vITTvVP0roRZ+OPieaYMPx3d/NJru2NfEw+3Z07n1r7xCJBJgIkHNIxxcq8r58DWoZhlVyzXtvJ9YGE+LBM+OSr7t9WCGkGs3wjyLEByvNv6hQFLGTt5SdY0X/6IF9gp2CO+qQyE7I+Fj9BezwR+Kf/8Ub/vfkJ/3hNnCAR5yDTxY2jhXo6KseLcHpV2mIl4Th6qgMVQC9v3wZ7s8rv9yFMvsEsee2k90RQcxmLeytWdw+Fu0sHfQFFYPurRMsqtmUnq3l0iKd0ByarYQcLbD9TCAc3uYKuVxHD3jfR8ooWCygYwU/5WYVawJOe0WY1iEb71QhDI6si+vwnkV4qCa32689mjAnvZrNkR2QUrqjDRnVEUdrZ0Ia90p8gGDaLz0l/ocXl0WZ6ZNV+JLiuJI63dKvdXVi6ntkYQVUjlpqNwkiXbd2x4/irK/Dc8cZxgfTK8oaNJR8k0w073JYUn8DOMTseczypCpjuK1oXFAJ77KV3weT1JYjimJqFfTLwx/s9wUMRYUJZ0uz4mWFSBA/xrkU428VZOJA+b6Ev7dVq2RKm0MbdkQ3qz78cnFnknAfJS3BRriQsET+/lhvlO0e0RyVjFc/T//evEuq+YpJZzBqbqhcQ9xFQGklYa13Vi/UjFaVOqEDRAlzXw5SAA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: udl-stats
    type: Opaque
