apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:SlOA2t7ruXMvgtRrxCieduVPjeN+ji3QOfYtjtMVB86X7DO5Gwm5x6CWP87KFaFaEe0=,iv:KxGH8gQxKtHX7a0wY1XR0KJq2SNEwMUZQN/98zKYr7Y=,tag:L9e0zxtMl66fhUnyu/57Ww==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:HfNbDWZEfE4=,iv:tXXR3VX+xFV1qxf7tWYyc2XuCB14hWyzoInBP7sor48=,tag:Xu5z53UkY5aMTRzWPwGv1A==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Z2hITlB1VnRhNzdjdUZq
            blZ3SFlxYmg1NVd0QTRNT1VOV0pDRzdJYVFFClZjclIyVHdkaldPTXA5Tno2ZjNT
            WDJGelQ1QkxWb0xJUHpHcUMySGt4QTgKLS0tIGxubUFUT1dZQ2FFNkUzZ2Y1bk95
            WVJ1dVJEQ29kMm1SZEVjNENteVUxZEEKCIvt1wSPLpWJbiVKeEbkUcUG7NEqdKLd
            d4oy4gyApN4V/EiHXOXvvz16WI62dmEfaeVFobvsdhkBKqDj+rnbHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T21:09:18Z"
    mac: ENC[AES256_GCM,data:2Ink6UVJvZE+8v+5kJ+c6U9sFg/Q85gv2r+6+KYTNBXjvbtzgY31E4guS1iC1Ys+WNNnJF89G8xsP5iFXBg2mwYNsK5gjahwMDKWMW8LNvlMOYHO50yea7LFHEuZOvohP+55isvZ0ugJgtEYMyv87sAL40ped3ScRFSPzyEjTwU=,iv:Eu4BOAKsGMNa7U/txV2oofpioekqXlTT09T7z4gUVBA=,tag:rR+UXZxJnPgDOcytDTkqmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
