---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: udl-stats
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAhWxl2XB4PeW2kGOz18m2MJa/l81pX/rt86GjMK76tQ7ANmaA6eFzZftfzdmR8yDZrX4tKvLvuzrBWLI1Uzbj8kja6b1VmGIg+oEcXdU/JIHbcOSPK7wNKpXPvlviDYXVAbVxdJYyvLy25V3qnWOweFVLuxGHzQyUMfcFWTuTLWIu6hUI2qoTXsRtP/ps0RIcCgXwOlCkW54NfZ+7KZAtXM8kxWlw/DdQYLvXFq2Nb85ONNsvH9isJpmIfQCbbqSNbupg+6u2bMqPW6uzXI7vTCHA98lvwqu61Jnm1EgOU2o0AQRaQMYEY3YMOYJ1igeOG9qdnZjur7jm8AysZGMm7ZmNcm9NbIYowNcISZTXTtbkCqJGssPK3VyXkKqbezcXnZZx6vrSLSKAD0xpjbMKnBz2jox36L5E0rrwv9hRBbk3tBZoJ0sqNgjWlJ9YYP1eukqsLt0psMtgNLmAiv05ukrnFoNFd9ZYj2BMU6LNaR199G4GlVNJfHRV/XRS6S29oLc//RiSOhN49bxlV26WwPdLZmZaJOXJVgVXUOAiaTIYC1Eh76Zew1LPIfB6TX45aVO3cgO73BxN5sMZGskb/tEqOkBS51mUPOyv2bRGaMc3Hpb6gOow13Nx+BRqo3Ga0KEWbJcRC0P9gAIy3vuP3gmNszOML0nWQN1x/JC5zCe5zqPGi+8Am1Iu8j6GyARocXePbexImZA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: udl-stats
    type: Opaque
