apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CQJp8k1nD4LBHSEDh0t94aC3D13DfrD7b6ddIsqfPAwO7WPwR+mBmw5FG1qgGDJg/2A=,iv:Iizk7VI9gv+0a56E8/SWItIEypN6OBloNgmo8ezhtPc=,tag:OlKGsPoktCiudMvE0v28Pw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:p/u5LNfCChU=,iv:zufe4ou+XOXIeAIFQkxaajjtDedz1HbD2IlLhqvFaz0=,tag:xqEUnFE4ZRTQxyFsLSXDcg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM2EybnNURU14ZjJQSTlp
            US9heEZrMmczSVlBSnFVbExodmpLeHRtWGpVClREMEhGU0pUcS9odVVOY1lmN0la
            QTlrZytBOEk1VzZOcVVBMlMxbGJFdXcKLS0tIDVqbUtVaVdqL09ZanlyMUtRMGVu
            cHV5bnMvaGpSTktCYmN0UG5YMm10MmcKC8JR8qI3eOQ53ATgJJ0e/qJ6x3dh0EVa
            ZKDxVOflHbhX0N6VFcPBQA6LtHh1+HDPz2/mUbZ7g9cYXDIFv/NxVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T07:49:40Z"
    mac: ENC[AES256_GCM,data:8WbRL1w4Rmm5JRm8+0PJrX+hsHEm3io8//f4WPDLn+jctyC2rmjClBtpIAEMMZryWddsEhCAoyWQmQYCc4QPMe1COepTPMM9Jp1IQuKwSivwfybKfAPl2C47a+rtIEkg+ZbSE2iJrhnQi/uMryNftzVKse3AABOfLeccDJ6fOng=,iv:h9gmLyEi7Xmzvug+5TnrguMjgKU9hpzkopGtyGokAKY=,tag:sgUy/yR6EU+fAVwOe37cQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
