---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: udl-stats
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBOteclRKmqbUd0U3lCQGcYeCW/1OksQMIG6/2dcGd6Ud8QqCS6Lhu9kAvEnh66rm4uJJyeCtAcXkSPZBtyn8HE738Qul2TXvQo/BzoAPP0gLPBXCFFjdf8vBgDU6Ep13/uvsZ85VZvw3Y0KnbMPLmSF5efOzGXzIwga9D4Xzt8XCBWB35BI4dk/WVAPclPBq5RA04qs7pUYP3BpEHnnb+vPknz9HydZ7GJYE2lJH1KKWtXcyn7A/OKUWWndhI/F6BPhwPHA6oqBu7HD9J7+1KB01DWRY2CPdQW5oyJRBCUZ9J0tse9bodfYLxkwU6/6IZqss1+BljNrVf0G0OCt+4NJrtttnL2iF7llvXe3QnwbC0wOpjYCAYXdb5A9bLN/qYsHJhOxbsUN3Nu8IwBqlrCYfaHc2NtZU3PoAWzcrzWOHF8Tq+BuYL0JKMgc2wasblFz2Yh3uo9zAaAqGy0A6oub/RJ7ZSefV0z+MF7gAt5zFKgOlHlsEzGBwzrPacUF3mvLMRxa1cs/Gijzvrep9i2tee9ZUtVRNwWcHGW2SPS/bI5afiApcTElr15fSmHL5agApKOTPubCyL0f3c2V7yK2nN0MZZ3cGf9TA/XakwxUc8hCs2A11+Qjpl3vq1AKqs7tweHf9goJ7dFy05BOsmcdvpIwAHuOjIRoJULk9RgLkyQETXILVRDB8gP8jF+aRXB/VwnEM4jhw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: udl-stats
    type: Opaque
