---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: udl
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB5TV9OL1vdf46twuYP7BvKnNL2iI+tPpGe2DtAIZzCPirRMPAd5lbGil6Hs9PCp1HEU1y8r85zPj13HkKlKSSFgnQ2i20fH8m+3KX42Ay15ZuNx3El/5s/SfKw0eR1OPIcuzYxql/uM3etboCBh9rrd8rAaQKJdG5wGfMb2VfV8FQNIPQoDM2wJ0dCzNrM+VEMdSJhnLdQRa0fQPHteC6JU7TPK9B6FNaWhzkpHlD2xDrDywFyq7iS7Xluj7K8rHVlHW1YExT5h0kZAnieGsD2sdrF92bSXkTA7z48feNuQaDwjnBoAVUc6v3lC0iKCwWJxwKHRMTtYHutdY+NtqIk8La0YrVqhiIyh0FNZBjtMxWS8RkhoQwzf9laQlx/p3RFyUQgEbAgD0B+2GN/JZU6h4ZIPHGMKBcHZW7cpLwFJ5QsHw5Ys7JwMhDF66yMD4wey0n+aibAf7HNU3/oe0h1sFTftiENVbyNhKb961VudPTx3FcLcoNjRxuYu87+ePdq33bM3EYYPsKqUSrItBNhEWf3lMtmJI1ZQy4E5KySXm4FM4UjqfajUicCRqH6rhvSLLL+D+Bg8C7mMIqsfMULSbAfbod8IoDYtw7F3CLVXzRVGzxOHV9QxU1+S2TCx6FB9C7pJPLD/pdQEkx4LKJWykjcxy3bF+Xcf41cdghtNGyVDUfJzOSGIO0hd8AeiGbzhss5q2Y=
    POSTGRES_USER: AgCSw40f85ozV9htOrOEn794JVNIdPw1p3MDsBOTeowYl7a6ZQPEdGT2/26som8s4HXFO+en4jrbQFYI2PHxjKPyK88h0KoxRjxaayHP01yOYFJGsBPstM2CClJqSB+k3YU3FU3ASs9QKH8pDYd3p3MEEaw2vH+T1Z9zf0Uw+TTHBWaV0QHkE5A+96fOQk3Y3qcNmpLVLWar7h+M8nJiinkANFXIMpZrXOOkLGmJkCs2VmyDs+FBtT3+40l3zREOMNsHxBW1UOYWRbPtvr2m1Njemz3XzBzRg/g/bfYl6k6FN0My0xkk8Fd45iIs5CYq+ByihQNOGXKACm2JR6NY3mWN8yI4f4+lsxJ2qcZMfs22WeiTi1fl+P7JN4JG3J2b9i9QpKCWRNNxMyDHKvq1RNJMJXt6uitwrftBBiBe968yB98csRbHoleiLWJwFyzu9G+am6vyWXlANYAA2kLn//2F8+/XxHoifGXYtw3F9i/Jktyw9dKVZlxu7Z85hPK/TqFxKLLIL1meNgX9Ndmi9Erx0VlOJ3q+jglM/r3PdGrz8o/ylM70uPZVUfPA9vF5JOPutZmZvtrXXcGAtZVKLtg/vsBDeY9/ejEvZCiqvccLLXzhqzmYUnjosHEnDjeF1bzbUM2iHGxcoIn7/ponpKLifxYCKAL54CKmjYiwYKlJbOkR+PdYFCSKyXCCESBOQFwyFA38BSuLdA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-creds
      namespace: udl
    type: Opaque
