apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-creds
    namespace: udl
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:idAUCxEi,iv:52KrLABdTinRr7OoyRfA0R3LGozY4B5vVz5RXsAhSpQ=,tag:yre/975mwO4O+71XIv9kyg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:6I77/JaN2Og=,iv:658dEAS8Xg1NqYAQM/fMto2lrjoQz8GGo+kGFPu/tw0=,tag:uYqbF68PPDAcsjZomHgpvg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuREVRMGNRUHVuSU9ZSnA0
            MG1XYTZtQ0s1SnVhTHN2ZnhUOGNGRkxxOHdBClFsREdkVmlFWE1PYTI5d1hGRFUz
            UFVRRmVxaVJ0NzhNUEl2MWlKWmpjNVUKLS0tIE9qRXVJNGxabWFLemlQOHJkOWZQ
            ZzcwRDFua0dOVDB4bnBKWWE0L2paVkUKY0aIdFr3th7qqw8FnXfRIyQrV84a6roz
            qfbEPDd0WaZB5CFmwuPNtSG1FrF6EfW9JiWMluMR88dVXe2DnF1DgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:06:38Z"
    mac: ENC[AES256_GCM,data:0czMUYxctDk/F93mRAEKPlaKofTXKOY0KEgaaA7Hzv9komtpJzIyLvHqjps3vByvqdfSzO/yLUKP0pav4/rpceGpHJ3sstEeYHXkhVmXPi0uJyOhphSD44mRW7mi6ZcPJCy0sOQPdlJT3iDvtl6XB1kwXMN0qfscVuCetGApYvo=,iv:AmQt520yhVhFAjTcky9TImm/HZrpRXlUptrmM/a9GF0=,tag:owWujJngkdBf2ZsX/AuIRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
