---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: citadel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAAglzEqmpHJnM2S4FC6ICr65lQQ37/8QiU8/eT8jWmurysHm/wv7y+4vCXwogfzcjRyw8tvdQI1Y5BqTPVz3DuZCxmE5CYQ2ol6s77wJU16L+YNZVWUgGUOovkPz6bMQ6auF3HvVepBIMu3o6ECmIWAwCG/paJHUxdSv1GOu/D7RtwTBNOxcilBv4IdI7/lFb4twX3h8chz+Y/hlYvesCtdDQc30eIZZN8p3I2blJ0dUdU+/kJWUQdCmVSrmC3O343QM2CjzH2uvqq2fDxPki95Bz2t5tpw/5sQsykasjkYeOF1n4y/8blxPtnlU5oEw9+5ClCztx4ZnKloRrs/ZgHEE+5Fe7liAnVLYupzSuGLtTLi+fv58P61wvxxV/sligXTw7hPjanV0J+Jh+1WQLOXJQkw3dRBJjhL5Vq7L9K0J6J+W12sW+dm9pgrXEq5PuXH4nVr5DBU71HPf0ZLb/6lkT3xnKfdNdrB4A9y/qSYKTNStsSOmKuRWUbujZ0n4GIGubnpNy84vBdMWSs/RSK21JPNE6IBsnC6OtAefw0H+57ZI/QakjFc3BTTf8qUqmA2KIFAhdlORefxeELSCeCrNBrBeQuxx6gt1jHqMsrCM0MgGIdul6GJg3+BB4K0g2UYsCYn/EBAwNXYST6/ipppkX0owb8FVMXGrpetCt8bkanTHGQ8siwmM74XtY7+2oCocKa81s=
    POSTGRES_USER: AgBOX8CuIc+3K7yWVmgqlyUMNVA9h4almF/Wr7+REsm2sq3v+DZ2mXK0ckUz7IK7O3j0zibVFVHZjJ8yIKdc+PN8hrR43IsjgFi0QkEwK63cn3Hq5zSctdmMJnIaqekCTLa4xrnwGPFDnvQX5W0DZMbtarAwooVJJN/2EnySiv8Us3mRysvIN+6ko7YW/JiWu1YRZrpqReXZACtvZuV9G2oP/sEry1lSSziblZCvaWMLXn8/QtfA7jFrXfUlsnSvnDDaeJRWOOfCZi0ogmhd336hGXWvgcq7oFvDaVlGq7iIqc51BFS25DuhgIFHJ2vpcFRLonFYTxM5m+SzTlinBJ1WMLbtk+H0gjFh4g9OM1HZOWhidBLnkctPGNsaEVm3hLFgrfU20A82YrxcaU8fN21ilGWT4mNcyKMFfv8Jllc6oHeBozngXkkKOpTu3ttI9O1RHYd89vwB9GrMWmQGKfg1w4ep7qF1rC+OEKBdKJZGL44gEXPPKg7YM5GygPdqxBNl4u2Tb82darsAVC2WS1MfCsUa6ObnxzIVR2NnEfa3oqDeiAbZy9dUOyUYsy1xO1kpk1xeFpzGSxqDfWzbmRPK2Ln4DJSDpsaz0HfHmkyVbA1HXiWN585RnR9jwZIAuSLRmRnXaJ/Gid5hYqSnpVBFHiTlJha1U5gJMsbx3rMMGSTeJMyAtXxAOHDfwU9l72Ox/4nezhRjEA==
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replicate-to: udl
      creationTimestamp: null
      name: postgres-creds
      namespace: citadel
    type: Opaque
