apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-creds
    namespace: udl
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VY+vTv5k,iv:VdDQ5daoUDqtrOdGn70q1dpsNFABctlZgsXDHi0tF2Q=,tag:0WuUMwRoj0/zWR1mCPd8Lg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:R5DRQU0oISI=,iv:aqWWyl8/xFPZ9DogMJ3RhYCTXl98Aa9PUtSjRyoSGNM=,tag:XDwNa1vQOwvZ7iQRkZpkQw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUk5FSTlQRGkrU0t6emZB
            MGlIcTAxWGR0OEhmSEJyM1FwZjE4K1BSK0RvCjRnODd2K243SkxxdlU3QkpaR1RM
            QVh3K0RsSHBDUXd4cVZSTXJSNGQ2ODQKLS0tIENUUXB4eWo1UFhVMFcrVVRiNE1x
            eThZQUIrZ1ZYazBodTNXSHlIQjE1K00K7hz8U41BdIaS0RLD72hV49ms+H+5N8gJ
            vhyjz5Bs0cWnHS45WT4TE1TM9l8fU9mfty5K7tu5POXZW0aVSgEN3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T03:21:38Z"
    mac: ENC[AES256_GCM,data:mPCmZxZujvRqA8sFDPhsLPEF6elb5JhaauOh51w24N8P0xmg7tqY1do7l8wJTRC2t7Jy33W0pMgG0jAe4HsxW6CX8ro7O8ABLVC19BXGq91qQuYcY0d3VlGVagykzgmAfr0nWk9uOyfLfc9lmmwjXofI3hxios8PaLX8IC4l6Xk=,iv:2vbNS3I0QIvvi1I0Xggam518a4hl3Hq4mRpwBKHERb8=,tag:osLY3HqnIZuvSa20lq1vKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
