---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: udl
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCU4IslR8dc+tRIr02ApdrLIHMLUjiDAeu8lstamcY3TP5XKLk+D1IDdFOMttdQRdOPIVPm0kp6NNB+NfAxBhhpRjAX3GcgkH3IvwDXTk/rlS9XfP0f5+OZNJV+e+jMVeaaMXSVGbsY+rHgA+6smsEBQpt6zYvQ6tplsZ6y7yxc5vuxbYK/1xh8eRwWJod40lkRl8jnrDXgQVg2NiNalnF17AYBiOwGKutSxhnHVdjRlL12VaDxI5HoYAYjwhRljsWT3UZcop/gBFB+2C4R6QKkkq3VWF9xda90gLrDUIAoG4V70TeHU4zYosSDNVmtu6JoeBpLWLy3QMrsyLjriz21kvezbzbtP8AEYIIXZnvUYW/3lQdkyKrOsDXG329eg3QHK+VdTcqXYPYD0CqnF+oXo1JkOkH6HCmvS0OmpiMLV/hHfaPnY7n7rAbccEqnZ/prfnJD3KamgWAPzRuAdbmnseedMKS0qUxlhLa+ADCHLopTCHCQKAg0JkfI64b/3ICwosASCbQ3uZN8mXg87o3GVLPTo8U3QHakzd1SbidL5ZAdDDvdzolVgN6bo+zdov4UGpTPBLkbByGOt7Hk5oXUou9m/vSgIvtOAJmsfIg+Jbc8/vcDdXeFc6259hwL1PHTdgzhRV0EgxBDjMVyqLrJjPkMRYmzO+FXqB3kiFpJJ3Jpw3CqgaEUQ1K2EPU40DQy+lXuFXs=
    POSTGRES_USER: AgCydjKLjIZvW+tNtLZhlqK7/fdjtgPYuJmaO28id/2gF8Gnb7Zirl5cjQ4C/UK0Ux5CNpxf3Wlb3vFMvYfs6p2jlMs7IpQSlGYNhyYIhghY2FFBzXtvWV+YzhT8oybI9jvoYGpm1livDm4Ze/bEJBRWj96IRaQl+PS6tT8brWxQHZRNwg4VSgTFPz5OQAVhem8biYReHO6+3cKbNSp0p1pP3nALLNxiuFX6mpKlLZtOeOeaHnxfitkJu8ODZNj03qqEA7TZX5+uso/I9ZQrs76ZN37n2Jmbb63BBsHaQ+V2Y2DXyQ4vz+alm3UUizmIMPOc75KIjRA69TJojyciGmnolU/tSVNCTuiM4IDFum2fsCW4Gwt03BjgUTTbY/HZ4abtU2+Dld9Wjz6opvqEYyfi3FqBnmA2WOUTANTY9yT+glNsqfevgHlISfFMHeGtlwynqTgNVS5i3DhBkjTqBGP77ghkMw3SxdsIwWyb0lasWvO1g43TA2yFEik9ZgtR3ajQFFtl2/IZ0Fe7JDJUS7bFlAJyHHLiPEFwySOjiK/nRJYcIuGGJJbl6FqQ/YH6liuM5q3CdgYc5S79dPyqcQOi0C7KBVF3pGGLeuShOyKSW54uwWr/yY20HhMKPG1NNXkAOhOCpp9VkaFtzZ+5De/I4uD4LTieAKwWah+8mv+RCrMBYOdrR2gmNzwdZ697Vr//+JxvGsBuhw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-creds
      namespace: udl
    type: Opaque
