apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-creds
    namespace: udl
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gaTHy1+r,iv:3PnFu3QAbUL6JpvcBiz2n+1V1R6H4apHPFgYGZ/uRmg=,tag:i5wxj6nyB7xgjdcDaz7VtQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:w04aFitXkCU=,iv:3zVH27tT0ujtReNnCOXxHMVMgNjrw5fQem9XxXd8+Tw=,tag:M+E2fSdv54Rcbo89t1PaJQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0T1h5eThTRUx0QW5OaTlY
            U1dMRGRqUUppMzVYOU8zYWlzdTYrdEpSNkNFClh3ZkpnSS94cjlpTmRLQ3kyOHpM
            SzhYa0JnWmk4aG04aUVTRVhNMjFZelkKLS0tIFhJbDYvVTJOOU9WYUdraFQraTB3
            S09UbWV1QldYY2djU2U1MmpLaWlNRUkKKyt7X6I7kXzLbaLpf6cOUVR44b70P2dF
            QITpvyeYcLJVmGBHvWvzX7Zs0CAUtr7lRsIdPvKWoccoavsN5ZOqRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:35:25Z"
    mac: ENC[AES256_GCM,data:gZPmpmBkZbLJMX3Nzu00PYTCtjZSAJH/cdRB3ficyEdw17G8clEEzlAKwORQ31ulahOwjcGdgvd/VjKvacKPB4Cy4lw4Uubx7BHCA1dpZ3TE3eSnqUgfZti5DPGnxE3ZNpLj15Vyt49YCNte1PJKrUgKxBH3CaBvBl0mxlhBHDY=,iv:FfKJRdZ+weiRG7H/S3kz2kovaUDq6tCWO+sWo6qO2pY=,tag:6BzGmlc/c3qnUvqyMMitvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
