apiVersion: v1
kind: Secret
metadata:
    name: steam-api
    namespace: udl
type: Opaque
stringData:
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:er2saEpm0Jpyd/FWHPDuu3xlGqore2LgdN4lBi+ia/4=,iv:+c3OtH1QGOvay1l6c9O1GGN+Q12+l66n2OyeGLT6hmY=,tag:7DJ+w22vP/benGhwv42T7g==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ2NZT0tlUWJmU2lZNm9U
            ME80eEtxVitlV25DcUxBN2FIa3dPdVRpWEdRCnp0VXBSa0xjd21xU3YyaFJSM0Y5
            Sm85aW5QQjVlVlRRQlpLdXNVdHhPNTQKLS0tIDdnSEZWMHlyM0MyRTFqODNJa1Z0
            MTVmdWkzOUpNZW92Ym8vRUJIRnloNXMK8OHWh5XW+ip2kVnk/9jRaSVoia2VHvGn
            bzT2p223eNZzXxytWavHrHYINhAgJLJl5OqNEcYAJ4gEdFSJC7RC4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:35:25Z"
    mac: ENC[AES256_GCM,data:kYjr2ZzZ6Eh+eBCJhg+pynIZzU3qB+rqI8ndbtAEhQJr9OavzrSAkHI8SB3qWIfXsMmHWstYiI873iCBEmly0+X9MXhacXcNHlsjoYbNg3FhfaboESMLduT6xulSbcehQjvvDqXQmEIjsX9wIZ/b53smEQlxAyP0TpREZIDSmWY=,iv:lO8e+VaezAF75fwsKOw9Uzq6jhLihInJo2M3w9ONaOg=,tag:WoNAwE4CwNWlcXo37ZpG5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
