---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: steam-api
  namespace: udl
spec:
  encryptedData:
    STEAM_WEB_API_KEY: AgATf41in8v08pU9fmyEGy1ZBjGz1+Urc8K+c0cmnLhv53ulXyoCyKnzqdcGqpRaJcA56DPkctrxwiJ2Bn+DLxUrzcmiBLi0tq5bihj9nVQW3oc9AzLCTDfp48LJmPkmJX92oSljrIw3oPRRMBuubc7S0V/V5j6WoIHQh+7BBgHDguQGE+wANydr7FE1H8snFORHNh56qjyYxqu2Mq52i4fDfmPxtJLC4+6IG7Js6Y5k58Jtqjky4fq5ko8V3NWlyAUHN15Do7t+WVIcqbAzDqGevrbVxiEtmM5IJr7Cf32TbwWcSqCadBY80X3tIkuye7Ff+qBKBhtqottQauL4I4AHlbvMxB/D8OXayexSTaIvAKLP7LSbHbLthIV4cj3C0NX9McodJZA7M9rhSRjK07ztqonsMS8CJR51/nhRSW00+u5TOVmsHdgBYwgJqUhXEtaEUdyD9QYozDaDrJaQYPfRL1j8F81u+faGbPGVSAgCiyDlBY4Abzc9duWR5OJ5RMJx+9K0DRMRnWbXSSJ+38ueOsTX+l6N8IRBJkYutAf/1CexeHp/YFLYzNsx5g+OwF0njUI7aNFYquy2pcxDphkZ6pKrUXPUkLG4CJked/jRAhQ0n57c+xj0gqd2KbEqoaVECCgoiKCg1InlLNaohMWpS3nTUV9QKeXhr5UJ43vHtgKzQ1HnX0fWcqHO0vZ1D8+nkqWKXzH70NzuBc/p6Ed5ivhI3skg1eYeXafkJ53kfA==
  template:
    metadata:
      creationTimestamp: null
      name: steam-api
      namespace: udl
    type: Opaque
