apiVersion: v1
kind: Secret
metadata:
    name: steam-api
    namespace: udl
type: Opaque
stringData:
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:fk56zS8iPLcWYX2x7mhR33FKEw+LaoHvmEA1hPGenkA=,iv:D2JYX3g4s7F9Wruk2m97+T5Cv3oIsc7H5EbWKRDSin4=,tag:24JZJlIM8TUdYdulNh7dyQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbTdtWVg3d2RvUWVXQzhq
            Yjc4d2gxc2ZpRkV4M2hjbEIrSkdsOVZrc1JzCnlwWUQ0WWpPa2hWajlJQjhEYnEy
            bEJHNk44OERhRElsRkNPblZ4OUF1YncKLS0tIGNROVA4d3owQmQ4YXphZWpQUUYz
            ZlFpZURwYWxGb3pSS205NDVvSUhFb2cKQoJDmRYko0uC3GKC0LY1gwIq1E6oEQYG
            4Bc0I8O5ouXsAqCxm3GFlSetlwxZZJfL2uYr2wEATcc6UcOYnXpc4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T21:30:40Z"
    mac: ENC[AES256_GCM,data:yqWWKN7+Hs82L2AOIBNycdoSiK9wrLi59diTTGtLRbZlvdeWO24G3Jd4lCHbhvT4M++O46g5P4pIxNVrbck23p3dUkbVtCxw+EwSJktcM6cmeMis1OPESQEafUS3Tlwkr0kVfAazfX4DGlOYtngY4rQK3E+SL6RU9Ajslt+R5iY=,iv:KeNo/1sQhgrLuYpUUdYMd3ZTZML0YBP1qxNanMGnc5o=,tag:ik1HP5pkKoamwG3YzyDsiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
