---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: steam-api
  namespace: udl
spec:
  encryptedData:
    STEAM_WEB_API_KEY: AgAc1CUxSm2pPg3QtagLPEeB6P6AvKY2NJnm6AI5q/9vNydd0HfW9BVv5Qu60ehLscjGLsen0oivLMHM+qTcJXrDMFSxucpOrDlkopnaI1tgyAaMCl64wmf+RBw1us0uso0QHFnOVD/5BQ74pHpMWkpfSjdI0gBdPso3Zv1QL+g20n85OYywaetJYHG5dUHesOABjZPfooAwzedZMky2MGMtS+0+uDk2yMqRi8FFE9N/qdVDMGwCXAPcbcxd9JNKT4RbxmqobZ5wrvkRZPuLCrPc3TECHrWjYSV3ak7cT0K/1IYCOMGo7TWi8YhpAQuY8vpCTtgubeUE45a1AlW4tC1Um8Lmux2TGqNL81RrWOp09+ujw90fbrTkMQ35gWROSktACEFGnu0XWouBCxJUAQhft6zWz4rVbPwj6pNDl2SpCzzuNGCgDvECc0pwOmzgtMAO4rGWzTAbjAlp85Ps+RyEEp5v1eV1XwZPqNZP3+CP3g8g3/3+64mvc5+GRnGGksOnQgO7V9sNTNRpoRzkd5gQbu+G+UCgZRaeEG7PRH45YehKm/GCTTNt528DPgHOaY4YklbHeKEyOdVTHPLcEMWVgmtDPXSkH8XSYxR6K4oQSesiq5AMJgAxTHTqy6MGONKWfuXV3TI7/4Cfao2JWcM4ciUDsKIF/SqyOrT9MKlikaAlD+WWpTGsiSz9axiIt3ExdEZqR0MQ18WC8RAmzAN7lBoSgSz5XntgECu5yntTtw==
  template:
    metadata:
      creationTimestamp: null
      name: steam-api
      namespace: udl
    type: Opaque
