---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: steam-api
  namespace: udl
spec:
  encryptedData:
    STEAM_WEB_API_KEY: AgAkBDdDDY9bf7WVzMQV1LfwmjOpPf3/UkPddCBZcWGw+JfD+znYdFrRCyq5/i2BEoWd49R8A5BnHVEb/RZmczdYi8bA1sS6ddCRSjMyz2yrrNFcCO6mp9FCmmWcSfRTH5hD6KYNOUiNqFnv63PWjxIgFeto6Q4ygZsjMxUiFMPZDjXbHf5sAaRbnUELdkCzfsf5VojN9+50mnqvNGdxWMd571r8qSzZ7q0961HWZKhmXosDtaIj9xKB0dISMLOKFN6boHqkWfs/HavCzJ6wOYJMLwzF9lvFvy5xifCYRJKeku5TnotpClp7rAhfDMyVZlIXdwsKwSYUp5gsSallHPX8gRLDWuIQJgS48cFB9387nQrj/7pBbOJouiJqGpT296SCKKwcMzvO3LzYe5dI3fH0nZV66bfBySrWGdWf2QwVMMFXrlFaYw8E7QpIQ1xBlUtYPYTyu+33PH4LJoQAbLr2FP0Z9oHVRacrm86RJbuWUfZ8M+k3f0/nx2YHU8pH7OMUjOyj1oUBHULzqRGJjSyOrcIi0/wrbDsTv2mhYMvBsmxGWNIgaICxF0W6PyYGL06TYtY8zyNp12l+IpPoZ3SZfMYxBrCv1kZZl7CNq8AdXkiOIrv44TAn1xaQraHD1zOugMPJ4Z0wWKD6KYOwO9sHn4n5niwew18E/w2tISBmYJ3JYJlA9wEhoRKyCpeg76nTt1Nq3KrafzV9OLq8Y3tGCZKZTIwBXVR66wXTznL/3Q==
  template:
    metadata:
      creationTimestamp: null
      name: steam-api
      namespace: udl
    type: Opaque
