apiVersion: v1
kind: Secret
metadata:
    name: steam-api
    namespace: udl
type: Opaque
stringData:
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:yi3sNvf1HHQNneYQV7/8MJTnN+PioVZSeEnaRNKy3r4=,iv:jRMjFUYqrPjktKjCtioCp6LIEUMjfqVMXfkvtsqg6v8=,tag:FfyLFSjgeKwcEFgR/muLdQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeEtxNXF0clFYb09JekpD
            UWs5dFZLamYzZnhReEZoMXlVUjFKNktVaXpvCjRMbmtyMWwyRUwyRUMzaExyR0I1
            akNnZDR5QkRrZm1Wdm1yRFFabytoczAKLS0tIElwOUs2S1NFdW1pM0tMbXVDTkdm
            MEgrRDMwYXYwVytzVUNHalFGRldKcEEKEXOzYIrlnut9zxUPA7C6kxohE34vlsjK
            ngIRuvJGv2MHH7AhYpbuvQIO3x278zBfxhLm5knFJvMs703mhm6vzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T19:16:22Z"
    mac: ENC[AES256_GCM,data:UMQaVu1xdT5UlS5Y0SfdgtI3h4so43gxwbTOyuCxnar0RBdFhROTvKAf06yo4Bir9dgp7PgLyKpOF3/RcxfkNIPhXZB2ck3cUR/wgb6ubk9c9b+JVotPPls8uHQ5Wo9pP/S15T3RLV7Yi7n4NCWAQSZxoMnux0Ue5U2PNl2DHlc=,iv:jRR9pjlXxFMaZj8vhlUUYhW3ZH797mnxs8OcmyuNMtk=,tag:/OoQHzGVZtfOCG3XdWRCBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
