apiVersion: v1
kind: Secret
metadata:
    name: webapp-secrets
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:aw3sUboCC9SMB5/zHcH68w==,iv:aZvoLKnCFRxpy9+UsGwtCmfgT1ivg4DUWv3XvuGvrTE=,tag:BDX/LlGyNg5IDgraZOUMFQ==,type:comment]
    ANALYSER_API_SECRET: ENC[AES256_GCM,data:sQV6D3Wdmu9jv5Q8pObPDY4Oo9rgmepnMA==,iv:k466z++7SepzWWjcx5b3v7Gp1+4D3xeL4AuaOpBhFHo=,tag:hXDLLY6lc3FSmHg7+sKNLQ==,type:str]
    #ENC[AES256_GCM,data:p9JPYmbVUFCANyd5nasJ7LWVwan51FY=,iv:YNiGeAJdTZqJS694iUGWq9P9gyyNGGWr8WzxEY+spFs=,tag:eRXYiEX7KiWZ3k0P5vUMHw==,type:comment]
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:qsvGAUBP7LnMo/ToaJNpwJcBVAVq3Kj9fUOkeHojrXo=,iv:8WfoeQP1leQXCjByBBwcB7cOufC3xK1Qn6rwpcqQEl8=,tag:Z1NltYlWZW5oU/o3VA7ijg==,type:str]
    STEAM_AUTH_SECRET: ENC[AES256_GCM,data:wThNsXjc+sxzlKVrKpfMLcRuZYlxVOiJu6PCzhMdrXyA1NzRAFse,iv:dajjEIlNMFujxOOl+ocUV4HHB2YSpXEjdms5C9wHosQ=,tag:RGG+3fSPu5xawW87t0ao6A==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V3Yva3o1T1Jyc3dqQ1Ay
            c2VpcnVDU2l4aW1MSW45VkJESVdqb3Y3QjNZCnZqTjMxeEtxY3cwaGlyanBzSEx3
            YUVCTFBtOUh5QWhtd3pCamdqVkcyZEkKLS0tIHdEN296NTVsUTJYZEp3U3IyVU9h
            Nit5OCtSSW1Zc2hwZEY0d0FrRkIzTHcKWtVMGEvEjcZyvuAoyFrXjP/0miP5x65w
            gd1vsS1k4HXJPrdNECXWW0wLFzw139tQVffJH49+Y/pe2TsfkD74uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:59:57Z"
    mac: ENC[AES256_GCM,data:c75ajR1Sw1+9Xk/x53/qGZLxHhNvD8+zqK9/ExwXPnLq+E87gp8k1QcH0Q4sb1iIH2YP/cqcUVseS3fo/cSQaiJJTwCTXJt0jHTC6HJnT8vu2L4pfrCx4GxirEqhOQ3yk8LzqprUdvGw1Ru8jlmeU1qV4+ZdJhokvQKUl1273VE=,iv:wTo3vgmbYZlxFL4P2gMXnyP7LUmjYs8dtxYv4vJtkWY=,tag:qAqfKNMh0h0m4EYvrNajaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
