apiVersion: v1
kind: Secret
metadata:
    name: webapp-secrets
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Bulak85qeoaJaR9PiXfiEQ==,iv:PL8cceWrspha5RcBdApYkyufbl+8NhgNavq01pViirY=,tag:qOQOFHdoKk0G0VwcPWLHJQ==,type:comment]
    ANALYSER_API_SECRET: ENC[AES256_GCM,data:Le015SdwUMr1bAwP5RU1j5XCXZOStE02ow==,iv:fpXRrTf/R0X2EHST27pAMgAgBzXjBZYeuYw8xHMO+OE=,tag:SiDGMLdQgPnZDq1xVhU+Og==,type:str]
    #ENC[AES256_GCM,data:uaNAQzpc8RCbpGnU3qYQ+RX+bclqfe4=,iv:T9daZs+195DpUT8KwINuRp83nPzDbvEO5K2o6ZYKXBM=,tag:GVfh636ihe3r49jMsWtTlw==,type:comment]
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:lSrcC4Gr/MHuYnzfXxJWBXCsFPuSfitw1aLFH6Fvhx4=,iv:zBcawO2rN/tTHwEVu/4aYOV0mseVDkngZxH8joKtL7M=,tag:MwKLKABztzQdIOvN6tpSnQ==,type:str]
    STEAM_AUTH_SECRET: ENC[AES256_GCM,data:yUkq/8+Enw0dpCuY6qcneAbOaIh/Of6lsVjKcTJVp0Uz2cWZpzIB,iv:lnhQpFty9h/LXdN6e6a76Af0X2T/xbzk8Bf/gxilP+4=,tag:GivVJFMLV9cdyN8J9xIJYw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaU9YQXVFVVZ0ZHlWR255
            UVFnY0Y3WUZxcGFLTmhRU3NzOGZqTlE2bkZjClIyZDMvbzJab1FyZ3kwdlpvSERO
            UXpuenE4czRRMFp6TXR6V1pNVFNqVTAKLS0tIEVOM21hdkF6UVJ1Yi82ZXQyZUU4
            bEJFRTUzcm5sd2ltRk1zcER3a05SM2sKjoAT7ipiYhH8A5VHvKm3isVEsuoUGQ6k
            rEXkxxWlm4DXKkPcToCSRvrB2WwxnCe7mhsm81q0yMgho7IN28CnNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:06:37Z"
    mac: ENC[AES256_GCM,data:2D819am70NOL+FySaLXoBJbwdq4pv2vZrJ+VBe/qwHV2RQs/V/8zzJpsC4Rm+bmLlNyCUfbg65Axw4/RJbL7NgrXLtXRBG1R12FkOsHgC1mAGYP/KMDnxoUA6dvGKOzGgbYrl5quP5DhbC28ZtHS1KeCvqGGnnbds9rcC6t7zeo=,iv:HY27JQcE/+naklTsjOG7v3wtvGKcBopJ0oGvIbgHRtM=,tag:I8aG3KEdNOhC7J7tlbhn1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
