apiVersion: v1
kind: Secret
metadata:
    name: webapp-secrets
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:13vc6FOsMyKEnrP581YbiQ==,iv:iTTB1rNClg93vMZ8LkOyNGJsnlP5yIYQNI+BCObI0/w=,tag:k9NpB2ZuuTaXsMdwpeuqsw==,type:comment]
    ANALYSER_API_SECRET: ENC[AES256_GCM,data:q+HnGaytwNzXG+3TsAj1i1bxQ0NgB3clug==,iv:0x8bCFshK61tGJ7+GtxbrBJC2j/t+QXW0P6Rac87dDw=,tag:vmY+Ld65rq7ERUwT4Crkow==,type:str]
    #ENC[AES256_GCM,data:geu/X9K6jDGDIKxgUgtd+K8oO8WF5gU=,iv:SKRNV8DVxEJ/c688byp8JWAOsgLZ4nogWfdkskagA4c=,tag:jHJ4jp+qE/7ndb59purNWA==,type:comment]
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:/kgL6WRCduGq+QEi8Exkian/T5/BOVv/8JPrutq04s8=,iv:B+i/C4ozrKM5MPkWEyagq8GJXYM8q/3YCVhSvyrC/Us=,tag:+9/DEroYfhH5ZJbh59Q4VA==,type:str]
    STEAM_AUTH_SECRET: ENC[AES256_GCM,data:mEXTr2YNIFli4HDkxuwiRZJU4MaM+HEpmf0SGm/RKwilapY926Hv,iv:HkYXIWnSJR8eHXrp/PVhzJCyn2l39eRLZJVfdm3p56g=,tag:Qf8d+dK7c+qZevWf6h5VFg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTkRmb1VVME84VzMxZ3NK
            ZFVDUkpwZ2xDRi9JQ3hydkJHRW9zVG0rYnc4ClYycElQTlBDTks4Y1B0ZmpUdGV6
            M0JHajBadVNnanJQYXRMUmkrd0ZhdTgKLS0tIDZUWlh3dmxuRHRFalJET2dzaUs0
            NHBid09YaGN2U0t5YjdrRVM4Uks1MUkKf4CVAw1icx05Zlvzi6xpWYZvc12ulM5P
            KBou7KxDlMxwe0lDsQu5Q5cOK5a9eB9/MTRoFJJ2Tk2fV8ezthQQVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:39:03Z"
    mac: ENC[AES256_GCM,data:iuyCSVql+fI177o8nrXCcYy5L/UoIYNuPu380dP6QVMiJv3YbGjKxPc5W9PyEPWERsGFXuuyf7otTDILq6NgA1xYfhEFBwcWUE7NVmDd8BbNch/rbsfvc7+1maqwdjmRxw6nf9611E5i2H+v3y+3BnX3GWkvz2gY1njxLOvQ9kU=,iv:4ITzE6YYi6CTj32S6zQAogRyM51MR0K6Sm2D8i3aml8=,tag:SHPC+kE4bjaEqE2cK3puQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
