apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: api-secrets
    namespace: udl
stringData:
    SECRET_PASSWORD: ENC[AES256_GCM,data:HUUdlWNS4LpE5UmP2kKwn724h0vj01c3YeedhA==,iv:BeeAvjISRYPtmiJ+Oo+LhPyH90VXQolyrdJiM9+sc/c=,tag:gByspxJSpmtwFa3F6+mNQg==,type:str]
    SECRET_DEMO_PASSWORD: ENC[AES256_GCM,data:AOILu5E+96GCWjGsNqLmtK99QTV8aoKA4eY8/Y+7BXF2oqspHreg,iv:tzirJd8DeHDl0SfOO6nKLWIl1b7Q6DxGOlEAw+p8bWg=,tag:XPxD6PzQ1hdoZaT5Pj5e0w==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:L/Nhb2T4SZDHGJOz8SgZx7B73YQ=,iv:JNJmLaj2tKpLBXMYEHq1NvBHz58Z26e5D8rGVx/jVHc=,tag:8XPpgKV1zq0cBqQWdiWJEQ==,type:str]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:j4gcgaOR,iv:su4G6RnL+AnRivOaJRWWO+nZq8b/DG2bm0bxxeoGtIE=,tag:dmtzFR6np0jXJS8PMA2czA==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8RIUjB457pXfWnoI1km17lKCAAeW9yHbj+7AMYGiyLlMs3hft+if,iv:6oZrPysNOp0KVb89X0RMfh5WeBYMF03slPlBIfkpF+g=,tag:VXJKCEFNTor6bo/Q3XK3Jg==,type:str]
    MINIO_USE_SSL: ENC[AES256_GCM,data:EIT1pEQ=,iv:jekw25SdWhYfhMg+LRl0YLn9SsmR+avS4wyVcf4ohwg=,tag:ElT3mOvM8NdkqtKzNp3aVA==,type:bool]
    MINIO_BUCKET_NAME: ENC[AES256_GCM,data:TMXlIKxOz/b4,iv:y0sep6hTrUFs9vZJrbc19qZ/uxWSIxtamw3ZPT7k6gI=,tag:MJRdQAlLguTz58pwfm02Mg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSXNpbWNuODlzOFRWY3ly
            SitiNkYyb2RWZGtYVXFqNk9KNEhRSGFjU0FVClJ3S3RyZm90dDhjWTMycGphY3py
            Q3NQWk9sVnZHMzRKbVhBVFdZc3BUUlEKLS0tIHF0Y2xKcENQTDdBdW5ubDUyWlBW
            bGNESURSeWlZUEhTbzVleGdlRjdsS2sKJ1uSQK/SQ/ONcHStH+8RfqyScmXcH06e
            LKfVS92cRAJxnduWLN7Z9tGswvPAtt3e8joMyIReJ0/s1MFIDG3ztg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:56:35Z"
    mac: ENC[AES256_GCM,data:898QdRfvGQMgtXO/7tVLoigGxcQifjl/WBfwqnqpjnNmWcchA91TBArWz75ZvaJmudXpkpR+hsgMgFLB0ecmNX3m6XWacWpPG+wAShGuAhmdQbxCeSKuFeQtATIISiGno0oqPp++sexyOtKSCMRn/tXRpU2GeEXNDUxgt/4shT8=,iv:h9abe3iA+pT5ZHvP5BOUJ4J/inOkxDxjJsNjjmz7l+E=,tag:OzlvaQHWfL5JpkzbM8wdIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
