apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: api-secrets
    namespace: udl
stringData:
    SECRET_PASSWORD: ENC[AES256_GCM,data:pl3clE5iLfmZwLC+R+nr/0p4VecCuPzJeaV7tA==,iv:E5ZcVn1vt8udOaEQG1AuC4Q0UjZa/E+FJiWTM2pyCf0=,tag:FdEF4iXMEHlEfVEDfbbX9A==,type:str]
    SECRET_DEMO_PASSWORD: ENC[AES256_GCM,data:6ucdDDXEcgdc330HNpMwK/p0bkKa1DQGlL+Dt8iY499VwXuu5cy/,iv:t5fOjV+nyEezB3zO1dyca3QcX27Gwmq/Bv4mxCvjqKE=,tag:Sd78uGkP5BvPM6nkhiN6tg==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:nZMJiw+hx6fB0w/PFT4r2Y/r6uM=,iv:hB/Eq6NjsHy7sIGKlktAMb13FEjmKg/NuExHg2eduQo=,tag:kQtk3uUjmNk5d2n8FHfEsg==,type:str]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:KhjDQgw4,iv:isNwF/GW1sxBYw9Invv4LuKmeMSCPSsyo7BLKG6YJDk=,tag:xA3xVLmbmxLq+FOroJZsrw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:C/JPdttv9CH8eBGG16mesVW4SJd6ePQSwdwHgBHL7pt/w8lNmSUY,iv:NojPzRYRV+NcG8GkkvKYxZ68DsO7WInb+sRcPFob0Dg=,tag:zMMYudPGmPHBBGQTWvkyHg==,type:str]
    MINIO_USE_SSL: ENC[AES256_GCM,data:NhiS70w=,iv:Nv3TPLBXXe/XwYudN90y2k79EnmVhrBpe4lBtu/tgyw=,tag:sHuFWt+ZZMy/To/5Umkfcg==,type:bool]
    MINIO_BUCKET_NAME: ENC[AES256_GCM,data:130YeufZ7fyR,iv:nadk2YDVL2C0B7LZ0R/tPmtHnIhkikvZ49HUvtSYOgE=,tag:O7RFn68gxoymQmoj+3DU8w==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbGFVbVBCekRmd1ZaR3pE
            TFRTZXhoSkRmV2xzZkVQZUd2L085ZHYrWTBNCkhWUUdMYURvRU5tK0g0Wk10Nkpl
            anFONStlaFovMHE3cU1ETUw0cGxiVWcKLS0tIEI1NUNiR0NhK3Nad281QkV6TGVk
            VkFUZ3psUmh1TElNeThua1NreTBjajQKeg/81dBoWb69k34U42Phose7hbBW2erQ
            MCGWSQl39r9RNFmo6RF8BBKdo5TpR6aAQneRvd2uw7y8oTAg2yeExg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:39:03Z"
    mac: ENC[AES256_GCM,data:mGaXDG/rmzdKjmwzkrpbaprhcF0pX4bvH6OhM+dKZxD2dS3f7rFbCJ/jXSe7LN8r9pgGxLSgPV7K4Wa+tTmbYsuUCUHp7FhHSobqmyIxh45GltFVsdpZl06dDc4/qCXpsJbsM0lDsxbmTNBZ8z00je4lenmrsZCdoVFXysasmQM=,iv:mAXqaUcYpcMgcSAojRoGrk/WeGPfgzC8iIOzxAEWMWw=,tag:uJ/lF9UndtsWWJaTE8uUgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
