---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: udl
spec:
  encryptedData:
    SECRET_PASSWORD: AgArpWw3UH/lQExdhOhhM9tFe0+T/KT2P2ENLfW/sUs6ZyG6taBuT8emodiT0xGLOD+x+hugx0BmJ34gkpqn0naBcxD82vx+uK+JM4Bimnw96dQyf2c3Ba6jrE2C9BF2y5Ibg8hq1mEvnpXLLeRmYAYp4/vVbhMHSjHPBbMeURwUwuf3V5wbybQEl4zzSsNHcGpCTYIU7QbT2gw3SHDftkNQMr62VaN5gFnoF5To3O34rkFfzdXtjwu2uZsDw9b3aKCxWKsNIX7rsxsDyE3RffmGw7LLptzuX+RcWGADRI6UEnKsNxfkkg4pJA9PMYjc9hTRTQx5P7rwVlPIdki/AhAnD4ZDbJvS7fxI5YlbKUpqO4GLMl5W9MclGFLBLT9Dn+8f3m32S/ymsWJLSCpfCww/tiFKxUKIGqD2ZAsTb5LY7a1VLQyW7eVoB+OgcW+uTZt0RTVL1RGEolIXG4AGYucuVVkTEyXXMWQUGTAqwXs0PaLnlAOuSbXdHQKprFdlQjuRBwGIsa7+J4F5YFGeELI1i/GP/iW1C2laX5u7iX/h6iC1RvYRwa/fseirdKxDkY7DaU5U1G0ZoCw2OxLnMXpQwM3i7QvZ0uqnyQgIfMZOvu10HP5IAaiJ2s81zgYrOS74/dXdSwLfLtcVCepIXO0Aewisn0147DyrouVuauzeyABwgGZ+Q8Z60PHvqrcZ8YkS674St92CMLSddZre56fTDGaiAa9tGgl4U3rZ
  template:
    metadata:
      creationTimestamp: null
      name: api-secrets
      namespace: udl
    type: Opaque
