---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: udl
spec:
  encryptedData:
    SECRET_PASSWORD: AgCDVhBhPkrPunOtUaPXaCcO5iWJzrHBXgygZM1LdnjWMfPfr44sYLLxUl1ZZt3Pg6Q0u1X8Aa+EGny1uqeNH0YFfckgcVmr1+bDOi1n+0UomSqc8dZtKW6kYGCQdnWhSjACsEC+kySArfwAMzXlyO6DgjyuWrgQW2cu+YYMIJ2QI2pad++WjR4RU/dAsMj/SpVWYnWbVD+ZxFhpp3NUwok8VL/QxUPmnNMqdEXhSa70AEnchctwEbeFBFoqA/CcrmzD+SKNKArOUfaG4WcVfB/WFfmkDt31NFHJRNchRei2nDMz5SJ5l7nGWzVOqu9i1mrBI16pzCm5//oLywSW2Pa4VekoQLjpRfVziYkA67nvDLndc5c6KCnudpKBgffHeo9y1qlw5pMt9wmA6I8uVVSxG3e4e4vKhBvAvMWBeVLnw3mcDY4JRQNm3uV5lgmIIRfPtJByv28XuUlci6dmfSqz2zn7EuSL2bAwoiYAkQNi6wjJVz0JaDcy4E1HbblOGcz5vI54aL7kPnTiMeJM9g7DYPhBo0c/A6+wcwo7c4+liEdAvxv3zL7WSQDWlCH0rt7/o2qAbYz8rOCC/ElWoNJiH1APpFuvrXcIMjIaM4t19a8mS3CvHzmQnX4Xmzw1Wtf2FwrvEA0hdEHUMD1G/l5tJC3HrNU99SxmtRui4MN/sWRIMUJr4tqXIrV4YBN/I5EAIGgcCpHxQSb8fwEmBx0L6ApLPYtu2akYxY42
  template:
    metadata:
      creationTimestamp: null
      name: api-secrets
      namespace: udl
    type: Opaque
