apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: api-secrets
    namespace: udl
stringData:
    SECRET_PASSWORD: ENC[AES256_GCM,data:FK06M4QbYyQJiMYJOSBFx/hOVPVguTUwVZJr8Q==,iv:ipaWOz05ucDrQ8mOFqgsSA2X3sxXXy8xMpRV9UNpMgY=,tag:5jyp/CJcxS991OBynrMu5A==,type:str]
    SECRET_DEMO_PASSWORD: ENC[AES256_GCM,data:+1K5DDZyRm48iDVZ44iVyeIfbX++19heOp+q6BkGFUATPmOeN4FK,iv:b2Fc6nSfSxADEYdbiPZYV/fzssz7SQTnHogiLxpFZMc=,tag:V5QnFJMJ3i1CxtFMyXWMEQ==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:k0mk2IEj9xqdxF9SVz7gR35tfGQ=,iv:So6xFnYNEVDSg03mU676Zj2llYBG85HUwm0cW9XaWFM=,tag:timilqCtJTUGS03mqBUynA==,type:str]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:SIuDYO2w,iv:cMCs6Zx4MVmnm+jDzxS2cdxfBMUZWVslPCaQ3kVJ5vU=,tag:3egda5T0uEYXP8BzuG0p9g==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AXYcgnsqXRemO4t+7rc1ghTIqZVhY4rswYfOxfdhYaKy1fXzPZQL,iv:vRRlQ/q69V0SZOoGfbrAkLtiftcy+uD0HYb9/QOV8ag=,tag:yLkhkC7v90W+5yFXO3kuZg==,type:str]
    MINIO_USE_SSL: ENC[AES256_GCM,data:DsN/d54=,iv:XKXb8jDG4BIHcZK4KOZPwbAQDIvvJVRfvFVmVnXrfyE=,tag:Jlk98L+wQmGkuNBDXjX0KA==,type:bool]
    MINIO_BUCKET_NAME: ENC[AES256_GCM,data:hnDZ+ullDxwN,iv:BzQAerVW9b3ls/P+24nHDcjE3kiomQGobs+TJ/Z3fL0=,tag:IyXY3AxI8ktX9giMfyAFsg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMXB1S0tLNWpaazJXRW5x
            S08zajFsaGFXeU5wV0dMY0N3djBMU2pGTFFBCkxhSDlPVWlTZlE3cmt3eHpFcnFJ
            L2VEZHpwR0dHV3VTWHhjY010RnRTUW8KLS0tIHAwVWVWY2JHeTIvRnYvN3lMRmRm
            UGxXVkJlMU9SMnZmSE9YTTdVUGNLNjAKpusythg+qHnw8RSTlMwaymgt+iTu96mX
            A90KRHKQA7xYsfn0X2a0H2SH6DTK+2cjAUGWJNnFlF9nfZ2Oqa07AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:35:24Z"
    mac: ENC[AES256_GCM,data:8rddJsg/dee1Tg3mxiLBhLSFOxYuxKqVK4I75PVC+z5bUFt+3YtQXiDmBS5kLDoyY/Jbzid4Zg5oaYZ23FecDLUwor2+ASr15J3vZPgkg0w/ciEUKRvzWgufhrd7fk1kgiqrRngSPkRKi1mwZ2aJAMrBoFM21h41djuxMYojnP4=,iv:MdTkBYFek4dnqer6x9ImSb85k8MQYhysYFpmrWGdoTg=,tag:B0oSPtzmy9hIhOWV+bGE9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
