---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: udl
spec:
  encryptedData:
    SECRET_PASSWORD: AgCPo6iXAanwWIDI4fh5Z0jymk1tsOoBPXDQP4a7d1ChT+Dl0myQ6cFjtb1J4lmdgs21GUTwXyr+M6idyIU3BDSSODwIFjDaloS4t1HFpVCcWEOU2FA1owo49ouF/qy2SmqvfvG27DJucQVacNmTTWagNAUKSNnPIjaR/9Ud+EJW0dXRPghLqdLVavB48G6aXiNhpuL/7WxGu29I0RflxJAKrhvjJUg7KokkmbBPln9KMlhVkD6cwpDCfsI2Is4I8+NdpzpRuOxdQprK51HQDwW1mrS3N9wx7uqFHO5dktspqOT5uivz4Hon+7lNGEFOGTS2clSeuMguh+SxUAH1xVN1EnD/+sRbH7k2g2YvAEg/oNWm79hVFyj81NokykYKS1hOyBbIBurd07jEdvu1eo6f4CkdC/hXyd8XnoF4ID6eQRiPVR1YTUFMsQJHPeDW9+V3C1EknBrW73fA7oLbOZfpEJstRRNTgautRHdZk6TXJFMc7i9X5jlYou9LYXe7YiaW+493vuFnA1QFu639vNnbhCbNlq0Dn/r2dP+O8FFQtpfOYUXKJ1/sKVhZQolCpIW83ImVbKvyEE1xFT/vy6Vrj84SieE6IvqXBZz7sF1qrMh6KhIPtLJWyyWbeKkAiu1+CRlyUr85ASRdzmHxs5yz22GM/9+ZWSMz8SvNGQQP/oZ/wmUpiTLLedzv13HXEk7kQ09gX5AVGHet92A43m2BPqxIc88s5GcTqhwv
  template:
    metadata:
      creationTimestamp: null
      name: api-secrets
      namespace: udl
    type: Opaque
