apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: udl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/udl-tf/united-api:build-14 # {"$imagepolicy": "flux-system:api-udl-build-number"}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DB_HOST
          value: "postgres.citadel.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_PASSWORD
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: SECRET_PASSWORD
        - name: SECRET_DEMO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: SECRET_DEMO_PASSWORD
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: MINIO_ENDPOINT
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: MINIO_SECRET_ACCESS_KEY
        - name: MINIO_USE_SSL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: MINIO_USE_SSL
        - name: MINIO_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: MINIO_BUCKET_NAME
        - name: DB_NAME
          value: "citadel_prod"
        - name: DEMO_PATH
          value: "/tf/udl/tf/demos"
        - name: ENVIRONMENT
          value: "production"
        - name: DEBUG
          value: "false"
        volumeMounts:
        - name: demo-volume
          mountPath: /tf/udl/tf/demos
      volumes:
      - name: demo-volume
        hostPath:
          path: /tf/udl/tf/demos
          type: Directory