apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:q8uY2N5V7O6o6D8q3vVFoceo4e0pp6U=,iv:I4KzP5yLfewE8ixcobhRDRjaussu1K2a286VzaINyUU=,tag:v/F+pJKJkt8KBhZpvlXJRQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTXpQY0xFdTJQdXBtSVg4
            RW1OVkNPTTFHVXBZYmJIUzJPOVRCRUhHQTBzCmV4aDFXL1pRaDFvNUN4S0dxWjN6
            NnRUTktWeGVBZ1AyRHZEZHhpeFRZa2sKLS0tIDBYTWtzYlc4SHlXNGRuS0IwVU9y
            UkxpUko4NERDK3hkbEIyeDJzeSsreWcK05MNkDtRDQBiXuyq0G2XzUulCgIvXYN+
            9+Ml4vH9a3+wPAop39g+H5Oqk9H3hlz5QcSWQFOUdobAxkMghYjW+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T22:23:27Z"
    mac: ENC[AES256_GCM,data:6zPKItGEritjRYw8x7Ky1x5+ibWjRcSS4TygKTk5JtZiAuGu7oNpX7yIPDweefd9SKloSF2qicaIU2MJANjCjfq112Kl69EUggUEO3AOGqg7pijswQVbJ8PFqhjETQ4uk584Rb8PPvTLsmBMoZEp26+Vuab4FGVBgp26kRtM1yo=,iv:BGxNRvoZLpY6ufEYlWdYdIHaZLg85JrXBiduYZrlwOk=,tag:lY0Ch/SfmtV7i+tULiO9Hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
