apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:p9058zbAyX1N18eyvyWMrrGVVUWhL2M=,iv:B15l1lkoEDJt/65I0U7AguLFrbN9hWdQSPyldHvYgh4=,tag:SZYija8s4MvDP5TeOluEww==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM3BuZ1ZaQUVYclN3Vm5s
            K0Q2T09pKzRvT0pyN2YzaHJCN0FWeHl0OVZNCkQrenRaQWc2QUlZTGI0dEFrR2VY
            SWZVVEh6MDZoVW5BQ3p3RkIwS1Rwb28KLS0tIEZLV1RBRjFCVzNWNEtDemxWN1Fx
            ZTVCTzBqVUtNWGV1SzZxaThJTDIwVzQKqRYUBn5IN4yBEJFxqbIcdTph2uFNDXbA
            cmxgRQdhjA8qBEZVFJ44x6h4KcnX+WJL3pnhvHFZ7Z+YuwDhtQFebA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:06:38Z"
    mac: ENC[AES256_GCM,data:JNBMqYH8uU4prICeaJ8lPl1wWtUoRKknopBkkORzTtO8tM1Kn72lkt78wV/RYkzgtcY2dCxokd0yBStJaXXPbiJq1hXNtT/rVnc3Udr7Zr0odt5PYzxUSOPh4fERfm7JeCLAgeP47fcz1F3s8G7RjMjhIgrCmiLxmK+1iR79f/Y=,iv:Im134maUkiOzTIpt31Afnx6rzNHIXLpBSVDVEi9C+QM=,tag:RBVlbjRkfCCRIcyyxqlwbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
