apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:b9Q9H1u5wDn/VEwdVtawNP2Seq0Q1YI=,iv:rwejTTYZ6f5z1BDPYaXqQvixau8RqahePvF5UrCri4w=,tag:WLdibZ+ww/d7m2RPt05ReQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TS80Y3VHK1Y1OW1zbTBC
            RnM4dVNhd3A2aDF4aUM2aVNVS2x2dG1OclRjCi9lMERVaHkvdTJaSXp2NFdwSjZT
            Q1hDWVNhWGtNN0N2RHpzUzhNSEYwdTQKLS0tIFJBZFVNbForOEdKV2JXMG5hNHdF
            ZVprU0srWlpCSm5PM0tvVHl4TmgxZFEK7zaEY3PBQFi7C3whFoRjqJoFy5vEd+VL
            JVejp0XYkfxNg8JppNWl8/qE/Md+O6zw6pi97mrL4pgOqEMAZIegdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:35:25Z"
    mac: ENC[AES256_GCM,data:LOPGBYayJMucwu2W7raU/OVpSG3+Fj5/Rqm8Eeiios5GtEHMZJvvb/u07oKkRdZjtjveE++rKRZkHsjM6r3kzyq5hG1ml32IVDi7hDOz7iBStOvSlN9u88j+UWJ+8EQvlRx/JrCBnN0zgaGgrOQYlCwfsiXqowLLtEFbKgYsa5E=,iv:kTuYvoBaHtIco2pTKoltt8RZKlug/R+cGDItRf36kBc=,tag:GP65dLNSmAQPKMJGEUi3/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
