---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgC4nPq3lyYIBsY8YHKpD3m5zgZqxc2efBqZD6EkF+4zPuXn3HLAyV84LJq24xnd1fe4LcM3uJt3O8GzHYI89Xh6SyRgXQdXnHJLaLDJ9c9Vx1S7ZIZ9/UoMIGYDg2P1lvPv/iKGHbNuKHJghaw7o/2kEyl0a8USt4CaVeP6mzenilG475dzklDRr2oB711Ng53C4E94eg+u+EbVKD80gJl7V/GhTICqLvRb/54XFy7+BGzHLwXisYKkQ1suBoc28TzhktCbm38qgh9ade8Zyyqa1GVVZo+rsqL/HaY0L5nVmLB8uoXz2SLSLANHflsvzz6dmgCw10cfyBVhImxKpkS4NX0p62KjgMDDRHGEVOBxM2IrwAH5qjBFbHF9PqcsoscpUOGEua1fFKPbfQeEe8J3jFPPSw4DQOOrpSPP7qeKibGEvEjtJ1PeLEwz44Ix3/TN/4axWOtWCgmKxLSSx5K1pwKeSpd2QMS+MBzmjpQgg256vSM3kxcCOVTmKd+8VFVDV2Tjy4YFqnkyFvCbEpwgKuHCxRGrTKZrpqcuYJCcTTnztI6IzkO3DXCJjRACuMwX+pe9nIJgRO/h1c2hOPYm/t36pNL5QT3/1YmMPyWUaMiqmaWLMH6J8OsbU2Kvy0YmL1DEiS3pOpdYj3v560yHkuAXZu1j7AabJjf7oY0UJo9wLie2dzbNCsNPOr5PaffMouDayJ4OiCznJnXst60Bcb4lZN7BNQ==
  template:
    metadata:
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
