---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgAAZITXDhq+XzFXPM1LRbcsOYKKuBzT8kMNr6cSYdIAuH3m6V48STx8Mz4VNRxCjZMn4nO9q78J6OKAUjQ4Ju4SoDeBy2JkFm4sjdRWAHOQkxEZBaM/23iaE0SjEE09WwOhrlCXsHIJeICKbCHwCOpHqXuheweLnkNe3OKmFRYWFmvz3UE2SH3YvsNY4b3mutFNYFkGhjn4YIrDqSWJn6QeJkbzFj/jcDlns2etn1rxSWBEJwX+UjxCyvRJNYAhn4HK6kyyUr6rqtdgKi9S2yaIt0UZYAHPUxlNN2TVXGuhnLTJ1whfymEbcd+AEnAYGdSpC3goDPskVT/ltT0qT4ArGE2aNafg+HFSGzF/AVDQ+/bkIA6/++kUim4yVgj83vf4Y/DkvJPIc2XxFVQF8d/FLOdtWlQf/q7lKqTb1aIxk7qGsiPriVbEgkGZ7vmgyB3k3ZIed+Npi/HSAgO3m7Bp1TiIb2/nYEcHvvQyYHiE1sbHjow9Rb/v7WZ8wW58IXyiJz4UfOwlhw6xV25J6ubLVpQPBc41pzjTjbKZUYmjfp+43PL4Zhnfc9OAxCvAMPR5Q+gwp5snul03+0ftre9k9bHk19GeI32sgMHibQhpMoPU5skqm4YrQmxCFa1VOUR7Zyq9Jfs89YKV9vEz80eN6uz7vhgZHOF9WOClRXVhbuMJXRcOCzv3llHMe8Lgpc8oCC+KIpc1M1Ey5F9ZWMU4G27QpLDvlw==
  template:
    metadata:
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
