---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgB33pTynVlFuKwxhMmiI962u/3Z1E7iK0AI7s4Not2bWb2lmtnS94Deurqr6eQx7MBHaKz7CcAsoc8IaB+r54gPqM2+bP0eyQ9rZxO4VnpTvAITOUT9ypWEitFkevpKT0rZ/vxva2xgVC7uvnJ0uucxe2VJ+1FaJNAMIMXnxjsjWlSeqDODHiBSOxJTgD9+A4l344VugPnF3YDMDbkgMglNU2dP2nVKZY2lo6/r9d/3mHDGcPljezWfG++hghqbb7gm176UgRSB2+01nzL6hKeWEBn+bxtfKWT4L5Nyld6mIuA8+UWMTN8dbuAigYs/OvzCLo3wFWDvXaqvbGVY4rqaqgcIOCwB6fuIOY1nNTFTzWVvKi6mJyDcuxt+pFm1wsJuFTA8fmg7wHMMgUb233SG4klrXK19OjavEWC0IcnhB7Rr2BDT5rFRBSds/tebDb1wMY03fjBFlxpwhNjYJP6IBvCewVs8ZtUw0qR7Pbtz3Spzt02vq6WdRCnZhIhe5XkSaBQTaPfBjgY9PAefX4tig9k5ZIr4BvLTnCQoK6sxyxK9AVlKCyO6iiMgrTAch9Z3bczgOhu+NM6uKniOOIziUStZcir9gR2+ssgWCWfK9XKXxhyn8SNXh6O8L6vRNDyMDR3PRFknqu5FT6NDcuYNeHsjQhXTlwmDH5fvszrjED4F8IpWrs6kpng35jzAMovHutADvd5vzsZPUUy2rQREgCKjJZDEaw==
  template:
    metadata:
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
