apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: udl-stats
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:dDgGi8F5948KwP7f/Ws8BDjtc/VXw8XzkDuo8EM+tAAqWLea+FnelSI0AHzKufSVtwS5uuS5lOe9eypsMXfD0if8DCTzOxdNLCtjh9xYHn+5,iv:V2N1tx2nzD3rk+S0NHRSyDTnchDG60v7Q37JYY1FyXI=,tag:zfqrZgCrStkqipKCBddoDw==,type:str]
    TFDB_API_SECRET: ENC[AES256_GCM,data:wxvk+ZkPtKGXBumewUhFQyv+q/JEe549ag==,iv:LqDwijEu89G2PRnKyPpZ9spBPbj8hIP81pPPPlulvo8=,tag:gSQ4J09Az3CH0b892e9okA==,type:str]
    TFDB_API_SECRETS: ""
    TFDB_MAX_BODY_BYTES: ENC[AES256_GCM,data:Ld+Z8/i8Tw==,iv:JuafOFxwTAYk06QYSz04feclvIHo/xzOUM4j4S7cREA=,tag:agpp6dLz6KpThhl8Bv95LQ==,type:str]
    TFDB_LOG_SECRET: ENC[AES256_GCM,data:fhXxmKrsBfuqi3lpg33vkGnSn6+dNVnplQ==,iv:pqbrDqEhMk185lLcjgrvorVRe7tFc3rV4gjpAumzrbY=,tag:OKH9P7yoT8duYVfcGFYNEA==,type:str]
    TFDB_UDP_PORT: ENC[AES256_GCM,data:daVOwRs=,iv:q80Ga+Up4sVJUAxniMl0i3Oak9CvhZYR6jFPy/QyZzQ=,tag:pczHJWsUz0vzzxCqwPtUgw==,type:str]
    TFDB_LOG_DEBUG: ENC[AES256_GCM,data:cOT2buo=,iv:3VtoOxH4d2P33mSLBukvlYbHxgzw0I7v/1STFpLW1uo=,tag:x8e+/l2B1PYgT/998e6CFA==,type:str]
    TFDB_ROOT_ADMIN_STEAMID: ENC[AES256_GCM,data:ryST92q+v3Ho84m260vcM08=,iv:w3TbVKCyB80ubyBqwI1+BNfh1ckoVG5iLX7IZYLvz5Q=,tag:CkVLAanAQ18T6H3fz+QQxA==,type:str]
    TFDB_UNITED_API_BASE_URL: ENC[AES256_GCM,data:85XzWnwESgd28OveHYIF5PT/fBlzAhUki7Ftxt5//A==,iv:gYEReE6InH5pz/+Zg71/yhgAtQa8zkMuzLC+5QDOJ7A=,tag:cwNM5rmLxjRMhIj6vUWJyw==,type:str]
    TFDB_UNITED_API_SECRET_PASSWORD: ENC[AES256_GCM,data:cyCbm405qpf0qHQJRoqCS2oxe3EtlsJ3k4Jq/xCfd7Y8IdUUIryW,iv:dczzPuXrcDaWN6HMbXGX9WJQWYQUic01ZLdScOhffYc=,tag:Oy2EaM3ejd+Xab0cq442ng==,type:str]
    TFDB_DEMO_UPLOAD_TIMEOUT_SECONDS: ENC[AES256_GCM,data:9Y8=,iv:NNOIkPFz/4rzYj+rv6x8nv7AV+YeUVz217fV0qOOVAw=,tag:TFdB+dSCLq4Vj47KVpZdyA==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Yk5JNDVYODQ5QmpXQnF0
            blBOWndXOEVGVmxnREpjZnVPd0MxK2g2Q1U4CkhGRFFRQkZKOERsS29zd3J6Q2p6
            Q25NOVMxbGlBWDBJSllzdVVKeGx4RlkKLS0tIE9xVWtnenZDc1NEcVp5bzBubDI4
            aVR0VDVXa2JxRWNIUzdrN1I1Tnd5S1EKbnOoLoU8Y5WrZL6zJzt8unyMDUORG3hy
            khmSoA5sRflZMgWMYQOyDdpfHK+gDgas+QmMs8jJCHuKK0xtlIEgGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:04:53Z"
    mac: ENC[AES256_GCM,data:Cnibnrf4e+nInPMI9hFMpMQMwQKBvNZ7sisgeafKkQyKWWTgDvNln7YVH+8bUUOLphWhtB1hAEUukl6bjWuMF6PGMa0KWbddSGDq4P+sF79vvj4YWlhSCq6iwqrJg/8ogc6maNXtOtatuCaLE3CP352yOOCIE4kaWb9N+OGFQBE=,iv:2Gi8hEF09TLf0F3JiAodMilhuVdYg4Zp+SfYRn2gOwI=,tag:2MgzMleqrgnzXVU8/O35VA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
