apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gUdJU1bOQumXbe2bp3LTSQ==,iv:awDBmfaoVBX/x22N1sw+tSpuaDUNjzZXUNnWfi/ecUM=,tag:7l+Nwahaeym1v7LDrtkzvQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:vkGfu6NL5q0Am5YycDdSuRFSyjOzWBp3Ax2bmO5F0HUyHWqpakimk3yGotdYJ1vOMx15HnCUI+V3PK490absdyNRYyvzpwm+Qedu6k+71Vgp,iv:rc6szngF4TnKl3fGktp9+YtR10tcL/uHGWpwydeuBus=,tag:5EmCdhp3IFY4H+wmXGeeKw==,type:str]
    #ENC[AES256_GCM,data:scpYMbdGZJv7F6MK1mr4/g==,iv:nRqP/v74czwW2TJw5MeQAgGdSLN+D0LyN+leoupai7w=,tag:+NGmnji4KDcHGCHaebWKpQ==,type:comment]
    TFDB_API_SECRET: ENC[AES256_GCM,data:osWVgfwvVt8GEyz7GvPcFbJidgAnuLb/YA==,iv:tQuph3sv3Fv8YcUVty/0KE3GLDMD7xb5ECIhckER8+o=,tag:nnOSHzW3VefDY/dWxlcxDQ==,type:str]
    #ENC[AES256_GCM,data:RRzhvS//nwK3ljmWQGKWD0e6usy5g6eb8B6bmA==,iv:OybAYv6EU7CCJARSNrORczghdPDotAd2Yq65vpMlr/A=,tag:cBj4PKdaionO392sNT+zdQ==,type:comment]
    TFDB_API_SECRETS: ""
    #ENC[AES256_GCM,data:lnSP3K4lURmP,iv:/xKWUihhieFgk1gc0s6GDPD2NuE1euvk332mc0jwEVA=,tag:gdkhW6xQoEzU+imEBFOx6g==,type:comment]
    TFDB_MAX_BODY_BYTES: ENC[AES256_GCM,data:7EWJ8grRxA==,iv:lQzwlLui31B0+EQEIbZThrkMEOZ37dvPNUdzy625m8M=,tag:CXIk+7liRDBYHYOBuzoc+g==,type:str]
    #ENC[AES256_GCM,data:B69rqTSKCVYq,iv:kaGqe/lJvr+9zgr1wNGTyOdIczzSBI4inAhT/Zv9ZKM=,tag:ZgpB8gBN9W8pOiqZM9l/HQ==,type:comment]
    TFDB_LOG_SECRET: ENC[AES256_GCM,data:l9YwvKBJnmIaWrHIwp+Mv26RdkE/nQL3AA==,iv:U6m128LHqpHW3gWxLZThnU6jvdpE1ujHing6oABqP7c=,tag:l+c77vwLhnV0u3jH+g60ug==,type:str]
    #ENC[AES256_GCM,data:krceVJetSyn6,iv:czoVfOp1JFvVH3CEr59ocUoK9dPpY37nxZ1nlQaflfw=,tag:5mbQ9DmFYjd5DU08aII0jw==,type:comment]
    TFDB_UDP_PORT: ENC[AES256_GCM,data:5Sgix5Y=,iv:fTW3u1U3T7UflvEMWxLztQkiny+et1llYdtNNV7B7zg=,tag:1DnZf7bOTNv8uUoBso8Yhw==,type:str]
    #ENC[AES256_GCM,data:QQUQTdhY3EIC,iv:cSXqMWs3w55CTINZ7Q4fwiA5B+eKqUamoudpFImDD1E=,tag:wNq4hlX0r87kG5CyvdPIjQ==,type:comment]
    TFDB_LOG_DEBUG: ENC[AES256_GCM,data:MP5TsnQ=,iv:mVoS0v2PxM2ATsSWpm5lxv1qfM4b9b5Ycmx9GDJV/zw=,tag:DcAwjU/xEkskkjocYuXQGA==,type:str]
    TFDB_ROOT_ADMIN_STEAMID: ENC[AES256_GCM,data:rk4kxPDlmVy2jRRpvVvVTqo=,iv:pg8w9NwLU2dEY8ZOUXZujQH2AV3ZT/OUdYuFZeKPgVQ=,tag:6WB/YlhODM788mL//BGImQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWWg0QjZuRnZBN2grdWhV
            NTd3N0Nmd1huVUFFdVhUNE5iamwxT2xSbkc4ClZkaE8xMGxsejJMQnNMK3BWYWUw
            MmdyOVF2REhRZHZIcXR0WlNFanRUM1EKLS0tIC9xb0hpbnB2TGwwZ0Q0VTE4eWZi
            RVorc2RRdGF0Y3IxaUtkSFZaYmhQMHMKQRFTPvJClNTC3TndHhTH3R0n+9nWAkUx
            QPUeEfjeiBQyuF0dki5RYXvzYmNlCMggiIcwVWf7bWry5tEiGytXxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T21:54:19Z"
    mac: ENC[AES256_GCM,data:7rA71GuqDEI6WPyzaA4S5FrCuQ2E3qqTWL0gs+YtfdZBENgMqChn8Ff5txb4KboKH6lbDL0RAk/u7jBTWwuGcJFbbrzHyN7QMjXJIDINREec0fRi/MY+yKJYl1eah1rXB76t/DrkFvCuY8XcsOWlfgXeNMsQX1vtjMYsS91vcNc=,iv:nxGWxF/oADMCBwPoO1S30I/NqGOmc2WIPsgWFMFOq5w=,tag:z+itgzGlvtOsTYALVAKXRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
