apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:aeTHptmCqc6+KQCVTSmxkA==,iv:OahUM1UGqRCEJUL9Uu2n2V1E8dePeCoANqrOgK/ZjeY=,tag:OmgDDtMyG7IDkE6jNQcDxA==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:ym72rDNqjoET+c6o+oDiO/88b4xkCLgMNGUM01z2drjG7B7XzAFTQq5Z9k3mtugV1PLzfVB/apF9KJw8mLGT3KRIuvBcly5Oo3nd4HsqNrXp,iv:VIYbAJIkpFtqd+rbIoPaJk+cGkxrKY0RdMGhOGVRzM0=,tag:e9VM1+diW/62SyVRk+jcFg==,type:str]
    #ENC[AES256_GCM,data:nV4xxIP5Ndgz/aLlojuUqg==,iv:sPc4X1LmNrXMq8RpvQ+RBF//J5JpVh+IzdisVEPETbw=,tag:XTtCo5vAKY+Wh1BBAdpTzA==,type:comment]
    TFDB_API_SECRET: ENC[AES256_GCM,data:C6w41aR/pZnHpW7Tf2h7jAGo6xsw1N9gVg==,iv:GLTs8ojLfzYszQrQzTmo8/JTqBPaSSNlb3kBdhEosWY=,tag:ZMBPcg7PmcObOTOn0PCgLA==,type:str]
    #ENC[AES256_GCM,data:qUdz/e4YR/sApkXCAphD9xG7qAcdGnVozg0hyA==,iv:aQVD1qZUMzNiDn/2FL+Ot8uKTi286c3WulOcxQypEJ4=,tag:KXEWWUeNMkrnzHTUBnATXQ==,type:comment]
    TFDB_API_SECRETS: ""
    #ENC[AES256_GCM,data:uugCf/3qHRpp,iv:B3DjpON7CgP7D6dNtZdEJFJZh4I//hREH4ZldlRAE4k=,tag:uzZ6ct4Ng+0gSgZybckU7Q==,type:comment]
    TFDB_MAX_BODY_BYTES: ENC[AES256_GCM,data:6+mbvz01Yw==,iv:OhiRgf2IdHraiq/FWFMkA86kuoKUc8V5tuoVhnQ7NWc=,tag:Yla/ah0c68rLqThl4+udBw==,type:str]
    #ENC[AES256_GCM,data:2avcuGZSPo7u,iv:zGIvTu3BuuUPMs2Q5zKbhZDc83gXjn4ezW7t0ESM9qc=,tag:1dSxFNbP20FIUQbPOM4cEg==,type:comment]
    TFDB_LOG_SECRET: ENC[AES256_GCM,data:XoyV/Gv8hFNGlo0L2a2q3L6zOHDZk/CxiQ==,iv:Itpzv3av8HYOqNvrTXApvdZfzV6FthMNqH0H0Yq1R6E=,tag:4CQ96DpyWGPsxHb6QQt8iQ==,type:str]
    #ENC[AES256_GCM,data:8vHsoBGseezU,iv:lzHxTl0Ie9AhxRfCeC21t/nkhUOi/HvSVogG1VAdMpc=,tag:thZuQH8allz6PrppQzdtsQ==,type:comment]
    TFDB_UDP_PORT: ENC[AES256_GCM,data:baLJ6J8=,iv:5vKyVCID4lQX6iJbTf5IvqqnqbFa+0PfZvFT05wxvaE=,tag:39a9HZO0Jl9WSgC5gj475w==,type:str]
    #ENC[AES256_GCM,data:de2gwnj1btsK,iv:62XANAaCXix6FubKAz/9vptSRdm0i28q3+l49MS5BOM=,tag:jDBi75iAphAx1nh4r9VQtA==,type:comment]
    TFDB_LOG_DEBUG: ENC[AES256_GCM,data:KiGdgyo=,iv:kowEKYDrWps+qcDIw83il0FP2zOx0gWq1Sfqt3Hf9qw=,tag:Li96eEE2I4cRfoXDyCCcTA==,type:str]
    TFDB_ROOT_ADMIN_STEAMID: ENC[AES256_GCM,data:Nnc8NBk+I8kQKct08CReE3Q=,iv:Laoyouyq24+wlxHXyV+v5a+n10WdxohqVGTd7fg2bSI=,tag:Mbi4FbLqJUB68G7Gtem8eg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTmV2dUhoVVRJYU9LYjRM
            R1Zhb2tuOVFEQmp4aUVYRDFUWkZzaGI1MkRNClFyVUNtSzhYN1QwVVR6TmIzSmNv
            VFIwMUJvelFsdGFkUTNJSGJ5d3dUY3cKLS0tIG85a0dBRlB3MGJ4c08raXFCdHNV
            VHl3VktqczlQRUVLZXZpTFF5TmV5bnMKe03B2s35uHg1dyh62zoL+ti4aMkcV4Hv
            U85gZkP4Bm+WR+O6Addrz6xocDhzMoycEMRGR+rVYsO+2aHY+cIV1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T21:30:40Z"
    mac: ENC[AES256_GCM,data:0AHevUsaqmmEEoND6FY2gEJuIF/3dim0zrFDt5clq4Igx9evxK9JTJpDyhWXG9+VTJB68WrBLdgUbhLdAMtqCCW5qZOFMf8nthE6N2POUkWkdRV+DauF2SB/V5xNLRxqDtz36MEm1DyVXAENN8d9VRR9IWzRNZl9s2SqPiAY04k=,iv:QVOKl9x+tPQ41MlIg81T6NzPE5lWNZQtuZ8CtOETiHI=,tag:fWe7cNumh13mT6Db68zaWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
