apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: server-passwords
    namespace: udl
stringData:
    TONY_76561198123577596: ENC[AES256_GCM,data:w0ucwz0Y,iv:PDHIzutErZxLc0UYOzyTI64VhJMXnQS72cygf+JTLk4=,tag:rJb6W+nQZTv8SAAGrvn6OQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SzdXK0lKbUhQNmliVE9D
            STRHc3h3ZkVWNHZkSE1aRm54YUpYdmdocmpVCjJiNTl1ZTUwZ0hFenJsWkNsaFNr
            SGlqSG82dnREYzhiWm45TGZmeGN5eDQKLS0tIG1tSUdkdzdZTXNxT0lDQWlPc3hO
            Skd6eDZlUlhpUjdGTUR3MmZkVmNPdzQKt9Xj+Yz5GBMPvXz7/6HyNNQevtrF22+A
            zQ2eD1o6JVGDGGR6lVcFL0jNbP4/eBShGEoHYyAx34nvPzLcN7mVlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T22:23:27Z"
    mac: ENC[AES256_GCM,data:nqj5infMJkYn7NC7XO+C8HW0VpdqXH9j6Ayj5xT1PG5xu1FnLrmJlXHUq6EYTkQp9W3Boo7lMq2GiV+b+4O0jLWPjJj822iwERN2Mjd6GhxUL9fy6guszfq0HrRVxKu2oXywKKyoBylrMrF9JcfHOPHW16o5D0Js0Ln0q3JV53k=,iv:Vmp/fSQNKCj2IKJN6LRe+wYLMfBfDEvGpvLRoGYdE5k=,tag:znlHlWpOlL1XAF9q2naMTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
