---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: server-passwords
  namespace: udl
spec:
  encryptedData:
    TONY_76561198123577596: AgBnnb0m/b/f2IaB76QToZhifiqidvqvbo/FSdXMZrOLjF9Z8SttqLbkkeIaSEObAGlG+Q8LepEGuvayqfFXJQgJRvME53ueC2Y+lxOEGeouEYf3DlYaU281gAJ9JQLgZh2VbsL4vPOMejtEYn67DSrQWg/FsQSInb0BAF+r1FIZjHJfz1aDD6c6qX6q9UpNlAhh9AkjvRv9RRpbDUpDCpsmw+ikLUL19OqDBhx94tIeiT2q7CJXrJfq9qIRn6Xa0Ac0iLx6GtuTjisuahcnvrYEVm/j+37EGYRlXE0/cm8QKM9Ze04CG5oKV4ZY9cjypPJ4x5FLXc/P34kAljQlCcOKVtmETtu5Nt8z9uMRi0SdEf4akEq+p9l7dgJ2kRaaT9FzEds0DdDq5T5X9dBwRPYNNB7jKUkEqS7Lkmto+oDnhRDX89GYJHGahyJcP4lHu8Q2OBg8xGr+vVnBNUWQzCf0QLa2xn9dbXsXDWS+qfsMmumrnaUqVY9I3BwzHznuvvjvOViaTkLAs3Zkb1lrsVG338s582CY/W2/o7L2HX8oZ6MDrLyYsEE9/sJrXKL+Bg/lSmNEC42wBo5dQWLfRO7pcevRZw+X6UaggcsVCIJEAud0moMyI2/QrWHy2HBTXiECTwgZXhhR2c+/PSizT7vn0kFSGSxkHvPc3iIAF4COiWtfZ9NodN6jfaoDmghMeIdBi5Pr9UE=
  template:
    metadata:
      creationTimestamp: null
      name: server-passwords
      namespace: udl
    type: Opaque
