apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: server-passwords
    namespace: udl
stringData:
    TONY_76561198123577596: ENC[AES256_GCM,data:Lb7PVaK/,iv:gz/+SkHWLXbHXIGtU+2qcUI07kYAzJwchwRw+M40WFw=,tag:IwSZVYAEI+qALwEmzFY1jg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMWk5emVqdTBrdk9iK3Zh
            Mk9MYUdoZk5oTHkwSnJwaXJFYVh5bEdoOVdzCmVFd0xMTDFKTC9uV21NK3FNTXZR
            WDJnU3JvaEY5cWdtVFUzM2JOUGV3UXMKLS0tIERqV0p5VkszRFU2M3VXaHQzQnhK
            dVZEbU1DK0JxcjYzNGRsRjhZMGZ2TlkKqyZJPP2prwHVF+bTisQnsDl+w9aI/N5V
            6woWLKhIK3wsbhg52NXy7M10a4R+VqHxg1KhJ1VuZbfFESmS/OIGrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T19:18:54Z"
    mac: ENC[AES256_GCM,data:xv5s3w7BXEI74QXytP9Wow6oBdC1uJIsnFWu9snJ2UjZ/p0NKC0X8VjpwLTiQALt94YkMTNbrz4p2sh9opVavtb7jGvpGLGkHDASnFWJNbvaohkjYG3Ede5sVmNJ1NdRp5orx6XM3NzrHYTyZTPyEm1e8TjjPRIPFZcDO3eEDlQ=,iv:UMBeYs8BxHCg4wwkdb8FR+QqBOPSJ2kqq4jqnPkJmrc=,tag:YWsWCmIe2mZRZQAj57uy9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
