apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: server-passwords
    namespace: udl
stringData:
    TONY_76561198123577596: ENC[AES256_GCM,data:vErHUBlB,iv:6NCeBKZneuqQ9XpbMUAeA9e/4L3QYoMzf0gpXrvOIA8=,tag:cS8zALXDTg8K1xRUZnEfkw==,type:str]
    POPPAS_76561198777082182: ENC[AES256_GCM,data:badX+AjA,iv:fPMgSMut3WtAlJRMWTBvv74SXZEwYyy9ubuwEKtmw9A=,tag:IInn/5GDgd+Q7go1SXIgJA==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaURoWkRod0lzd3JHWUtj
            d1Q0a2M3RjRpMlcwUndVQ1hJOWlmUFJlbkZnCmNoaUJ0TDd4VWU4bGdvNUxpWXZq
            QXh5N2VtamJsK2pXd21QMjBGNTlYYWcKLS0tIFhZQ2dqeUt2QUE1TjdZSWZjZkov
            YzVjdTErakp6aFJoN3ZvdDZIQUJaVU0KFffyILBxkkeXi1uYiSVyT0LK4E4jnz/4
            dWaKPE4ZrC8R8EyTV591l4Vtcxz381lsBofAMwcPJGD1wPnELTRo+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:39:03Z"
    mac: ENC[AES256_GCM,data:p6Y2tHEiWKdxw6TAHUD53Nnyudmf3fFMfg2Pv/clKTIq+r36qMB75U5UmPdf0UwNwm2d7KUxLtOSIhwsb6MLRIJs7AfYMHvx8FhKyzq3z3Q7dM0nZrcdltANhZa6Acw1eQPYTf9lAFBJuNwgx2JXfxUgOukiZODClNrbIXM5bOM=,iv:wQZ7hJtU+82Bx3Xvonrdzr7/a9SdvGkONn67fkoHt0E=,tag:B6sCIS30GmSwJIeTjkH6Gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
