---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: server-passwords
  namespace: udl
spec:
  encryptedData:
    TONY_76561198123577596: AgAwHp7erLXtLo6GSj9LkUMwpnytXujwc8soYa2uDxeWQnF2P7HCPZzSQ6cd2TbM2EnkKWLAZFASj2zitYbjfqHjBKaqQFkcV/bjV8Sqq/dIidRSWtPsoXKEbjKAINjiKt9s6oUNCBZMXu08jBYFuozmR+/aqzbLD59vNZsMJRQ9MkzPCVaH0b3tgYXKbCns2ZNWyQUqGE5qykJIw+qmn4nw8r9+xbTubPz+01HVTd5SYii6JEm0VU4mpLBfBCz75RUeM1b44z8pt4Wxfv2aIo0//HnNR1XQouuOekBzG53uSoXLDKklDkYaqJDRO2dLiKUJlF+Bukv9gFXx9wlcNMIkcWdZTkxClu9INsmKPou/t6xsOl7NRk7AaneNFKORUpfRbCMEKj8euuttvrIpDArRFj/FWiRjkML1EcroDVCZeyQv9B5q6DafraCgNqelwlS/rrdZS4zG4+bQVT5Izc1hdfONSWcQDayyAzJhnIZK22Ennw9e81yVYZxBkJu/nJFo7lpEMvcw7Xb47NiJ/SgB91q2qdfDnFwft3A4O6yzvJN5FRkNmr83wYbPkDyc/EeE/RDeoLtoW+55kLgdhMYve5efgKvovLtNkWzbFNYsPQg9ma2A0IJl4P8e+EYST3TXbW4sE8Cgx28rmggHVIaUo4No3J7848/XEW/IzghqQwt+VV6s3xP8iyVLGmMmseK1XpTHXBo=
  template:
    metadata:
      creationTimestamp: null
      name: server-passwords
      namespace: udl
    type: Opaque
