---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: server-passwords
  namespace: udl
spec:
  encryptedData:
    TONY_76561198123577596: AgA/m0nLMxsp8SdyvebvoEtYMf8VenmcsRaAOY7wOrkrq1ire0DCtZqFkZJRsxTJGDk5bGvaEg7lf2Whb56o0eEpUMBsfn9jdNj3eJySt8hXl1J29op4lA8zmAFMlAuGYuY14JEEHnwXkFBCIUNQR1XK2wA4Q0a9Yh6BCgNt8lXKTMjeYRf77BTXLz7FMlHVKObk/JLfqap3kbd7Vpseoy3X7F61cUnCoLszCNVbyv3ftwy6ypGkThI9VVsTIU1ICWLxJPV0IhR9n+nCVJP3HDIMph82F1oAv+Pn3/WpiKNhY6Qt3WkzAl/gDjMYp/Y8lQkMintwhG9m4HJHHOhblE/Yko/KyDz8e0e77B9unR+hEInq5KG5VQe0U0uUw/Hz+css9t61hcEiirAhEUBKw79e96tGpvA+a0uJNDFm/HJWGGBQMXD12aJPw84YmItXGgnXRKiZ+F2kSyCkuJVq1EieGU+q5ySCA2hjqgFiUmvf6t3d9wGkYq6+nlF1g4VEKFpAtXwYR8BRVqn7iH60KxAsMGF7j7WkmZv1keZsj5YMAujgV6VGXimBgtfzqO7jR/amhlA90eHVz5meOY1thfK7cknXoDNshgmcO5yK+XAceEel0PtjYBFa7dhVrNak+XE00upHFRpX4JxXL4B/Ww0bQHzUa0JtM02rg5ElcIwl8vm/GmYzvnuwW1w+RYcDq3YLDzDLi+4=
  template:
    metadata:
      creationTimestamp: null
      name: server-passwords
      namespace: udl
    type: Opaque
