apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: db
type: Opaque
stringData:
    MYSQL_DATABASE: ENC[AES256_GCM,data:lXmFiZ8r98eLzg==,iv:1EYVYWa+IztfT/NQMQ92ah6K213mHZzC5p4TFtHinFQ=,tag:LyJWp6brmvX/W68D0sbAPg==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:cd2E8ZCZloKbPigyaR4g0Q==,iv:NxhuYodWo5rhlhsTtrFu9exQIzc6Uln4pDF900PnRug=,tag:Llk2VHX7l1bwS//CxmreHQ==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:A/AF0FBC5SAwgWS8OdVlQg==,iv:tnYxCwq8WRwcWga/wgv057xM5I1xSrgPYAfVrBnuJF0=,tag:KpknkkIW9/i8AZDZwmlwzA==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:KGgPnJF3SJu0Kw==,iv:J1KTiBxXmIY9owt6aIDdkU9hgODDsejgNhdb6nqdrTM=,tag:rtUk6dJAjqGn9S34MNgQFw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS0VZdEd0SExXZmZLZHB2
            YjRqVVp2UWM4cW0rK2Vpci9GdldUK29ocmlBClZzR2traHFzSjIxY0M4Vkx0SVZv
            Q1VXZzF1TTBQMFQrckZsUzVJVElhMVEKLS0tIGlmWVAwTm9zcEVEVThVaFFoMmow
            ejN4emttMlZpWC9RSzNzWUF6dFdnb3MKnAY2oKTHn2zhzCpogQpiN7KxCm25ipgc
            L0tpPkGLjgmGQtJtPjfgUPpDcie29afRqQ4Xto6STgiT7fQsjk5N3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T18:36:38Z"
    mac: ENC[AES256_GCM,data:JoYRnfT/HSj54AiVtjxyArDkiGsad6znn0If38gEEIsUSY+FYQsgHSKpU5TYpCyfLSDaEnYJJJlnArGhM/4J7nlxOAfrCSRGYdFMinYE9u2CQ83B/FbLnAchx/rZF2fqNfEOJy9LeoiTs3SNdz2oHrRV8nOQnu0l5YRBn/7Ql4M=,iv:9pQT8j4s+jzcha7ae0rDJcr19zXKWOmsWNGkGX35dog=,tag:FSDA413v3vD5TBzfFGcdTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
