apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: db
type: Opaque
stringData:
    MYSQL_DATABASE: ENC[AES256_GCM,data:3AlR4E3f7TdROA==,iv:UA4mK8zsN/+28Xs344rEB2C5SAO+vfpyS0Yz7T517B8=,tag:oWAp2DJDcMCy6YV1kMPuxA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:OBoV+xm+d//NbvnJwbqOpA==,iv:ujOtG9pTIwIUsNCuqcuVCBbUjGhs28etaxYMunjAsfw=,tag:a+yQtieciPh4vDPyExNGKQ==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:rR/gNK2qC8s5BABW/rHHaw==,iv:eb2SLKbQFC9Q9dks+O+d2as9kCsU6BA0Xjgc8EcY2pE=,tag:KmkMAqUW31PDtG+qIh0tHg==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:gcz5kgBzFfIpFA==,iv:uYTUjEM6YvA/z28sWruDs3Lj9haTalu/o7OwHD73bd8=,tag:N6O60ZkD+WlXvedQy3Vl9g==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbmJwSXBKTjNWazU1YnZl
            cHBMdStXR290MlZacFVoOS91VkVxL20weFVzCk1saUhsbFpJbThBaWh3N0p1YmZk
            VTdmU0tqcjFsdW9IVndUVTJtazZFRFUKLS0tIDVweHV3bVZYWDNORVo5ajhMNGdE
            WlFjaU1Ja2gyYWptUVNUU0EvV0hHelkK49Lpj+STjuvngegQB+GQnr1VJpQme2dr
            Py/qRvrBuhb9lfG5dv+3R5jLMbPW8W7+EZDYo2kZdP0k3jmxUWnjNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T03:21:37Z"
    mac: ENC[AES256_GCM,data:kqnY+DXLs0Fz1s46a5FHAoZkAdN6euVYEwpdCNM1V9KoP7/94hAiNJnFfy/YEX12jCuoHkxNMRK19pa117j8SXTqDknokv2HE9DiLR5ucqD+ybmP7yHFWH47+ZS4ghYM9Enyrlt86jhU6fAxBQXRUFVmFy8P+ice3irPtwwqGM8=,iv:lUUA6585LjT3BtBqGNPxXAEvcwrBu5Izycpw7vpYDaA=,tag:1H1kVFIDGr/YouPN5XyXbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
