apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: db
type: Opaque
stringData:
    MYSQL_DATABASE: ENC[AES256_GCM,data:uOVz0OG1rqEgDA==,iv:laiFeF0oofvsCsolKK0kAgZ+ED5vLTxYLWlhvgUAWnM=,tag:M9OuDTJRZsFDXGdy4FKclw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:W7Ax9NJzA+Hj39yF2QkWNw==,iv:sf9di5IZ6m2cT8ij3/HLXFINO/cDs/x8jk/QeoC5XIc=,tag:SW0D+1nx+ObtaSgoGleUqA==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:iO7mx8TUbgBP+kgoqMwaqw==,iv:P2+koZHEhrpKjcW/tDeJ7PXgkhhBrSVlh1dO/VPvckI=,tag:tD+ezbuPgG1ZqBZ61ZRT9Q==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:UB2v/WOMlcFLmg==,iv:OloBgwTHfK/QZA3Cnko10Kn0o+2IMsaoljSNjNL+Q4A=,tag:abITTwNrQU/pozhbJEOC5A==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR3h6MVR1ZzB1TVo1bnBs
            R1lUcy9Vbzh6eVMyanRWckVaQWk2emRtNGlnCkFEcjEwempGbzlidWFYL042aUtU
            bzZmZ2RVR25aTVpLQjNlbnlZNVgyQVkKLS0tIFJSamdNM3FHOVlOZzNLejBkS3NS
            eGlQbVdhc0gxTDRLQWU1WlVxREJzeTgKEPK5RXG4W/t3vjMOkSPLh2+BVSnOC3T8
            DlnUecMvBTC87s3GYlSRxoFbES+EgcNOMTRKH8IdB8LmOXz9UAfgcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:04:53Z"
    mac: ENC[AES256_GCM,data:or1LbAjR/DcX+Q9kV9eRulMHRpkQtWTsLVlHSG8qm9Bl7nr92gJGcxsWAXI81EWk2GT+4OefrgvuBc1RiypYHPAU/35i6Xho2B9IELgGh4AZgtCmheW/Dd9meFuCLyePZ/FMlAOzeBauHV+ZMeEF/u4E7T8nfgIVNU3K/+uJn+8=,iv:uw5becFJlmdFANBo4LdD/X8Z8gqKmNnUKU0Qb7PAgio=,tag:SzP19jcHaVTWR/PV89PvRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
