apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: normal-one
  namespace: udl
spec:
  chartRef:
    kind: OCIRepository
    name: tf2chart
    namespace: default
  interval: 1m
  targetNamespace: udl
  values:
    workload:
      kind: Deployment
      nameOverride: "normal-one"
      deploymentStrategy:
        type: Recreate

    app:
      name: normal-one
      image:
        repository: ghcr.io/udl-tf/tf2-image
        tag: latest
        pullPolicy: IfNotPresent
      ports:
        - name: game-udp
          containerPort: 27017
          protocol: UDP
        - name: sourcetv-udp
          containerPort: 27122
          protocol: UDP
        - name: client-udp
          containerPort: 37007
          protocol: UDP
        - name: steam-udp
          containerPort: 26902
          protocol: UDP
      env:
        - name: SRCDS_PORT
          value: "27017"
        - name: SRCDS_TV_PORT
          value: "27122"
        - name: SRCDS_CLIENT_PORT
          value: "37007"
        - name: SRCDS_STEAM_PORT
          value: "26902"
        - name: SRCDS_MAXPLAYERS
          value: "32"
        - name: SRCDS_RCONPW
          valueFrom:
            secretKeyRef:
              name: rcon-password
              key: RCON_PASSWORD
        - name: SRCDS_STARTMAP
          value: tfdb_octagon_udl_v4
        - name: SRCDS_STATIC_HOSTNAME
          value: "UDL.TF | EU | Normal Server #1"
        - name: SRCDS_TOKEN
          valueFrom:
            secretKeyRef:
              name: game-server-accounts
              key: UDL_ADVANCED_ONE
        - name: SRCDS_TICKRATE
          value: "128"
      command: []
      args: []
      stdin: true
      tty: true

    paths:
      hostSource: /mnt/tf2
      hostPathType: Directory
      containerTarget: /tf

    decompressor:
      scanOverlays: ["serverfiles-dodgeball-base"]
      cache:
        enabled: true
        type: hostPath
        mountAsOverlay: true
        overlayName: decomp-cache
        hostPath: /mnt/dodgeball-cache
        hostPathType: DirectoryOrCreate

    merger:
      watcher:
        enabled: true
        watchParentDepth: 1
        pollIntervalSeconds: 10
        decompressPaths:
          - /mnt/serverfiles/serverfiles/dodgeball/base/maps

    overlays:
      - name: serverfiles-base
        path: /mnt/serverfiles
        sourcePath: serverfiles/base
        hostPathType: Directory
        readOnly: false
      - name: serverfiles-dodgeball-base
        path: /mnt/serverfiles
        sourcePath: serverfiles/dodgeball/base
        hostPathType: Directory
        readOnly: false
      - name: serverfiles-dodgeball-normal
        path: /mnt/serverfiles
        sourcePath: serverfiles/dodgeball/normal
        hostPathType: Directory
        readOnly: false

    writablePaths:
      - tf/logs
      - tf/demos
      - tf/addons/sourcemod/data
      - tf/addons/sourcemod/logs

    copyTemplates:
      - targetPath: tf/addons/sourcemod/configs/sourcebans
        overlay: serverfiles-base
        sourcePath: serverfiles/base/addons/sourcemod/configs/sourcebans
        cleanTarget: false
        targetMode: writable
        onlyOnInit: true

    permissionsInit:
      applyDuringMerge: true
      applyPaths:
        - /tf
      user: 1000
      group: 1000
      chmod: "775"

    hostNetwork: true
    dnsPolicy: ""
    serviceAccountName: ""

    service:
      enabled: false

    podLabels:
      update: udl
      restart: udl-servers
