apiVersion: v1
kind: Secret
metadata:
    namespace: citadel
    name: ghcr-login-secret
    annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:7pcy+NiSSh2cCqhzagCJ51cXyUi56UiTTagMBJRKuXVFtxsjXzm4Iht6kyubdDovaOebU6z5a/boFkD9g57O9LuChDabB4t8Rg5xK9hXW5nU1BwwYsO4RBtTHU+k+yCb6j3WSvNDOdo2w3XFAD8PFHmRbO9xt2LDTfYN7XsWMVmJ2pA/s3/umbcgdo0YMtfBoXTb8FiCoBBYLfIo7n6A/kRdmkmFHvXc5bbXhRIYvVbprynn8rBTAQcqOR8Be6e+7AHUaTJUvAZzliXoNFrcyRIcvgzs/jf+Xm+XtJAfsoKgJA5cfjazSmiXKk3KBWIqRhwJO7PvIknc5IvyPIMr5qstS9Gix80G5dr9DH79K6c75FdV,iv:G3TMp6lTX+WBLNJRaJB+9gOlzHFFVll/XXzAe7zGJ/A=,tag:6pcx/nj7ELjCv06b5EOQew==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Q0ZsL0N3aGhERTVRNXoz
            Q0NwSitTK3RreFdTV3dvemV5bEhvcGlaQjI4CmgrcVpoYW1EcHN0RlFXYjBMUW5O
            VzR4dU9RUGoyYXE3T3BFakJiVGxObTQKLS0tIDBzcjh5d3F2Uk9obHBiZXB1c2Fu
            cnNCZWFzMVpPK1RGUll0QWZDb1JKSkUK/ecO8Skd3RpJOBjetxe3ZF5zOdI+Rw//
            EsQbpXtciU6pe0bLNzJXPBZmdDPv3H6IOTFwXa3CZx2KXWQRvgNzQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T18:36:38Z"
    mac: ENC[AES256_GCM,data:npGnA+jXDqXc5VzvQ1uBNGI6068oIxDiLUmX8Fxc5IG652/XTtI2HyxDumTAasLZ9q9RrtPnqgvsUVZvNnRA1E0E8aAXxEmgO7M4zRK0cWqMdvvMITxl/quqhsOoO34IpcuT2g1u4qhcbbj+BW73g0dARzHA+d53+RgTJLWn4JY=,iv:7nilpbcKCoeM3B7Y82EihrjhnHdOVa/NcTQVABhtsv8=,tag:/DM7/gxHIl+URkiSm/YeQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: ghcr-login-secret
    annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:QnQ7hprUhS6EfyjADYE4vDiXEihVFgL9rL+JIplAQd0Xj6A5D/SwSCW4ZaIi6tNi8Op612M50r3VuuWKMJsvtIRPYnGSOgsfOC91ZAAfht9inpBuDSKl2UbajewlClzACU3hRCM/ApivEUb+e5XBGjqiA/HiIQg+JhhT8XGvrnKrgj3dE12HSuKju3UUii6DJ17m5dT9SfxJZhK/8qYeQ+BqjK3krybn2EqJ743TpaEVQZ6daQavKbEG3nPIo08yTMDIweh0W+vBNMJ4epdrmFwez4rBTW0Q+6BIMsc0dSVeBTBGopA/1UdGpKjx2TuOYUYgnnytX0WG8ZQf0M3c+NJQfhXzPY/55an92Hq3C9Pb+9UB,iv:K9z4rJbWZdb7eZRb01DyoZ/m6Df6ICIiLF1sJdIu/fI=,tag:kgMb1JkR2gckyRyZMhsuEg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Q0ZsL0N3aGhERTVRNXoz
            Q0NwSitTK3RreFdTV3dvemV5bEhvcGlaQjI4CmgrcVpoYW1EcHN0RlFXYjBMUW5O
            VzR4dU9RUGoyYXE3T3BFakJiVGxObTQKLS0tIDBzcjh5d3F2Uk9obHBiZXB1c2Fu
            cnNCZWFzMVpPK1RGUll0QWZDb1JKSkUK/ecO8Skd3RpJOBjetxe3ZF5zOdI+Rw//
            EsQbpXtciU6pe0bLNzJXPBZmdDPv3H6IOTFwXa3CZx2KXWQRvgNzQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T18:36:38Z"
    mac: ENC[AES256_GCM,data:npGnA+jXDqXc5VzvQ1uBNGI6068oIxDiLUmX8Fxc5IG652/XTtI2HyxDumTAasLZ9q9RrtPnqgvsUVZvNnRA1E0E8aAXxEmgO7M4zRK0cWqMdvvMITxl/quqhsOoO34IpcuT2g1u4qhcbbj+BW73g0dARzHA+d53+RgTJLWn4JY=,iv:7nilpbcKCoeM3B7Y82EihrjhnHdOVa/NcTQVABhtsv8=,tag:/DM7/gxHIl+URkiSm/YeQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
