---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: citadel
spec:
  encryptedData:
    .dockerconfigjson: AgAyGVIZmRUMpjpbAm4a2inn05UyaotVWpgxzKUhnq9P/SsJhJPevxhAGJkT+jr5AV0FbpAkPS/cxakYzX+35Usp74GujRxyo/00iIGNpO67aexh4V7So12PPvASa7tFVHyNWFHImXlDSCxaQDw7lmKXlpvY0GR8LrPEvtWJqUSgYjapTR3rn49Wnt3I6Lcu1mEXsDhtzubyHVpYbvsfR3kQlCQAVQUoFeKY5aRwpiZ4BVKl1PdazI+CD389zXOxqv699qGkIVV7AYVbIPNx7yjWoVWXZ5qcqLGyTYZ4qE17rQ34GQgIquJhao7TTiHFZGiRJMIjrVc6gzyHPrE1EXYgYW9rZtlZ9cPAeiNW1SrxtG3vhoeHZLlQ+4j1EgCJrUdOEFgNJCtQ1kppWputNow/GO2hcV7K5V+/W8PyOHAiVc0NLUOKKdjjgxfUP4y5byESyqOeRN3ZyDho+KcwKhXJkQg7WBx6x/kF1/lkdmflQuC6ciDZpPOc1M67Cb+pgU4BR/Pv/OTgfkr/PCPywn9gHVNRdVQAqX/8BgZ0Y9uNiymIedcSt231dSVob6LPIFmOLY2sFT0bx67BRXUgptkZZsmXJWytMDPrnwIqNQLNtufhMw3AFbdbZ1+ywPGeb3NSXN/wUsIvb8RN3ELX/3V3/VV1IfxySBPsol6Zaj5CwyiwYzKfF4VVAHYcFJSDLGCuVk7YpqCCmvWk6N+JGSNh4T6ahD6j+obyMorA5lK2b3jDQiWNcZI5WU59rUDlUQ6+Lhler69UpcnyGv24uymNY/fxAGcYhEO2gn0uY16lM3YW75gczLNyRDy6dA0Ojo1sRzNNJebDve2H5sEJPaMnAIPVAwLFa0CDu9vkl138j2ZH6t2rPYG80JAiOqzCFTvgRL17yJA2E/p5Fc05tGnsCM5vltM1DVYdRr0+NLz4+2b0Rmq2vcRGzXNf0mepD9sVmGP9ePW3ffN7mAw0Rg==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: citadel
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAdIC1rjdE7BOk5pnvc5V4QzuCH1ZiFpKopzQ2VCrOvMDMGDVilKR5tLtrEt04j1jML18bgakfOEr7WGBp+qlPnHMte5CvXP62iUgaKlsymVK7lTWKtVyQQKmsEWeLqnQNSDp+l1V41j3NE18wfZWQ+nM1VIiyrmm3Yz7tRmB8WwctIPFopG9SVy3Zqdj2sf9tuyClWIsjB5ZwzdzqVvl7qEfx/8hlNTdioIgg+2nQxPwzdrclr1dgYOsfpOdVkb5KUqjpx5ODZZbxXPobDPwfaY5A9nMyb7ZQ9yYxfkSNa3/ht+VLMd8Dt/favUChkwm/TSL5mrPAWDw3SaN63XzVwzMa5NefSqubOANDoEx+EEN4pFBankvY9iN5BSHy3tPtDI4dOikrWxwyUL7kh3OOVavw8DM+ttKj36eBEmbxq1LwwCPiVdn/NYVBd1ru9C2EqoFgUj+xW5/62ChM1nLX2u5tuuszekWHPH1OZ55mtQxUdxsYbYUxFmuTqXzYeXx5GRBaYw4JavLSsuCn28NGezoXbgx1XpPNPEkV0lnEftDKY8Ai0FbMxB2bBqdgRMhQaTQDcfoZbd6hivh8tGD+54STp4wIhbRM/4D+1JRije9UWZzlNXo1uVN5B7CWNHFhBA/tsI6gTXoDEiWpxe7/lDC40o5TySdUnCCpsNX1b0DQl92h55+8riAlioQSna8jCgdzEqqXEGdadDr5jurfR/2KF96mdFc+P4gEDYvb7ExPkfoScMAkCEc+pS03MrcEMNvI0mDXR54xYXLPX6qcSHHyN8hZDI+/vwxIyKzaon9CZh9eZG2GVTSb8sgJADVWIzmaMfBVc8stH4QdMNqt64owLUGSSWekx4cYCi4v2gJol/ZyHFVIdGSAQ2xwa1AN2jRpA9pfwW8/guvRpG4OoHp3hUdKXvQJak6Rn/7aF1Kkxi9LdrmPLz1NBJIUpU1PMfSd2pWRsBC012AHfIg==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
