apiVersion: v1
kind: Secret
metadata:
    namespace: citadel
    name: ghcr-login-secret
    annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:l0jBRNYrDzyLzzmK7ueRFguPYeBtwVnC13GH7SVsdIMfTmd0Q0V/0Bct97qPDH+03P+K17KOEq0lNNWkubr+ztML6JaY9ADrK477vdNILHxRV7s9kBzTMKolhBFaX0TITSd+HrEBqFVb5JgAt+n0GfU48+9HvI9TBIiy64uQePX/T9XLq/SEjkWYqCJot4jmUwLkyJiXoM2KWSdPftcnidhRJ0MG27rrJugOM2Yy3NRcnG54LcZ1GMQ4qYPzrF5Io1atgUnMy1mDREkAEQQGuv3fZ4qH2sS6t1SwAaP99Lhz6DqP1dXco6yRLmgZsGrwEHSs3ysXRRI7CBj32v/SMhRmw/bXLBmtC9hgPm7H/cWe19f9,iv:dYg81UIzQQ8Pfkqq+AoB1OhgxxvTspfY24ChokvO5fk=,tag:7N60NXhNeC5u6/bnRq3C3g==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa2pNZGtUUWE5dUNKUW40
            ZjVaelJYNjZIcXZPcERFdnV3M0NIeUY4N213CkNwbkFYOEEvTzl2d1JBZHNobHVB
            NldQRDMyOFZsdFZPaFJsaXRBa05mU3MKLS0tIExFdUIxYkNURE9zK1dRUk9ES3hE
            cXF6R3QrdXZkWnZCYVBabnR0bjdFSmMKNJjh8+2U6/+NPXw/aC25mePPkbWXarQl
            64sypNmOLtvf6nck2pBkzcpeUfg3U1ldW/H20kxP9x74QwE81iB3lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:06:37Z"
    mac: ENC[AES256_GCM,data:EWwyVEmuWBt5KMU0OqK7PxT0Br1MNtt8+SOuCdR2Ga17QwGxvPqKXcRZqjB+WWSGnTD4JfGqMRFkaSh46oZQcYr99SQAhfsje/C4GLTh367mnIjp5VqdZDgOwEJ+58GVMPTBd5IqgDyrdeCrUDP1OX9HhSBUcG426JaNriwJQxg=,iv:HbaWBMbP6a31JXDSF21nnJdU4ffKgDTyxAHRkfjgHzQ=,tag:kGerQ/J8hFvRA3oWvcloWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: ghcr-login-secret
    annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:pb+kK5fIf/U8WSalpSH7YW3LKUeZHWaWffqXDQ40KfJPvF5KhUILRKi65h8460kjrs809vsa+2fIa+NoE2L4ZOYqknK7nZnOyji2Qg+I8fMkM5Ko6J3EKtGiRKQeUeaswpWfov/nmYaVy8AE2GOQLGGFUPbpG/IermN7i3hZTxRs8kP2+pcczuEugMctegcyeCuiMjbKYMweoK38zhjkUY0ej/EeJMjNTfP6f5VwQqQnL52SmDDNrW90EyRhqmkCdRRtzWnGnlKPkkMgrLo6Gzt5OUi5DRuuBJLoOixyxq3uC+TG1GOTeR4NMC+yPvBLkQUxldSfSbTT8na+94pIvhKDwsEOvHPz668qWdPROuqwDbZK,iv:qg6WMoQ35qcUNwYVLdUnB869o5VwTaqLkj2GW57kKLQ=,tag:eqcngRAvKSE7wcCbnsxy6w==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa2pNZGtUUWE5dUNKUW40
            ZjVaelJYNjZIcXZPcERFdnV3M0NIeUY4N213CkNwbkFYOEEvTzl2d1JBZHNobHVB
            NldQRDMyOFZsdFZPaFJsaXRBa05mU3MKLS0tIExFdUIxYkNURE9zK1dRUk9ES3hE
            cXF6R3QrdXZkWnZCYVBabnR0bjdFSmMKNJjh8+2U6/+NPXw/aC25mePPkbWXarQl
            64sypNmOLtvf6nck2pBkzcpeUfg3U1ldW/H20kxP9x74QwE81iB3lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:06:37Z"
    mac: ENC[AES256_GCM,data:EWwyVEmuWBt5KMU0OqK7PxT0Br1MNtt8+SOuCdR2Ga17QwGxvPqKXcRZqjB+WWSGnTD4JfGqMRFkaSh46oZQcYr99SQAhfsje/C4GLTh367mnIjp5VqdZDgOwEJ+58GVMPTBd5IqgDyrdeCrUDP1OX9HhSBUcG426JaNriwJQxg=,iv:HbaWBMbP6a31JXDSF21nnJdU4ffKgDTyxAHRkfjgHzQ=,tag:kGerQ/J8hFvRA3oWvcloWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    namespace: udl
    name: ghcr-login-secret
    annotations:
        description: GitHub Container Registry login secret for private images
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:8NJq/1Kr7SNyJmtabOuK5Fi0P5x2ZthvOr9hxfNIk0mAjJWmfefFXtDVrW0DB9j7cp/EipNWChoB9JyozS6ppxi+/t8lK+cYRD6zGZgyJ9X9b83desxr6nYB7v8pvrUdPogoe7528YMg6PgXn96nx6HU5hMIetfTOoUYp8g1hOgSDATP7a/oqrJ3XWhWPQ8gGR9Rt0LRt02u2eFyutz77k6kxBdFoeXgjvj39gZ5m0+aUHFo5vqJ6qBNZVSTMO8IYBVtbx86SGLjM/4nJG+dVOoTDQg5xZnGy2eFeTOWrjPt/eh0t/KGjPPM1Ol7taZSoQu6sNjkgzMKvlmTb6f43rjpmDF5hacnykk3wKpriUF72Ylz,iv:R8mNOus3VoOQ1aocyGXYR7Do/9PsjPBG+Hf2aT0xB6w=,tag:FfZqLDlZXzFZhfxEodbfLw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa2pNZGtUUWE5dUNKUW40
            ZjVaelJYNjZIcXZPcERFdnV3M0NIeUY4N213CkNwbkFYOEEvTzl2d1JBZHNobHVB
            NldQRDMyOFZsdFZPaFJsaXRBa05mU3MKLS0tIExFdUIxYkNURE9zK1dRUk9ES3hE
            cXF6R3QrdXZkWnZCYVBabnR0bjdFSmMKNJjh8+2U6/+NPXw/aC25mePPkbWXarQl
            64sypNmOLtvf6nck2pBkzcpeUfg3U1ldW/H20kxP9x74QwE81iB3lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:06:37Z"
    mac: ENC[AES256_GCM,data:EWwyVEmuWBt5KMU0OqK7PxT0Br1MNtt8+SOuCdR2Ga17QwGxvPqKXcRZqjB+WWSGnTD4JfGqMRFkaSh46oZQcYr99SQAhfsje/C4GLTh367mnIjp5VqdZDgOwEJ+58GVMPTBd5IqgDyrdeCrUDP1OX9HhSBUcG426JaNriwJQxg=,iv:HbaWBMbP6a31JXDSF21nnJdU4ffKgDTyxAHRkfjgHzQ=,tag:kGerQ/J8hFvRA3oWvcloWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
