---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: citadel
spec:
  encryptedData:
    .dockerconfigjson: AgCAxISbQlxV3JPwKnEtyL5IXEfLjej3jscmYEWTYatWp+EF4sqgDTEFaChXnmrHpBTL99pU1qV5ndwPG1UbKGqoCwHfJ5utaCnpR5oQHvcTqt+R0F8AaUtiZ3bWlwR/Bhjw/fy/t5oSZ/FCT2RxOxOr86WTU1WH06wO5ESHgY3N0/JQlWHsENgGAXdiaSdcSAWWkzbsA0q/fJRA8u8H9VLkxYNmvZm0YpfMe0V4ucOGPDC8NayMukqhLhJ2dEHcehmU0ahZjFOKezaZ0UNh/JM1LH18IO4IKwHwTI6Bytz+Ua+V+h+wpRPJl3QfV3T3qsBh4Zm8Q2Bn/8Ou7zzZCNbtCsn6j/DXctgUs8W+8tQXx21N6WgomkOmJOlbjOT9K+o5vhJ+LG7bKj9votW9MDFsyJ33YFXkKTZkJt/lkeMbDN8h4jZ9GbGEhzf2H2PklbOl2zuotjO6tHDbge2q/cFRIVJrNA4b/mUvb1cuUOCv3IwKxKCUB4kOzCbCdf02HI4qxgt9GKMvQP12idogCPYHPWyg2R692zJUegOngmt9I61kqfe5kvVzqrlElWcYBaNrrob+z/gImQwjQawBLgMvRmFkenI2x8enX8IrlmhktddzyMbuvEa0YXskLA2yJgYIAC1eV9RlQeLI1AkwCEn2myHhHDA2slhZJkR13e2fhAIfJB+4QhqzeSq2j7BtOSDcRx9FO9XI33o0apQKbjSN1NPIe7cvH7h60UW+5HRY5c/x99aGn25FIGLl6MHruyZcgLQ2hsZslsV1RYy6nwZv/LM+Axqvg+StBAF2jqK4lrmmdaZqZkdwuibj+ixcjkVo0IQLCioUxyv2c5vsSu2F0H4COwCiB0ws/xH8YwfuB/fVC82wKzSH/hk6nb3jY7/NnOaNRkkdSYUTsb1d43DrbIQ8PSF58CJmVXTvNBYuKJgH/AEusD5wFyAqec9fajFihZvPqTjJ+dfC5lRVpw==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: citadel
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCTVr65+3aXoi6TWwSYUiRtgB64OrNZeCe6iOY5U1Cn1BmCJNNE+x8aDXi2/d7DJ41GNjPp+iO37sEU1I9Iv6UpddOI/KFQGFGH14+N4ZGVfED1sP9QbjSK6AKuIwjhI6YjZa16you0EKAeo7fNeiXVZ6YmT5X1eoQ9Ca686ZKqs9xevikkd3epsd4dE4dS3KrRmOeZ+rB8jj1sFryaolcZiLGaUpDjw47D7EjMscrNO4vBdsJ4hMlzAURsf/lSvd0zRWznHHb6VYje+qYgNV4z8oz6cFNX37MJdXzxXzmNRdN6IKH0LknKqit+ITiV+YxyD3j7BxDxYCl2cc3KBltPNdnYhI/tXyjDXVEA5KyfdHKLgEFYQ3ScywOnUSeGZxSpA19T3G0Kd2y6z6W8xiV6JdU3FPjglnrYsvB+spBbrLap8ute7ZObgyZj75OFTqNB54wbOoPYrqTb2nfScKUrMCCSuNFHxbqklFr9KH5A94ZuanYBobkwNU52YuhbSm1rvw+6oBNsrxy5xWrfNaqKzhnCi6LDFI0i2m4UqQbQri+NkmrwV4cLW48AwkCoaS5A3DWc1ifQ83f67bV/WqW67hWdKwHdlYGRmTgc9I36QMmVl33v/nzbjB9EyJfLGajwfBOZRG0E+G/Pxirik+xyZABCo695LyX9f64qcEpPlOhYyK3R4zsRPcBQZ1qqvEhNf/Qr4CKkgxWA4qVbjhPREUL+/PPKWGLkhOAYLTo/WLmbp082hu6WrBE6po3822wmbgrB4ygLeOHOCFWmJm7s6cJZl0bFQs+2Wia5coDSNx8rWaKdw6EV9mCUCzID0Q5gDTTzQt2see8ZsnfhduNuJdnwg/rojbaDXUhz2MictpZtVSbxiLF/8yLxWjg6hW+rGQdpr4NmlSBDIKGx3AsyDPE+BJYTtUbrApgp0HXCNhiFvM2ZSxvDyJ/udj0vQsYkqkK/ZkwBWZQ3oUKhGQ==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: udl
spec:
  encryptedData:
    .dockerconfigjson: AgBl+lRQ6iYxcpltZBA8E6W/oG+Ff3cmmSjLxwoR72+dVZBLR5+kW8Xr6K4sjX897iRPAVQAN8j8WEzY9hbsWC2MkaOOWCVvAM21noW24IzqrYycUYCUbaL3P9wwwDz2IM0dB3eauf4fseC1+u0i45nAEIQiEBNJR74ZOYOLYOlFcy/MjsnBNkSW+dzeN9cIfbfAR5IduxLQbDe3cdmKExVLaUhoOcVePtDPmUi+Bfx2iBW7NWmqUk46zgE6kfF6UdPK9h70nKvsKQ52rcEGoDINQ5Rh4cVofHTAoPr4dAXOftrerzDY6ueVUR0p79fik9Ah9C1la6JR1tohjMlGRqD8GS9Bes23JUfHgpPiuN0p74vQS3wbycOb3xW+saJm9kwvKGnIkueBe6cpvdJkREsqaFmulyvR6CQegVNef+7VX3O4P76vJAqaV/wfaV4mq4TejDUFYKFtOREQz9XiGW34pMpneID3B8eqYtURyRIIeyNJSzLpgzGaVxrHbN/DU+SXjwOM32/+UnK3dgrawxyG9GvVGRSc/Wz2Xao/ZodDljGUhFYklbyUU05tp/vNEqBl1caDemCklDDWer3m6/HaTflc0Q0A424NbL727nv97twqLJzlC73a1D8pqQwHhkEeCKRzzBTWivRpUQMWyEadHYBkVrWM+KjS3lZNero+lwCMGVAgYizc5R7oVHwKIMt5n9DkYlT4rYuF1qLNoV8vyYGcF0uLuEYb9VyvMMIuCM5+oZFfEUcOwhyp3lTE88YA+FtUY1hix1pFGFzF8oYyLp79UBdRtg2N11OoNz7O5LBwa8pBBmYT5jL2aY/e7ESZ/aThXbiwrsqdpT+7g9YCmINPoj30W19x6ZqKiVpNapU7cQrC/BSO1USvtm7IqjUghxl3Qf2prxV8+snxPIPwIyKouP5ke/TFPTzDC1LalDQBWW1HPL3e+ffu9uxGSng4QeCRw9WO/zJT5dY5bg==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: udl
    type: kubernetes.io/dockerconfigjson
