apiVersion: v1
kind: Secret
metadata:
    namespace: citadel
    name: ghcr-login-secret
    annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:lMT0ZbSHYplShOp9tTgKkEFByZ0y3XilPGjbVKh4yaY1JCe7qM7FV3BBvnGQOKfQGZGUyQxtSa2bunV9BflVOgvgyq5gyHvSZ39jO9Vnybupv+yK6eIJTTvN52vrG1+G1I3Cbl3dzuqZgrsNoSo7yo0UU8oh4AIaGMIxDWWUQrgW849mJ9hFsG+PvHbdnuqAt+Yke/mcPtq8hJd/iZRoiZM++QSMevsVcxrT2ywV/1mGYGTWakbFVOxZE/VjtMmFs0DKVdlUI50xmZ2qNpUKaxGL4iZ7DUkVYe+iegkPj8xcmBxf4c+N64cVRNzm/mq0WxjrnbfwAVCayoWcOag6KzZvkScY8k3XG4G7hS0wo1QwBVqt,iv:xLVOjECeru2HF23agjqBqhZCqaQQTLw+TaG1LdvNm9I=,tag:Ig5EMymFJJuTNVsTcvFcWw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqKzhla1FSRXpqR3pnQU1l
            bVllRG1SNXNhTEZRM2x6eTc2dm9lWm5Ld2lZCkQ0MkJxWkVrTFV0WDB2S0lvTlhL
            dVZ2Uy9kd1NCOStpWDBOTjlML0RWRW8KLS0tIGpMeUV1S2EwWURkanVZd2tDYkc3
            LzA0Y2R4Myt4ZSszNEFSak8yMWVMVXcKWLa8bz5cexKOCA1oBsdB9S8YtLqo7i1D
            R6T0lHEB7Ty54Fclid/qHXRunEv9VyHjr3Zl/UO6+mTu32h59fDWqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T21:09:17Z"
    mac: ENC[AES256_GCM,data:9UMns0YB9yppkZC6m/XwhrAULuCANuRdqMbdxTQB7DARo/ziMUYnikOF931qN1XUP89b/vbl3XiLXuJeKCdSzJY3KXYoub35WM5B9IYiy5JzisTpr5oz+fCDOZwsUseD2GHgbs1xy5rUfdShQkSbnO4ozRCEfr66Ja0FJxiX8gU=,iv:FzPdN4AR6/Za7rVKoUKLHTDR4HmA+Goro707vG8IlT0=,tag:9sHJpTECSxferjVp1VkV9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: ghcr-login-secret
    annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:jJlHc9OEAeeCdTnfyd/4Ch3eBw9ZovUkmcyaEkXQmKtViAMDToEjsDh68GbBg8uX2/8Es4H7oRYv00qS+FiA4mtGMJUEDbViuryUhFMOqkBfMihTqFRYtO7TyWVB0lMSHxRcZUfOonH4CQOxvlZmjYSNZ10O7rkQXdVLrCiLBcJarS0HShOlBiopOFFT++umDNAXPcxbO50sxxhHKYgNI5rMOapp+ufWGMdeJLDfHmnZ9YJtC1LYSNtkyidmgy9OYkBSVK7gBFlhgYxkNtSJFkhn2L8eqgAsmMIJ94Y71CS1clForJSCl2vGH0VKT1V4ZcO8KqcKnIlGx0FiTmQUrYGG3MltxT2IxsxYrEqlR91AfrYo,iv:k+kKxpDSeJGhKQP6G8GUyk1NuvQaij0Et5Yz5rO1w8Q=,tag:QTgOfAao49oCmOQkonSufA==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqKzhla1FSRXpqR3pnQU1l
            bVllRG1SNXNhTEZRM2x6eTc2dm9lWm5Ld2lZCkQ0MkJxWkVrTFV0WDB2S0lvTlhL
            dVZ2Uy9kd1NCOStpWDBOTjlML0RWRW8KLS0tIGpMeUV1S2EwWURkanVZd2tDYkc3
            LzA0Y2R4Myt4ZSszNEFSak8yMWVMVXcKWLa8bz5cexKOCA1oBsdB9S8YtLqo7i1D
            R6T0lHEB7Ty54Fclid/qHXRunEv9VyHjr3Zl/UO6+mTu32h59fDWqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T21:09:17Z"
    mac: ENC[AES256_GCM,data:9UMns0YB9yppkZC6m/XwhrAULuCANuRdqMbdxTQB7DARo/ziMUYnikOF931qN1XUP89b/vbl3XiLXuJeKCdSzJY3KXYoub35WM5B9IYiy5JzisTpr5oz+fCDOZwsUseD2GHgbs1xy5rUfdShQkSbnO4ozRCEfr66Ja0FJxiX8gU=,iv:FzPdN4AR6/Za7rVKoUKLHTDR4HmA+Goro707vG8IlT0=,tag:9sHJpTECSxferjVp1VkV9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    namespace: udl
    name: ghcr-login-secret
    annotations:
        description: GitHub Container Registry login secret for private images
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:tOVWMcSP5lZi9bxRwAArYCbzWn3MBwblL8lIL3GxXu4rykmQNdHHfhARtfvuy5R9cEEcftH9+z7GAAabNAuEhrB3GMqL2kXmdD7OI+bsoP67ys8uplsGnn7K5icQDjE8EWx4tqb772LhtbxXWj/AjAC76JOxRFOJi0ICwOfUxduiY6qrDgdN2GSukoeGUUomWp2loGSdtt5rhx7Sn8jz/fESginQB6l88P60M5/dK5A83usieXK0wxk3a2o8jzHd6UWAWL6YTffXjVoSZcs0eT5QJnpWpZBlcCKXPfXgIfID5GuAz36mdlVKIwHYoitDqEY8mMRYdJnHDVYkSNCRPT09/StN1sTYUZKqPIZ0hlW0Qdrn,iv:s7UwJTdpXxVQOn/ihyREpaATcntBKcBOWHTBI0YaXRg=,tag:E4v9gadz00LyyXN8LMYXUQ==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqKzhla1FSRXpqR3pnQU1l
            bVllRG1SNXNhTEZRM2x6eTc2dm9lWm5Ld2lZCkQ0MkJxWkVrTFV0WDB2S0lvTlhL
            dVZ2Uy9kd1NCOStpWDBOTjlML0RWRW8KLS0tIGpMeUV1S2EwWURkanVZd2tDYkc3
            LzA0Y2R4Myt4ZSszNEFSak8yMWVMVXcKWLa8bz5cexKOCA1oBsdB9S8YtLqo7i1D
            R6T0lHEB7Ty54Fclid/qHXRunEv9VyHjr3Zl/UO6+mTu32h59fDWqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T21:09:17Z"
    mac: ENC[AES256_GCM,data:9UMns0YB9yppkZC6m/XwhrAULuCANuRdqMbdxTQB7DARo/ziMUYnikOF931qN1XUP89b/vbl3XiLXuJeKCdSzJY3KXYoub35WM5B9IYiy5JzisTpr5oz+fCDOZwsUseD2GHgbs1xy5rUfdShQkSbnO4ozRCEfr66Ja0FJxiX8gU=,iv:FzPdN4AR6/Za7rVKoUKLHTDR4HmA+Goro707vG8IlT0=,tag:9sHJpTECSxferjVp1VkV9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
