---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: citadel
spec:
  encryptedData:
    .dockerconfigjson: AgARHZMv+v/ZozCo5xyl6f4ScPnWdWaar0WAk+O3lAS6wpAdzQY0FcXr4vXX/sol2gdxcUaNwhdxOI2tzfi9OE0bgIHnc3x3VUdZSkhWTLBcuoHPK8SzVV3rcqFdOzLh7/wMhStJV9a0+9yhw1SrePRMHkHczbX8vU2kxLzK748CN1uDgP96AOIekwMN+lWOZ2RvX8hrChAo6re+8IYYE1vS4ztsMXh/eGYj0UdwCXJmMgZ7LVjaEktQTSnczox2+5SWOigyimwaoRiAJ5CZ7TeND8i/HFzpzd/ClrJInB6nZIPLBEqWDbDkk/0btU4r6PL3tqQNhkueKA9nplRsO76q9QrF+GYeXSXyksiT3qaIdukY4rw1A0HBLtAGr815l3+D4yMTcgFn9QxfKP3M8/4NOuyf8x/m4lM+Dzm2VvjeVbjN3ievvqVvio4++vmVRaUyHf6dKFICiObd7bA8/O356CtTKxew6nAQhZvSybPcbU0J4tqqVxu0aI5xt0QAI2f/R6YWGFOcOwTTj8leT9KY/rct9E/3A1sgMGWwfAcNk4laC/IChsTN4QTTCif5fTyAAncFXTZcYXzgMbhs6Tg3QaAac+srmYWXXU+eL/n2M2VQ9xrPBWKrhFBkkdSAVfajmFiO0veYHtNUb4XWZE+wSoIRzNtkYvENE5rlEXvdTbPAEJP3eAZVhe3sgZbtnfjr5CU2s2tdaV3IQMJF9bP+QIWSFpBpyQNQCezD4Rb9a4Gar+bfOAribSezUZDIGF8T06vcPDlCrZwSZbhtk7svxjePy3Yv2e4l9YT8jWygeooc/5j/tOLzG/wXZAnFgH07d7EJEQAI9Q3GfQ4Q2IQQPRaXoaZbjh0uKV4uscXy8LGCdqY91+ZVH0wARYCOhGpftrk/L+FtPd+F1h9mjXiJqv6wwYBOZV5eLXXvrjZIT0see/eeyQb0uMouUl3s9frExjTp6d/1TePuG1wPhA==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: citadel
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBzdpby7dCIGkeFC+Y93aFrlK+wdxrAYKpbKgh/ONErtP7KmA/wSvTHgmLzCQYHBy/2Y6fkfm8icq+M/RorljH9h2EjVERcuL+OqgbsUl1ZR+XsNDeTc8qAdDm6JFc9xaEKcfFOW0kquDYt2fn4+yy3E/AnN0EsW7RhAqwst6ZOMpyvKqair7tnUS63srsGOTRY9kg/rWeNHiVhraCR2tlLHKu2slU6xHyvqC492LO3aexi9nwj2t9NnAxkWz/0DQhaIKN8jXoQapJCLuUTYUZoyr1yD2UC0TEaV1ckl8dD0GQDtok81t6/RBhJh4rBUGLzzJ5YUxdI7TPmnpb27+f0wXmx99J0CuoPYGQaboSmz4PpUoFcpIIgHrON++o0cmHmFJ0QegBu0EKUDIfE5rkuPyFa+kJ44lyJy8PC5RJTV0QAMpbSl2GG+AMcGYnNWkhpslSyf07FmmtcuqyeHtNCqH5SFgoSpBTigCjywsp9VVmVwCW+grcntnzPaHa8YxvAN6mtLq+NjxTKVmXQNDtir1CJExgmv226l3QeTOPv9Y5jYI64BK+sb5YutBKw6EkDn5FQHSu9teBI9y1qnGEsprvSEd5r17IKOU2Li7w0OdzbfEI+xXoKBbiJuNKDwXc2OxC1YzPOkZs/s7Va71OE9Q+nG4NOA7cAdmYQ2I7m15mwLxnAd98XiWEDwOeoYrq07A+x7bmjih8VuWm7byHY+A3ibOQamvunSSNdxnmkSe2c2RGbFeheNt5OjuTiU3KaCgxFoUAl9zk8RHh0Dj/pqV+kA70X2rip4YYgDRJvDXF0B3k18bUj9Pgs9EiCuCRHvtalUA6n8qOuVs7hAq1ByWGSHfSrKkTIh0Vac3jc9MkWYWuwTTd3hW4CvBTpQqqhOuWISz/DBz4jryNQiYzWx3ciecGmyKFcty2WDLt+06u/UGETLP8WETQ5wPhNosje/KP+3hKF058LxBSvew==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: udl
spec:
  encryptedData:
    .dockerconfigjson: AgBqdSEjII0oz5pKlNiqWzn6mJV6psRJiCEFbvCviZqu/1KE53LaVhIfaMThzBAFzpE522IuHJDTByixu2SjgtwUb3rZfyjoc7Ru1FI5vowSeBvCjn03MU14Q0wFdVGGQ4pSX867DrAljQBDIVzZaY/DpLShtl7amW4IOxCyG7oy5faa+Vm9SFJngX7JyFQNEMwF3b9Ovd2hLJ4bAaox65qEVvPiTOirs4eNUL6UZjFwOB6V+uirFVebh8QTIGZD1nwOEFTgmGj35wxMNApuj2BrJT0ebwd5LuBuMlUfDdxDaz2g3vMn5EshJ6qcmoDXgisabLTqWELonnTxpu0EskcNM7VdBiOXKEdtyxentVYMOinWukHKH6AL5I1Dex4VOS66RbQy+Jr3EiaZ4EKgLL+ez4VA+pQj3BAevtfEwpMNuwa0bUN26ZJxW+W2K4PT0QQZrFYECG1pmxvIwKxkEWdFqRYyDxLSKL7kSWDcNARavLVGm1eLS+mBQ0NrU4i9qbko4EbJftNL5M0xR/X2g3RIC1pmY5hd+p01ZD0p+vlrNmo61/opNt14BVAT5vhiWOPK6l6tuMhNrlozIr64MosWDH6925vuavwXECBaoXe1xo4YvWXaTuUA+pTo+uj5Tr+IDL/ya9dp59fJ/ma/5AK8OixMGH+kXHO7Z8pPKsPqY9apHmYHlCeHKTGlmkIOjYN43X6ymoRlwZ/rU2BS8PBMS/vyuBt7Dpy1XznFc01eTLzDUCaNbHJOHkPpC0k+qqPlebagCS8ZipLu+YmVSrZWHgI1OSzwpmj902OU83hATNVP2ami2Jttul3/5EPWm32Ld1IlHRsj3lHAkz9nWIlmPPW70FzxewXdpByNpW/7AYjh0PXMSWL317thnZND+37hylhTC7uW9sXZPN5PcBPfysoC3MHfN5WimYvXAVzSGhgh6TJclS93a7cYzql+p5K8BmrpzFUFOwLAj9brRQ==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: udl
    type: kubernetes.io/dockerconfigjson
