apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: ">=0.10.0"
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 10m
  releaseName: external-secrets
  targetNamespace: external-secrets
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    installCRDs: true
    leaderElect: true
    replicaCount: 2
    metrics:
      service:
        enabled: true
    serviceMonitor:
      enabled: true
      renderMode: skipIfMissing
