apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-replicator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubernetes-replicator
      sourceRef:
        kind: HelmRepository
        name: kubernetes-replicator
  interval: 1h0m0s
  releaseName: kubernetes-replicator
  targetNamespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
